"""Publish only verified BTC exploratory evidence; preserve all existing studies."""
import csv,gzip,html,io,json,shutil,zipfile
from pathlib import Path
from btc_perp_bot.research.archive import canonical,sha
ROOT=Path(__file__).resolve().parents[1];DOC=ROOT/'docs';DOWNLOAD=DOC/'downloads';esc=html.escape
GROUPS={'oi':('BTC OI 충격','btc-oi-20261002'),'persistence':('추세 지속성','btc-persistence-20261002'),'funding':('확정 펀딩','btc-funding-20261002'),'regime':('숏 국면','btc-regime-20261002')}
LABELS={'P_MOM':'가격 추종 대조','O_GROW':'OI 증가 추종','P_FADE':'가격 반전 대조','O_FLUSH':'OI 감소 반전','E_MIX':'현물롱·선물숏 대조','B_MIX':'이진 신호 대조','E_STRICT':'전원합의 숏','H_MIX':'지속성 양방향','H_STRICT':'지속성·엄격 숏','P_FUND_MASK':'가격·펀딩가용 대조','F_JOIN':'고펀딩 방향 추종','F_CROWD':'펀딩혼잡 반대 충격','RG_FLAT':'국면 이탈시 숏 청산','RG_ENTRY':'하락국면에서 숏 시작'}
CONTROLS={'P_MOM','P_FADE','E_MIX','B_MIX','P_FUND_MASK'}
SPECS=['EXPERIMENT_BTC_OI_20261002.md','EXPERIMENT_BTC_PERSISTENCE_20261002.md','EXPERIMENT_BTC_FUNDING_20261002.md','EXPERIMENT_BTC_OI_INFORMATION_20261002.md','EXPERIMENT_BTC_REGIME_20261002.md']
def read(p):return json.loads(gzip.decompress(p.read_bytes())) if p.suffix=='.gz' else json.loads(p.read_text())
def num(v):return '해당 없음' if v is None else f'{v:+.2f}'
def table(head,rows,ident):
 return f'<div class="scroll" role="region" tabindex="0" aria-label="{esc(ident)}"><table id="{esc(ident)}"><thead><tr>'+''.join('<th scope="col">'+esc(v)+'</th>' for v in head)+'</tr></thead><tbody>'+''.join('<tr>'+''.join('<td>'+esc(str(v))+'</td>' for v in row)+'</tr>' for row in rows)+'</tbody></table></div>'
def run():
 DOWNLOAD.mkdir(exist_ok=True);allrows=[];evidence={};base={};public=[];downloads=[];unc=[];annual=[];proof={};pass_count=0
 for group,(label,directory) in GROUPS.items():
  p=ROOT/'runs'/directory;v=read(p/'verification.json');repro=read(p/'reproduction.json');assert repro['all_bytes_equal'];proof[group]={'verification':v,'reproduction':repro};selection=read(p/'selection.json');evidence[group]={'summary':read(p/'summary.json'),'selection':selection,'uncertainty':read(p/'uncertainty.json'),'diagnostics':read(p/'diagnostics.json')}
  for name,g in selection.items():
   if name not in CONTROLS:pass_count+=int(g['passed'])
  for f in sorted(p.glob('*.json.gz')):
   if f.name.startswith('signals-') or '-plan-' in f.name:continue
   r=read(f)
   if 'period' not in r:continue
   m=r.get('summary',r.get('metrics'));name=r.get('family',r.get('strategy'));row={'group':group,'family':name,'period':r['period'],'scenario':r['scenario'],'return_pct':m['return_pct'],'dd_pct':m.get('dd_pct',m.get('max_drawdown_pct')),'sharpe':m['sharpe'],'trades_or_episodes':m.get('trades',m.get('round_trips')),'fees':m['fees'],'impact':m['impact'],'funding':m['funding'],'mean_notional_pct':m.get('mean_exposure',0)*100 if 'mean_exposure' in m else evidence[group]['diagnostics'][f.name]['mean_notional_pct'],'realized_vol_pct':m.get('realized_vol_pct'),'conflict_bars':m.get('unresolved_archive_exposure_bars')};allrows.append(row)
   if r['scenario']=='base':
    base[(name,r['period'])]=row
    years=m.get('annual') or {y:z['return_pct'] for y,z in r['periods']['yearly'].items()};annual.append([LABELS[name],r['period'],*[num(years.get(y)) for y in ['2022','2023','2024','2025','2026']]])
    u=evidence[group]['uncertainty'][r['period']+'-'+name]['mean'][1];ci=u.get('ci_bonferroni2',u.get('ci_bonferroni3'));unc.append([LABELS[name],r['period'],f"{u['mean_daily_pct']:.5f}",f"{ci[0]:.5f} ~ {ci[1]:.5f}"])
  target=DOWNLOAD/f'btc-continuation-{group}.zip'
  with zipfile.ZipFile(target,'w',compression=zipfile.ZIP_STORED) as z:
   for f in sorted(p.iterdir()):
    if f.is_file():info=zipfile.ZipInfo(f.name,(2026,10,2,0,0,0));z.writestr(info,f.read_bytes())
  public.append(target);downloads.append((target.name,label+' 전체 계좌·신호·원장·검산 ZIP'))
 info_dir=ROOT/'runs/btc-oi-information-20261002';iv=read(info_dir/'verification.json');ir=read(info_dir/'reproduction.json');assert ir['all_bytes_equal'];proof['information']={'verification':iv,'reproduction':ir};information={'summary':read(info_dir/'summary.json'),'selection':read(info_dir/'selection.json')}
 target=DOWNLOAD/'btc-continuation-information.zip'
 with zipfile.ZipFile(target,'w',compression=zipfile.ZIP_STORED) as z:
  for f in sorted(info_dir.iterdir()):
   if f.is_file():z.writestr(zipfile.ZipInfo(f.name,(2026,10,2,0,0,0)),f.read_bytes())
 public.append(target);downloads.append((target.name,'연속 OI 특성·학습·예측·검산 ZIP'))
 constraints=read(ROOT/'runs/btc-continuation-20261002/constraints.json');regimes=read(ROOT/'runs/btc-continuation-20261002/regimes.json')
 data={'build':'1002b1','accounts':len(allrows),'candidate_primary_passes':pass_count,'account_rows':allrows,'groups':evidence,'information':information,'constraints':constraints,'regimes':regimes,'proof':proof,'boundary_tests':read(Path('/home/ubuntu/.openclaw/workspace/tmp/btc-continuation-tests.json')),'limitations':['Previously inspected development data, not new OOS','No live execution, partial fills, historical publication vintages or exact liquidation proof','Conditional runs are not independent trials; statistical adjustments do not remove researcher selection','No currently running paper/trading/research daemon']}
 p=DOWNLOAD/'btc-continuation-evidence.json';p.write_bytes(canonical(data));public.append(p);downloads.append((p.name,'전체 요약·기각 기준·불확실성·기존 제약 JSON'))
 p=DOWNLOAD/'btc-continuation-summary.csv'
 with p.open('w',newline='') as f:w=csv.DictWriter(f,fieldnames=list(allrows[0]));w.writeheader();w.writerows(allrows)
 public.append(p);downloads.append((p.name,'198개 조건별 계좌 요약 CSV'))
 assert len(allrows)==198 and pass_count==0
 mainrows=[]
 for name in LABELS:
  a,b=base[(name,'main')],base[(name,'recent')];mainrows.append([LABELS[name]+(' · 대조' if name in CONTROLS else ''),name,num(a['return_pct']),f"{a['dd_pct']:.2f}",num(b['return_pct']),f"{b['dd_pct']:.2f}",f"{a['trades_or_episodes']} / {b['trades_or_episodes']}",f"{a['mean_notional_pct']:.2f} / {b['mean_notional_pct']:.2f}"])
 matrix=[[r['group'],r['family'],r['period'],r['scenario'],num(r['return_pct']),f"{r['dd_pct']:.2f}",r['trades_or_episodes'],f"{r['fees']+r['impact']:.2f}",num(r['funding'])] for r in allrows]
 info_rows=[]
 for key,v in information['summary'].items():
  a,b=v['models']['P_RIDGE'],v['models']['OI_RIDGE'];ci=v['uncertainty'][1]['ci95'];info_rows.append([v['period'],v['availability_minutes'],v['count'],f"{a['mse']:.8f}",f"{b['mse']:.8f}",f"{(b['mse']/a['mse']-1)*100:+.2f}%",f"{ci[0]:.8f} ~ {ci[1]:.8f}"])
 total_files=sum(x['reproduction']['matched_files'] for x in proof.values());total_events=sum(proof[g]['verification']['events'] for g in GROUPS);total_days=sum(proof[g]['verification']['daily_equities'] for g in GROUPS)
 c=constraints['main-C_CHANNEL'];old=[]
 for name in ('E_SPOT','E_PERP','E_LS'):
  a=constraints['main-'+name];b=constraints['recent-'+name];old.append([name,num(a['metrics']['return_pct']),f"{a['metrics']['max_drawdown_pct']:.2f}",num(b['metrics']['return_pct']),f"{a['metrics']['mean_exposure']*100:.2f}",num(a['metrics']['funding'])])
 body='''<!doctype html><html lang="ko"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta http-equiv="Content-Security-Policy" content="default-src 'self'; script-src 'none'; style-src 'self'; img-src 'self' data:; connect-src 'none'; object-src 'none'; base-uri 'none'; form-action 'none'"><title>BTC 연속 연구 · 개선의 조건</title><meta name="description" content="BTC-only 새 가설 9개·198개 조건별 계좌와 연속 OI 예측 비교. 실패·지연·비용·검산을 함께 공개합니다."><link rel="icon" href="assets/icon.svg"><link rel="stylesheet" href="assets/btc-continuation.css"></head><body><a class="skip" href="#results">결과로 이동</a><header><a href="./">BTC RESEARCH</a><nav><a href="#results">기본 결과</a><a href="#proof">검산</a><a href="#downloads">다운로드</a></nav></header><main><p class="eyebrow">BTC-ONLY · 2026.10.02 · BUILD1002b1</p><h1>수익만이 아니라,<br>낙폭과 최근 성과까지.</h1><p class="lead">기존 성과를 세 조건에서 함께 넘어선 전략은 아직 없습니다.</p><div class="facts"><article><b>198</b><span>조건별 가상 계좌</span></article><article><b>0 / 9</b><span>새 기본 후보 관문 통과</span></article><article><b>미가동</b><span>실거래 · 상시 모의운영</span></article></div><p class="boundary">이미 본 역사 자료에서의 탐색입니다. Binance 자료이며 Hyperliquid 실적·새 미사용 OOS가 아닙니다. 같은 자료·가설을 바꿔 성공을 선언하지 않았습니다. 조건별 계좌 수는 독립된 증거 수가 아닙니다.</p>
<section><h2>이번에 달라진 근거</h2><ul><li><b>OI 증가 추종:</b> 4년 +27.02% / DD 4.24%, 최근 +2.56%. 가격-only 최근 +3.33%보다 낮고, 추가 가용4시간에서는 최근 −1.32%로 바뀝니다.</li><li><b>추세 지속성:</b> 4년 +75.25%지만 DD 27.73%·실현변동성19.95%, 최근 −0.26%. 위험과 일관성을 함께 개선하지 못했습니다.</li><li><b>확정 펀딩:</b> 높은 펀딩 방향 추종 +2.32%, 혼잡 반대 충격 −2.81%. 최근에는 두 기본 모두 0거래라 0%는 성공 근거가 아닙니다.</li><li><b>숏 국면 제한:</b> 국면 이탈시 청산은 최근 +9.49% / DD 6.19%. 그러나 4년 +42.74% / DD 16.71%로 기존 현물을 종합적으로 능가하지 못합니다. 진입에만 적용하면 최근 +12.96%지만 4년 DD 22.01%입니다.</li><li><b>작은 OI 변화의 연속 예측:</b> 고정 Ridge에 OI를 추가해도 기본 예측오차가 주구간 +1.16%, 최근 +1.73% 커졌습니다. 이것은 계좌 수익률이 아닙니다.</li></ul></section>
<section id="results"><h2>모든 기본 후보와 대조군</h2><p>주:2022–2025, 최근:2026.01–08. 구간마다 1,000 USDT, 구간 안 계좌 연속. 수익·DD·평균 명목노출은 %. OI/펀딩은 거래당 손절위험0.5%, 지속성/국면은 연변동성목표20%이므로 동일위험 순위표가 아닙니다. 거래 수는 전자는 종료거래, 후자는 완전 보유구간입니다.</p>'''
 body+=table(['규칙','ID','4년 수익','4년 DD','최근 수익','최근 DD','주/최근 거래','주/최근 평균노출'],mainrows,'base-results')
 body+='''<p>새 후보 9개 모두 사전 기준 탈락. 좋은 임계값·낮은 위험·지연 조건으로 기본을 교체하지 않았습니다. 기본 수익>52.84%, DD≤13.56%, 최근수익>4.63%와 최근DD≤10.45%, 연도·비용·지연·거래수·위험 조건을 함께 적용했습니다. 상세 기준은 아래 사전명세를 확인하세요.</p></section><section><h2>기존 수익의 제약은 무엇이었나</h2><p>기존 원장을 다시 분해했으며 기존 전략 전체를 재계산하지 않았습니다. E_LS 롱 +377.77 / 숏 −138.94 USDT, 최근 롱 +8.14 / 숏 +38.14 USDT. 숏의 필요성이 기간마다 달랐습니다. 과거20일 국면별 평가손익에서 횡보 중 숏 −131.22 USDT가 나왔지만, 이 귀속을 필터 수익으로 착각하지 않고 위 RG 계좌로 별도 검증했습니다.</p>'''
 body+=table(['기존 후보','4년 수익%','4년 DD%','최근 수익%','주 평균노출%','주 펀딩 USDT'],old,'existing-results')
 body+='''<p>구조 C_CHANNEL은 76신호→36거래, 평균 명목노출1.35%·보유시간7.75%, 초기손절예산 평균83.17% 사용. 재시험은 13신호→10거래, 평균 명목0.17%였습니다. 주문단위 내림만으로 낮은 수익을 설명할 수 없습니다. 선물의 펀딩·수량단위·자산경로 차이도 있어 현물/선물 손익 차이를 펀딩만의 효과로 해석하지 않습니다.</p><details><summary>기본 규칙의 연도별 수익률</summary>'''+table(['규칙','기간','2022','2023','2024','2025','2026'],annual,'annual-results')+'''</details></section><section><h2>연속 OI 정보 관문</h2><p>2022 학습용, 주평가2023–2025·최근2026.01–08. 과거365일로 분기별 재학습, 26h purge, alpha10·8개 가격/펀딩 vs 14개 OI 포함 특징을 고정했습니다. 동일 가용마스크·완료 관측만 사용. 24h 라벨이 구간 끝을 넘는 표본은 제외했습니다. MSE 차이 CI에 0이 들어가며 모든 가용지연에서 오차 개선에 실패했습니다. 예측오차를 매매 수익으로 발표하지 않습니다.</p>'''
 body+=table(['기간','추가 가용분','표본','가격 MSE','OI MSE','오차 증감','MSE 개선 14일블록 95% CI'],info_rows,'information-results')
 body+='''</section><section><h2>모든 실패·민감도 보존</h2><p>수수료+슬리피지, 실제 펀딩, BTC 최소수량/최소금액, 종료비용 반영. OI raw+5m는 관측완료 가정이지 과거 실제 공표시각이 아닙니다. 0/누락·정확 룩백을 보존했고 추가 가용0/60/240/1440분을 구분했습니다. 과거 규정·호가·부분체결·정확한 청산·봉내 경로는 복원하지 않았습니다.</p><details id="matrix"><summary>198개 조건별 계좌 전체 보기</summary>'''+table(['연구','규칙','기간','조건','수익%','DD%','거래/보유구간','체결비용 USDT','펀딩 USDT'],matrix,'all-accounts')+'''</details><details><summary>기본 일평균 수익의 다중비교 보정 구간</summary><p>14일 달력/거래일 블록 2,000회. OI·펀딩·국면은2후보, 지속성은3후보 보정. 7/28일과 대조군 차이는 원본 JSON. 탐색 누적 편향·다른 시장국면을 해결하는 증명은 아닙니다. 무거래의 [0,0]은 미래 무위험을 뜻하지 않습니다.</p>'''+table(['규칙','기간','일평균%','보정 CI%'],unc,'uncertainty-results')+'</details></section>'
 body+=f'''<section id="proof"><h2>숫자를 확인한 범위</h2><p><b>{total_events:,}개 이벤트 · {total_days:,}개 일말 자산</b>을 별도 Decimal 현금·재고 원장과 대조했습니다. 원본 BTC 가격·펀딩 신호, OI 정확 격자, 롱숏 부호, 지연·최소수량·미래교란을 확인했습니다. 연속 OI는 {iv['paired_predictions']:,}쌍 예측을 독립 정규방정식으로 검산했습니다.</p><p><b>{total_files}개 산출물 소켓차단 재현, 전부 바이트 일치.</b> 17개 추가 경계검사 통과. 기존 자료감사 전체나 ETH 계산을 반복하지 않았습니다. 남은5개 상충시간은 입력·보유·체결 노출을 보존했습니다. 새 신호는 해당 상충의 거래량/시가를 사용하지 않고, 무거래5m봉 체결을 금지했습니다. 검산은 모형의 수치·시계 증거이지 미래수익·실체결의 증거가 아닙니다.</p></section>'''
 body+='''<section><h2>현재 연구 한계와 실행 상태</h2><p>정해진 회차나 시각을 기다리지 않고 제약분해→OI→지속성→펀딩→연속 OI→국면 가설을 이어서 계산했습니다. 실패 뒤 규칙을 바꿔 통과시키지 않았습니다. 현재 확보한 검증 입력에서 다음 독립 가설을 정당화할 근거가 부족합니다. 남은 창·임계값·조합·모형 크기의 변경은 같은 자료에서의 추가 선택 위험입니다.</p><p>강제청산과 자발적 축소를 나누려면 실제 이벤트 이력, 주문대기열·역선택에는 시점별 호가/체결 순서, ETF·온체인에는 최초 공표·수정 이력이 필요합니다. 현재 검산된 입력에는 이 증거가 없습니다. 그런 자료가 공개 세계 어디에도 없다는 주장이나 BTC 수익전략이 불가능하다는 결론은 아닙니다.</p><p><b>이 페이지는 정적 연구 기록입니다.</b> 상시 연구·모의운영·실거래 서비스는 가동하지 않았습니다. 종료 후 백그라운드에서 모델이 계속 연구한다고 가정하지 않습니다. 이 결과를 실전 채택하지 않습니다.</p></section><section id="downloads"><h2>직접 확인할 자료</h2><div class="downloads">'''
 for filename,label in downloads:body+=f'<a href="downloads/{esc(filename)}" download>{esc(label)} ↓</a>'
 body+='</div><h3>성과 전 커밋한 명세</h3><ul>'+''.join(f'<li><a href="{f}">{f}</a></li>' for f in SPECS)+'''</ul><p>출처 구분: <a href="https://www.bis.org/publ/work1087.htm">BIS Crypto carry</a>는 공식 요약/초록, <a href="https://www.aqr.com/Insights/Research/Journal-Article/Time-Series-Momentum">AQR Time Series Momentum</a>은 저자기관 요약을 새로 확인했습니다. 이를 BTC 규칙의 원문 재현·수익 증거로 인용하지 않았습니다. Binance 공식 public-data README는 원문 확인, OI 개발자 페이지/Academy는 빈 추출, CME 교육 페이지는403으로 전문 확인에 실패했습니다.</p></section><footer><a href="strategy-lab.html">기존 전략 비교</a> · <a href="structure-lab.html">구조 5후보</a> · <a href="https://github.com/JavisLab/btc-perp-bot">연구 코드</a><p>BTC-only · 실거래 연결 없음 · BUILD1002b1</p></footer></main></body></html>'''
 p=DOC/'btc-continuation.html';p.write_text(body);public.append(p)
 css='''*{box-sizing:border-box}html{scroll-behavior:smooth}body{margin:0;background:#f7f7f2;color:#182621;font:16px/1.7 system-ui,sans-serif}a{color:#176350;text-underline-offset:4px}header{display:flex;justify-content:space-between;gap:20px;padding:22px max(20px,calc((100vw - 1120px)/2));background:#fff;border-bottom:1px solid #dce2db;flex-wrap:wrap}header>a{font-weight:800;letter-spacing:.1em;text-decoration:none}nav{display:flex;gap:20px;flex-wrap:wrap}main{max-width:1160px;margin:auto;padding:48px 20px}h1{font-size:clamp(2.1rem,5vw,4rem);line-height:1.2;letter-spacing:-.055em;margin:18px 0}h2{font-size:1.7rem;letter-spacing:-.03em}h3{font-size:1.1rem}.lead{font-size:1.3rem;max-width:800px}.eyebrow{font-size:.8rem;letter-spacing:.11em;color:#5f7066}.facts{display:grid;grid-template-columns:repeat(3,1fr);gap:12px;margin:30px 0}.facts article{padding:20px;background:#e3eee5;border-radius:14px}.facts b{display:block;font-size:2.2rem}.facts span{display:block;font-size:.86rem}.boundary{padding:18px;border-left:4px solid #bb6b3a;background:#fff0e1}section{margin:50px 0}li{margin:12px 0}p,li,td,a{overflow-wrap:anywhere}.scroll{overflow:auto;border:1px solid #d7dfd7;border-radius:9px;background:#fff;margin:20px 0;max-height:650px}.scroll:focus-visible,summary:focus-visible,a:focus-visible{outline:3px solid #c47938;outline-offset:4px}table{border-collapse:collapse;min-width:900px;width:100%;font-size:.84rem}th,td{padding:11px 13px;text-align:right;border-bottom:1px solid #e1e7e1;white-space:nowrap}th:first-child,td:first-child,td:nth-child(2){text-align:left}th{background:#e8eee8;position:sticky;top:0}tbody tr:nth-child(even){background:#f7faf5}details{border:1px solid #d7dfd7;background:white;padding:14px 18px;margin:18px 0;border-radius:9px}summary{cursor:pointer;font-weight:700}.downloads{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px}.downloads a{display:block;background:#e6ede4;border-radius:8px;padding:14px}footer{border-top:1px solid #c7d3c8;padding:24px 0;color:#617166;font-size:.9rem}.skip{position:absolute;left:12px;top:-70px;background:white;padding:12px}.skip:focus{top:10px}@media(max-width:550px){main{padding:32px 16px}header{padding:18px 16px}nav{gap:14px;font-size:.86rem}.facts{gap:7px}.facts article{padding:12px 8px}.facts b{font-size:1.55rem}.facts span{font-size:.75rem}.downloads{grid-template-columns:1fr}details{padding:12px}h2{font-size:1.4rem}section{margin:36px 0}}'''
 p=DOC/'assets/btc-continuation.css';p.write_text(css);public.append(p)
 for file in ['index.html','strategy-lab.html','structure-lab.html']:
  p=DOC/file;text=p.read_text()
  if 'btc-continuation.html' not in text:text=text.replace('<nav aria-label="주 메뉴">','<nav aria-label="주 메뉴"><a href="btc-continuation.html">BTC 연속 연구 ↗</a>',1);p.write_text(text)
  public.append(p)
 public.extend(DOC/f for f in SPECS)
 manifest={str(p.relative_to(DOC)):{'sha256':sha(p.read_bytes()),'bytes':p.stat().st_size} for p in public};dest=ROOT/'runs/btc-continuation-20261002/public-manifest.json';dest.write_bytes(canonical(manifest));print(json.dumps({'accounts':len(allrows),'primary_passes':pass_count,'reproduced_files':total_files,'events':total_events,'daily':total_days,'public_files':len(manifest)}))
if __name__=='__main__':run()
