"""Publish all audited macro-vintage accounts, including the rejected primary."""
import csv,json,zipfile
from pathlib import Path
from build_btc_web_report import read,table,esc
from btc_perp_bot.research.archive import canonical,sha
ROOT=Path(__file__).resolve().parents[1];DOC=ROOT/'docs';D=DOC/'downloads';R=ROOT/'runs/btc-macro-vintage-20261002';DATA=ROOT/'data/btc-macro-vintage-20261002'
def run():
 s=read(R/'summary.json');v=read(R/'verification.json');replay=read(R/'reproduction.json');sel=read(R/'selection.json');unc=read(R/'uncertainty.json');assert replay['all_bytes_equal'] and replay['matched_files']==62 and v['accounts']==40 and not sel['passed'];rows=[];base=[];years=[];cost=[];ci=[];sides=[];diag=read(R/'diagnostics.json')
 for key,x in s.items():
  p,n,c=key.split('-');m=x['metrics'];rows.append({'strategy':n,'period':p,'scenario':c,**{k:m[k] for k in ('return_pct','max_drawdown_pct','realized_vol_pct','sharpe','round_trips','fees','impact','funding','mean_exposure','max_exposure')}})
  if c!='base':continue
  years.append([n,p,*[f"{x['annual'][y]['return_pct']:+.2f}" if y in x['annual'] else '해당 없음' for y in ('2022','2023','2024','2025','2026')]])
  cost.append([n,p,f"{m['gross_pnl']:+.2f}",f"{m['fees']+m['impact']:.2f}",f"{m['funding']:+.2f}",f"{m['mean_exposure']*100:.2f}",f"{m['realized_vol_pct']:.2f}"])
  for ctrl in ('E_SPOT','MB_PRICE','MB_CASH'):
   q=unc[p+'-'+n]['vs_'+ctrl][1]['ci95'];ci.append([n,p,ctrl,f'{q[0]:+.5f} ~ {q[1]:+.5f}'])
  side=diag[key+'.json.gz']['sides'];sides.append([n,p,f"{side['BS']['net']:+.2f}",f"{side['BP']['net']:+.2f}"])
  if p=='main':
   b=s['recent-'+n+'-base']['metrics'];base.append([n+(' · 기본' if n=='MB_RATE' else ' · 대조'),f"{m['return_pct']:+.2f}",f"{m['max_drawdown_pct']:.2f}",f"{b['return_pct']:+.2f}",f"{b['max_drawdown_pct']:.2f}",f"{m['round_trips']} / {b['round_trips']}"])
 old=[]
 for p in ('main','recent'):
  m=read(ROOT/f'runs/search-1458/{p}-E_SPOT.json.gz')['metrics'];old.append([p,f"{m['return_pct']:+.2f}",f"{m['max_drawdown_pct']:.2f}",f"{m['realized_vol_pct']:.2f}"])
 evidence={'build':'1002m1','account_rows':rows,'summary':s,'uncertainty':unc,'selection':sel,'verification':v,'reproduction':replay,'data_audit':read(DATA/'audit.json'),'data_verification':read(DATA/'verification.json'),'events':read(DATA/'events.json'),'scope':'BTC-only development; not unexpected monetary shocks, live execution, or untouched OOS'}
 (D/'btc-macro-evidence.json').write_bytes(canonical(evidence))
 with (D/'btc-macro-summary.csv').open('w',newline='') as f:w=csv.DictWriter(f,fieldnames=list(rows[0]));w.writeheader();w.writerows(rows)
 with zipfile.ZipFile(D/'btc-macro-evidence.zip','w',compression=zipfile.ZIP_STORED) as z:
  files=[(p,'accounts/'+p.name) for p in sorted(R.iterdir()) if p.is_file()]+[(p,'macro-data/'+str(p.relative_to(DATA))) for p in sorted(DATA.rglob('*')) if p.is_file()]
  for name in ('collect_btc_macro_data.py','collect_btc_macro_vintage_data.py','btc_macro_vintage_study.py','verify_btc_macro_vintage_study.py','test_btc_macro_vintage_study.py','reproduce_btc_macro_vintage_study.py'):files.append((ROOT/'tools'/name,'source/'+name))
  for p,name in files:z.writestr(zipfile.ZipInfo(name,(2026,10,2,0,0,0)),p.read_bytes())
 body='''<!doctype html><html lang="ko"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta http-equiv="Content-Security-Policy" content="default-src 'self';script-src 'none';style-src 'self';img-src 'self' data:;connect-src 'none';object-src 'none';base-uri 'none';form-action 'none'"><title>BTC 거시정보 검증 · FOMC 금리 재평가</title><link rel="icon" href="assets/icon.svg"><link rel="stylesheet" href="assets/btc-continuation.css"></head><body><a class="skip" href="#results">결과로 이동</a><header><a href="./">BTC RESEARCH</a><nav><a href="btc-web-research.html">앞선 120계좌</a><a href="btc-risk-research.html">위험배분 30계좌</a><a href="#downloads">다운로드</a></nav></header><main><p class="eyebrow">BTC-ONLY · BUILD1002m1</p><h1>수익은 플러스였지만,<br>낙폭 기준을 넘었습니다.</h1><p class="lead">FOMC 이후 금리 재평가를 BTC에 반영했습니다. 기본 후보는 4년 +52.88%, 최근 +6.39%였지만 낙폭과 위험이 커졌고, BTC 가격만 본 대조군보다도 약했습니다.</p><div class="facts"><article><b>40</b><span>추가 가상계좌</span></article><article><b>기각</b><span>MB_RATE 기본 후보</span></article><article><b>37</b><span>정례회의 과거 빈티지</span></article></div><p class="boundary">2022–2025년과 2026.01–08의 이미 본 개발 자료입니다. 미사용 OOS·실전 수익·최적 전략이 아닙니다. 최근은 5회 정책회의뿐이며 대조군을 새 기본으로 승격하지 않았습니다.</p><section id="results"><h2>같은 달력·위험, 다른 정보</h2><p>각 1,000USDT. 금리 상승→BTC 숏·하락→현물 롱이 MB_RATE, 반대 방향은 MB_INV, 직전 완료 BTC 가격방향은 MB_PRICE, 이벤트만 현금은 MB_CASH입니다. 그 외 시간은 기존 E_SPOT 그대로입니다. 수익·낙폭은 %.</p>'''
 body+=table(['규칙','4년 수익','4년 DD','최근 수익','최근 DD','주/최근 보유구간'],base,'base-results')
 body+='<h3>기존 기준 · 저장 결과 참조</h3>'+table(['E_SPOT 기간','수익%','DD%','연변동성%'],old,'baseline-results')
 body+='''<p>기본 주 낙폭 19.25%는 상한13.56%를 넘었고, 연변동성14.59%도 상한13.34%를 넘었습니다. Sharpe0.79935는0.8 미달이며 기준을 반올림해 통과시키지 않았습니다. 비용2배·추가1/24시간 지연에서는 양기간 수익이 양수였지만, 이 사실만으로 종합 기각을 뒤집지 않습니다.</p></section><section id="availability"><h2>관측 시각과 공개 시각을 분리</h2><p>미 국채 일별 금리는 당일 시장 관측값이지만, 당시 대중에게 공개된 시점은 다릅니다. 현재 Treasury XML의 갱신 날짜 대신 ALFRED의 날짜별 과거 빈티지 CSV를 사용했습니다. 회의 다음 날부터 처음 값이 있는 빈티지 v를 확인하고, 미국 현지 날짜가 끝난 뒤인 v+2일00UTC부터만 판단합니다. 기본 체결은 그로부터1시간 뒤, 고정 이벤트창은5일입니다.</p><p>최초 d+1 고정안은 2025-06-19 미국 공휴일 때문에37회 중36회만 완전했습니다. 성과계산 전 자료 단계에서 보류하고, 별도 가설·명세로 실제 공개 빈티지를 기다리도록 바꿨습니다. 이 실패와 결측 CSV를 보존했습니다. 확정되지 않은 값을 오늘 자료로 소급 보충하지 않았습니다.</p><p>일별 2년물 금리차는 고빈도 식별된 ‘예상외 정책충격’이 아닙니다. 정책의 인과효과나 원논문의 직접 재현으로 해석하지 않습니다. 날짜 단위 빈티지도 정확한 분 단위 수신 기록은 아닙니다.</p></section><section><h2>비용·위험·불확실성</h2><p>완료현물20일 변동성으로 목표20%·명목1배 상한. 현물롱/선물숏, 현물0.00001BTC·최소5USDT·수수료10bp, 선물0.001BTC·최소50USDT·수수료5bp, 양쪽충격1.5bp, 5%p 재조정밴드·최종청산비용·실제 펀딩 포함입니다. 정산 순간가격 대신 원시 시간봉 mark 시가를 썼으며 실제 호가·부분체결·과거 주문규정은 복원하지 못했습니다.</p><p>이벤트에서 비중이 커지는 경우가 있어 단순 수익 증가를 알파로 부르지 않았습니다. 주32회·최근5회의 희소 사건과 누적 가설 선택 편향이 남습니다.</p><details><summary>연도별 수익</summary>'''+table(['규칙','기간','2022','2023','2024','2025','2026'],years,'annual-results')+'</details><details><summary>가격손익·비용·펀딩·노출</summary>'+table(['규칙','기간','가격손익USDT','비용USDT','펀딩USDT','평균노출%','연변동성%'],cost,'cost-results')+'</details><details><summary>현물 롱·선물 숏 귀속</summary>'+table(['규칙','기간','롱 순손익USDT','숏 순손익USDT'],sides,'side-results')+'</details><details><summary>대조군 대비 불확실성</summary><p>14일 블록2,000회95%구간, %/일. 7/28일 결과도 JSON에 보존했습니다.</p>'+table(['규칙','기간','대조군','일수익차 95%구간'],ci,'uncertainty-results')+'</details></section><section><h2>좋은 조건만 고르지 않았습니다</h2><details id="matrix"><summary>40개 조건별 계좌</summary>'
 body+=table(['규칙','기간','조건','수익%','DD%','연변동성%','보유구간','비용USDT'],[[r['strategy'],r['period'],r['scenario'],f"{r['return_pct']:+.2f}",f"{r['max_drawdown_pct']:.2f}",f"{r['realized_vol_pct']:.2f}",r['round_trips'],f"{r['fees']+r['impact']:.2f}"] for r in rows],'all-accounts')+'</details></section>'
 body+=f'''<section id="proof"><h2>독립 검산</h2><p>37회·38빈티지 CSV를 Decimal 금리차와 공식 달력으로 대조했습니다. 원시 BTC ZIP329개에 연결된 {v['raw_daily_decisions']:,}개 판단, 폐형식 수량 {v['independent_target_quantities']:,}개·무거래 {v['no_trade_decisions']:,}개, {v['raw_mark_funding_events']:,}개 실제 펀딩 및 {v['events']:,}개 원장이벤트·{v['daily_equities']:,}개 일말 자산을 별도 계산했습니다. 최대 수치차2×10⁻¹¹, 7개 경계검사 통과, 62파일 소켓 차단 바이트 일치.</p><p>연구 목표는 아직 미완료입니다. 이 정적 페이지는 작업 지속이나 실거래 상태를 보장하는 표시가 아닙니다.</p></section><section id="downloads"><h2>검증 자료</h2><div class="downloads"><a download href="downloads/btc-macro-evidence.zip">40계좌·빈티지·검산 ZIP ↓</a><a download href="downloads/btc-macro-evidence.json">전체 수치·불확실성 JSON ↓</a><a download href="downloads/btc-macro-summary.csv">40조건 요약 CSV ↓</a></div><p><a href="EXPERIMENT_BTC_MACRO_VINTAGE_20261002.md">성과 전 새 명세</a> · <a href="EXPERIMENT_BTC_MACRO_20261002.md">최초 자료실패 명세</a> · <a href="BTC_WEB_RESEARCH_20261002.md">원문·검색 기록</a></p></section><footer>BUILD1002m1 · BTC-only · 실거래 없음</footer></main></body></html>'''
 (DOC/'btc-macro-research.html').write_text(body)
 p=DOC/'btc-web-research.html';old=p.read_text()
 if 'id="macro-followup"' not in old:p.write_text(old.replace('<h1>','<p id="macro-followup" class="boundary">후속 40계좌: <a href="btc-macro-research.html">FOMC 이후 금리 재평가 검증 ↗</a></p><h1>',1))
 files=['btc-macro-research.html','btc-web-research.html','downloads/btc-macro-evidence.zip','downloads/btc-macro-evidence.json','downloads/btc-macro-summary.csv','EXPERIMENT_BTC_MACRO_VINTAGE_20261002.md','EXPERIMENT_BTC_MACRO_20261002.md','BTC_WEB_RESEARCH_20261002.md','assets/btc-continuation.css','assets/icon.svg'];manifest={n:{'sha256':sha((DOC/n).read_bytes()),'bytes':(DOC/n).stat().st_size} for n in files};o=ROOT/'runs/btc-macro-report-20261002';o.mkdir(exist_ok=True);(o/'public-manifest.json').write_bytes(canonical(manifest));print(json.dumps({'accounts':len(rows),'public_files':len(files)}))
if __name__=='__main__':run()
