"""Two newly audited hypotheses, all conditions, no ex-post promotion."""
import csv,json,zipfile
from pathlib import Path
from build_btc_web_report import read,table
from btc_perp_bot.research.archive import canonical,sha
ROOT=Path(__file__).resolve().parents[1];DOC=ROOT/'docs';D=DOC/'downloads';MINING=ROOT/'data/btc-mining-20261002'
def run():
 rows=[];base=[];annual=[];cost=[];sides=[];ci=[];proof=[];studies={}
 for tag,folder,primary,count in [('MINING','btc-mining-20261002','HG_REC',56),('SHOCK','btc-shock-20261002','SH_REV',40)]:
  R=ROOT/'runs'/folder;s=read(R/'summary.json');v=read(R/'verification.json');rep=read(R/'reproduction.json');sel=read(R/'selection.json');unc=read(R/'uncertainty.json');assert rep['all_bytes_equal'] and v['accounts']==count and not sel['passed'];studies[tag]={'summary':s,'verification':v,'reproduction':rep,'selection':sel,'uncertainty':unc,'information':read(R/('information-age.json' if tag=='MINING' else 'shock-incidence.json'))};diag=read(R/'diagnostics.json') if tag=='MINING' else None
  proof.append([tag,v.get('raw_daily_decisions',v.get('raw_signal_decisions')),v['independent_target_quantities'],v['no_trade_decisions'],v['events'],v['daily_equities'],rep['matched_files']])
  for key,e in s.items():
   p,n,c=key.split('-');m=e['metrics'] if tag=='MINING' else e;dd='max_drawdown_pct' if tag=='MINING' else 'dd_pct';row={'experiment':tag,'strategy':n,'period':p,'scenario':c,'return_pct':m['return_pct'],'max_drawdown_pct':m[dd],**{k:m[k] for k in ('realized_vol_pct','sharpe','round_trips','fees','impact','funding','mean_exposure','max_exposure')}};rows.append(row)
   if c!='base':continue
   yy={y:z['return_pct'] for y,z in e['annual'].items()} if tag=='MINING' else m['annual'];annual.append([n,p,*[f'{yy[y]:+.2f}' if y in yy else '해당 없음' for y in ('2022','2023','2024','2025','2026')]]);cost.append([n,p,f"{m['gross_pnl' if tag=='MINING' else 'gross']:+.2f}",f"{m['fees']+m['impact']:.2f}",f"{m['funding']:+.2f}",f"{m['mean_exposure']*100:.2f}",f"{m['realized_vol_pct']:.2f}"])
   side=diag[key+'.json.gz']['sides'] if diag else m['sides'];sides.append([n,p,f"{side['BS' if diag else 'long']['net']:+.2f}",f"{side['BP' if diag else 'short']['net']:+.2f}"])
   for ctrl in ('E_SPOT','HG_HASH','HG_STRESS') if tag=='MINING' else ('E_SPOT','SH_MOM','SH_SMALL'):
    z=unc[p+'-'+n]['vs_'+ctrl][1]['ci95'];ci.append([n,p,ctrl,f'{z[0]:+.5f} ~ {z[1]:+.5f}'])
   if p=='main':
    r=s['recent-'+n+'-base'];r=r['metrics'] if tag=='MINING' else r;base.append([n+(' · 기본' if n==primary else ' · 대조'),f"{m['return_pct']:+.2f}",f"{m[dd]:.2f}",f"{r['return_pct']:+.2f}",f"{r[dd]:.2f}",f"{m['round_trips']} / {r['round_trips']}"])
 evidence={'build':'1002f1','account_rows':rows,'studies':studies,'mining_data_audit':read(MINING/'prepare-audit.json'),'scope':'BTC-only development; mining availability assumptions, not complete original vintages; shocks not confirmed liquidations; author selection and cumulative research selection remain'};(D/'btc-frontier-evidence.json').write_bytes(canonical(evidence))
 with (D/'btc-frontier-summary.csv').open('w',newline='') as f:w=csv.DictWriter(f,fieldnames=list(rows[0]));w.writeheader();w.writerows(rows)
 with zipfile.ZipFile(D/'btc-frontier-evidence.zip','w',compression=zipfile.ZIP_STORED) as z:
  files=[]
  for tag,folder in [('mining','btc-mining-20261002'),('shock','btc-shock-20261002')]:files += [(p,tag+'/'+p.name) for p in sorted((ROOT/'runs'/folder).iterdir()) if p.is_file()]
  files += [(MINING/name,'mining-data/'+name) for name in read(MINING/'prepare-audit.json')['source_files']];files += [(MINING/n,'mining-data/'+n) for n in ('prepared.json','prepare-audit.json','initial-audit.json','formula-audit.json')]
  for n in ('prepare_btc_mining_data.py','btc_mining_study.py','verify_btc_mining_study.py','test_btc_mining_study.py','reproduce_btc_mining_study.py','btc_shock_study.py','verify_btc_shock_study.py','test_btc_shock_study.py','reproduce_btc_shock_study.py','btc_session_study.py','btc_target_ledger.py','btc_persistence_study.py'):files.append((ROOT/'tools'/n,'source/'+n))
  for p,n in files:z.writestr(zipfile.ZipInfo(n,(2026,10,2,0,0,0)),p.read_bytes())
  z.writestr(zipfile.ZipInfo('DATA-SOURCES.txt',(2026,10,2,0,0,0)), 'BTC Blockchain.com public charts and public Bitcoin block/header observations. Coin Metrics free community BTC CSV: https://github.com/coinmetrics/data ; CC BY-NC 4.0 https://creativecommons.org/licenses/by-nc/4.0/ . Research-only archive; not all raw BTC price ZIPs/common dependencies included. See preregistration/source journal and repository.\n')
 body='''<!doctype html><html lang="ko"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta http-equiv="Content-Security-Policy" content="default-src 'self';script-src 'none';style-src 'self';img-src 'self' data:;connect-src 'none';object-src 'none';base-uri 'none';form-action 'none'"><title>BTC 후속 검증 · 채굴 상태와 가격 충격</title><link rel="icon" href="assets/icon.svg"><link rel="stylesheet" href="assets/btc-continuation.css"></head><body><a class="skip" href="#results">결과로 이동</a><header><a href="./">BTC RESEARCH</a><nav><a href="btc-web-research.html">연구 기록</a><a href="btc-position-research.html">앞선 포지션 검증</a><a href="#downloads">다운로드</a></nav></header><main><p class="eyebrow">BTC-ONLY · BUILD1002f1</p><h1>채굴 회복과 충격 반전,<br>모두 기준에 못 미쳤습니다.</h1><p class="lead">공개 트레이더의 채굴 회복 가설과 학술 논문의 큰 가격 충격 뒤 반전을 별도로 검증했습니다. 사후 최고점 수익이나 비용 전 수익을 그대로 쓰지 않았습니다.</p><div class="facts"><article><b>96</b><span>새 조건별 가상계좌</span></article><article><b>기각</b><span>두 기본 후보</span></article><article><b>2,466일</b><span>채굴 원자료 감사</span></article></div><p class="boundary">2022–2025와2026.01–08은 이미 본 개발 자료입니다. 신규 OOS·실전 성과·최적 전략이 아닙니다. 96계좌는 조건별 계좌이지96개의 독립 경제 가설이 아닙니다.</p><section id="results"><h2>기본과 대조군 전체</h2><p>각1,000USDT, 수익·최대낙폭(DD)은 %. HG는 현물 롱/반증 선물 숏, SH는 선물 롱숏입니다.</p>'''+table(['규칙','4년 수익','4년 DD','최근 수익','최근 DD','주/최근 보유구간'],base,'base-results')
 body+='''<p>기존 E_SPOT 저장 기준은 주+52.84%·DD13.56%, 최근+4.63%·DD10.45%입니다. HG_REC는 주 수익·DD와 최근 수익 등이 미달했고, SH_REV는 주 손실과 최근 수익 미달로 기각됐습니다. 더 늦은 자료 한 조건이나 대조군의 한 구간만 골라 기본을 교체하지 않았습니다.</p></section><section><h2>채굴 자료가 실제로 추가하는 것은?</h2><p>HG_REC는 기존 가격 추세 E_SPOT에 ‘해시율30일 평균≥60일 평균’인 날만 참여합니다. HG_STRESS는 반대 상태, HG_HASH는 가격 추세를 제거한 해시 상태만, HG_INV는 기본 허용 비중의 정확한 반대입니다. 채굴자 운영 압박과 회복을 검정하지만, 해시율은 블록 도착에서 추정한 값이지 순매도량이 아닙니다. 전력·장비·정책 변화도 영향을 줍니다.</p><p>원문에서 제시한5000%는 매수부터 사후 사이클 최고점까지의 수익이며, 정해진 청산 규칙의 연속 계좌 성과가 아니었습니다. 저자 기록의2019 재도색 수정과2024 자료 공급자 중단·변경도 확인했습니다.</p><h3>누락 3일을 원시 블록으로 확인</h3><p>Blockchain.com 차트는2025-11-13~15가 빠져 있었고, 짧은 기간 재조회도 같았습니다. 이3일만 공개 BTC 블록437개의 연속 높이·일경계와 헤더6개의 이중 SHA256·난이도로 재구성했습니다. 독립 Coin Metrics 자료와 블록 수가 모두 같았고 해시율 상대차는4.48×10⁻⁹ 이내였습니다. 임의 전일값 채우기는 하지 않았습니다.</p><p>일자d 자료를d+2일00UTC부터 사용했습니다. 이는 모든 과거 최초 공개 시각·빈티지의 완전한 증명이 아니며, 추가7일 정보 지연도 따로 검증했습니다. Coin Metrics 무료 자료는2026-05-24에서 멈췄으므로 최근 평가를5월까지로 줄이지 않았습니다. 별도 공급자 조건은 그날까지 Coin Metrics, 이후 원래 자료로 고정했습니다.</p></section><section><h2>큰 충격 뒤에는 정말 반전하는가?</h2><p>UTC00·02·…·22시에 완료된2시간 log수익이 이전360개2시간 수익의 표준편차3배 이상이면 큰 충격으로 정했습니다. 현재 충격은 표준편차 계산에서 제외했습니다. SH_REV는 반대 방향, SH_MOM은 같은 방향, SH_ALL은 모든 구간 반전, SH_SMALL은 큰 충격이 아닌 구간 반전입니다. 관측한 것은 가격 충격이며 강제청산 원시 자료가 아닙니다.</p><p>기본 체결은 판단5분 뒤 시가, 다음2시간 판단에서 목표를 교체합니다. 신호·위험이 불완전하면 공통 현금 전환으로 고정했습니다. 초기 명세의 판단보류가 노출을 너무 오래 유지할 수 있어 이 부분을 성과 계산 전에 명확히 했으며, 이전 명세도 보존했습니다. 주 구간361개 판단은 공통 결측 현금이었습니다.</p><p>선행 논문은 다른 주기에서 반전과 지속을 상반되게 보고했습니다. 저자 선택2시간·임계 표를 미사용 선택이라고 하지 않았고, 일중 시각을 전체 표본에서 고른 결과·비용 누락·거래수익 단순합도 구분했습니다.</p></section><section><h2>같은 비용·위험 원칙</h2><p>완료일20일 log변동성 목표20%, 명목1배 상한,5%p 재조정밴드. 현물 편도10bp·0.00001BTC·최소5USDT, 선물5bp·0.001BTC·최소50USDT(감소 예외), 양쪽충격1.5bp. 실제 펀딩·종료 비용 포함, 거래량0봉 체결금지. 채굴은 기본1h/추가1·24h, 충격은 기본5m/추가60·240m 체결 지연. 비용2배·위험10%도 모두 보존했습니다.</p><p>펀딩 참조는 원시 시간봉 mark 시가 근사이며, 실제 호가·부분체결·과거 주문규정은 완전히 복원하지 못했습니다. 단순 노출·위험 감소나 레버리지 수익을 새로운 알파라고 부르지 않았습니다.</p><details><summary>연도별 수익</summary>'''+table(['규칙','기간','2022','2023','2024','2025','2026'],annual,'annual-results')+'</details><details><summary>가격손익·비용·펀딩·위험</summary>'+table(['규칙','기간','가격손익USDT','비용USDT','펀딩USDT','평균노출%','연변동성%'],cost,'cost-results')+'</details><details><summary>롱·숏 순손익</summary>'+table(['규칙','기간','롱 USDT','숏 USDT'],sides,'side-results')+'</details><details><summary>대조군 대비 불확실성</summary><p>14일 블록2,000회95%구간(%/일).7/28일도JSON에 저장했습니다. 극단 사건·계열 상관·누적 연구 선택 편향은 남습니다.</p>'+table(['규칙','기간','대조군','일수익차95%구간'],ci,'uncertainty-results')+'</details></section><section><h2>조건별 손실도 보존</h2><details id="matrix"><summary>96개 모든 조건</summary>'+table(['규칙','기간','조건','수익%','DD%','연변동성%','보유구간','비용USDT'],[[r['strategy'],r['period'],r['scenario'],f"{r['return_pct']:+.2f}",f"{r['max_drawdown_pct']:.2f}",f"{r['realized_vol_pct']:.2f}",r['round_trips'],f"{r['fees']+r['impact']:.2f}"] for r in rows],'all-accounts')+'</details></section>'
 body+='<section id="proof"><h2>별도 계산과 오프라인 재현</h2><p>채굴9개·충격 신호6개 경계검사, 기존 원장7개 합성 검사를 통과했습니다. 원시 해시율·다른 EMA/분산 계산, 폐형식 수량·무거래, Decimal 비용·펀딩, 시간/5분 DD를 대조했습니다. 채굴 최대차2×10⁻¹¹, 충격6.40×10⁻¹¹ 이내. 채굴95파일·충격'+str(studies['SHOCK']['reproduction']['matched_files'])+'파일 소켓차단 바이트 일치.</p>'+table(['실험','판단','수량','무거래','이벤트','일말자산','일치파일'],proof,'proof-results')+'</section>'
 body+='''<section id="downloads"><h2>검증 자료</h2><div class="downloads"><a download href="downloads/btc-frontier-evidence.zip">96계좌·채굴원시·검산 ZIP ↓</a><a download href="downloads/btc-frontier-evidence.json">전체 수치·불확실성 JSON ↓</a><a download href="downloads/btc-frontier-summary.csv">96조건 CSV ↓</a></div><p>가격 원시 ZIP 전체·공통 의존성은 별도 저장소 재현 자료가 필요합니다. Coin Metrics 무료 BTC CSV는 <a href="https://github.com/coinmetrics/data">공식 저장소</a> 출처이며 <a href="https://creativecommons.org/licenses/by-nc/4.0/">CC BY-NC4.0</a>입니다. 연구용 자료 묶음입니다.</p><p><a href="EXPERIMENT_BTC_MINING_20261002.md">채굴 성과 전 명세</a> · <a href="EXPERIMENT_BTC_SHOCK_20261002.md">충격 성과 전 명세</a> · <a href="BTC_WEB_RESEARCH_20261002.md">검색·원문·실패 기록</a></p><p>연구 목표는 아직 미완료입니다. 이 정적 페이지는 작업 지속이나 실거래 상태를 보장하지 않습니다.</p></section><footer>BUILD1002f1 · BTC-only · 실거래 없음</footer></main></body></html>'''
 (DOC/'btc-frontier-research.html').write_text(body);p=DOC/'btc-web-research.html';old=p.read_text()
 if 'id="frontier-followup"' not in old:p.write_text(old.replace('<h1>','<p id="frontier-followup" class="boundary">추가96계좌: <a href="btc-frontier-research.html">채굴 상태·큰 가격 충격 검증 ↗</a></p><h1>',1))
 files=['btc-frontier-research.html','btc-web-research.html','downloads/btc-frontier-evidence.zip','downloads/btc-frontier-evidence.json','downloads/btc-frontier-summary.csv','EXPERIMENT_BTC_MINING_20261002.md','EXPERIMENT_BTC_SHOCK_20261002.md','BTC_WEB_RESEARCH_20261002.md','assets/btc-continuation.css','assets/icon.svg'];o=ROOT/'runs/btc-frontier-report-20261002';o.mkdir(exist_ok=True);(o/'public-manifest.json').write_bytes(canonical({n:{'sha256':sha((DOC/n).read_bytes()),'bytes':(DOC/n).stat().st_size} for n in files}));print(json.dumps({'accounts':len(rows),'files':len(files)}))
if __name__=='__main__':run()
