"""Publish only the independently verified MI72 experiment; no new calculations or old reruns."""
import csv,json,zipfile
from pathlib import Path
from build_btc_web_report import table,read
from btc_perp_bot.research.archive import canonical,sha
ROOT=Path(__file__).resolve().parents[1];DOC=ROOT/'docs';DOWN=DOC/'downloads';RUN=ROOT/'runs/btc-margin-20261004';INPUT=ROOT/'data/btc-margin-20261004';BUILD='1004m1'
def pct(x):return f'{x:+.2f}'
def number(x):return '자료 부족' if x is None else f'{x:.9g}'
def run():
 s=read(RUN/'summary.json');v=read(RUN/'verification.json');rep=read(RUN/'reproduction.json');sel=read(RUN/'selection.json');fc=read(RUN/'forecast-summary.json');unc=read(RUN/'uncertainty.json');diag=read(RUN/'diagnostics.json');act=read(RUN/'activity.json');source=read(INPUT/'independent-audit.json');assert len(s)==v['accounts']==72 and rep['all_bytes_equal'];names=('MI_INFO','MI_LONG','MI_SHORT','MI_PRICE','MI_INV','MI_TREND');base=[];annual=[];cost=[];forecast=[];ci=[];rows=[];stress=[];side=[];activity=[]
 for n in names:
  a,b=[s[p+'-'+n+'-base']['metrics'] for p in ('main','recent')];base.append([n+(' · 기본' if n=='MI_INFO' else ' · 대조'),pct(a['return_pct']),f"{a['max_drawdown_pct']:.2f}",pct(b['return_pct']),f"{b['max_drawdown_pct']:.2f}"])
  for p in ('main','recent'):
   e=s[p+'-'+n+'-base'];m=e['metrics'];annual.append([n,p,*[pct(e['annual'][y]['return_pct']) if y in e['annual'] else '해당 없음' for y in ('2022','2023','2024','2025','2026')]]);cost.append([n,p,pct(m['gross_pnl']),f"{m['fees']+m['impact']:.2f}",pct(m['funding']),f"{m['realized_vol_pct']:.2f}",number(m['sharpe'])]);ac=act[p][n+'-base'];activity.append([p,n,ac['override_weeks'],ac['override_days'],ac['fallback_days'],ac['invalid_feature_days'],ac['model_missing_days']])
   if n in fc[p]['0']['models']:
    f=fc[p]['0']['models'][n];forecast.append([p,n,f['n'],number(f['mse']),number(None if f['sign_accuracy'] is None else f['sign_accuracy']*100),f['negative_last_beta_weeks'],number(f['median_last_beta'])])
   for ctrl in ('MI_LONG','MI_TREND'):
    u=unc[p+'-'+n]['vs_'+ctrl][1]['ci95'];ci.append([p,n,ctrl,f'{u[0]:+.5f} ~ {u[1]:+.5f}'])
 for p in ('main','recent'):
  for direction,z in diag[p+'-MI_INFO-base.json.gz']['long_short'].items():side.append([p,direction,pct(z['gross']),f"{z['fees']+z['impact']:.2f}",pct(z['funding']),pct(z['net'])])
 for c in ('base','cost_x2','delay1','delay24','risk10','data_delay7'):stress.append([c,*[pct(s[p+'-MI_INFO-'+c]['metrics']['return_pct']) for p in ('main','recent')]])
 for key,e in s.items():
  p,n,c=key.split('-');m=e['metrics'];rows.append({'strategy':n,'period':p,'scenario':c,**{k:m[k] for k in ('return_pct','max_drawdown_pct','realized_vol_pct','sharpe','round_trips','fees','impact','funding','mean_exposure')}})
 evidence={'build':BUILD,'account_rows':rows,'summary':s,'verification':v,'reproduction':rep,'selection':sel,'forecast_summary':fc,'uncertainty':unc,'diagnostics':diag,'activity':act,'source_audit':source,'scope':'Public BTCUSD aggregate margin stocks are information only; all executions BTCUSDT perpetual. No investor identity or order-flow identification. One-day assumed publication buffer, current vintage and repeated development history; no strategy adopted or live trading service.'};(DOWN/'btc-margin-evidence.json').write_bytes(canonical(evidence))
 with (DOWN/'btc-margin-summary.csv').open('w',newline='') as f:w=csv.DictWriter(f,fieldnames=list(rows[0]));w.writeheader();w.writerows(rows)
 with zipfile.ZipFile(DOWN/'btc-margin-evidence.zip','w',compression=zipfile.ZIP_STORED) as z:
  files=[(p,'run/'+p.name) for p in sorted(RUN.iterdir()) if p.is_file()]
  for n in ('collect_btc_margin_data.py','audit_btc_margin_data.py','btc_margin_study.py','test_btc_margin_study.py','verify_btc_margin_study.py','reproduce_btc_margin_study.py','btc_target_ledger.py','btc_continuity_study.py','btc_persistence_study.py'):files.append((ROOT/'tools'/n,'source/'+n))
  for n in ('snapshots.json.gz','prepare-audit.json','independent-audit.json'):files.append((INPUT/n,'input/btc-margin-20261004/'+n))
  files += [(p,'input/btc-margin-20261004/'+str(p.relative_to(INPUT))) for folder in ('raw','failures') for p in sorted((INPUT/folder).glob('*')) if p.is_file()]
  files.append((DOC/'EXPERIMENT_BTC_MARGIN_20261004.md','source/EXPERIMENT_BTC_MARGIN_20261004.md'))
  for p,n in files:z.writestr(zipfile.ZipInfo(n,(2026,10,4,0,0,0)),p.read_bytes())
  z.writestr(zipfile.ZipInfo('DATA-SOURCES.txt',(2026,10,4,0,0,0)),'''72 BTCUSDT perpetual-only simulated accounts. Bitfinex BTCUSD margin long/short aggregate BTC stock observations are information only, not exchange trades, loans, identified retail positions, new order flow, or all fBTC currency funding. Public documented stats1/pos.size:1m:tBTCUSD:long|short/hist. Exactly 350 Sunday cutoffs x 2 sides, each preceding 60-minute window; exact last-minute selection, missing/invalid retained, no forward fill. Decision Monday00UTC has one day assumed publication buffer after selected minute ends; this does NOT prove original real-time availability or unrevised history. Extra7day scenario delays only margin information, not current settled funding/price controls.
All new raw public response bodies/metadata, normalized field strings, source receipts, plans/forecasts/accounts/checks are included. Paper PDFs not redistributed. Common prior market data, old 329-market/80-perp audit receipts and pressure raw-hour tuples, shared modules/repository layout and Python dependencies remain separately required; this is NOT a standalone environment. No personal records, keys, financial-account access, or live-order service.
Mechanism motivation, not replication: Strych2022 https://doi.org/10.1016/j.frl.2022.102689 (abstract only; full methods unavailable). Official aggregate endpoint definitions https://docs.bitfinex.com/reference/rest-public-stats .
''')
 main=s['main-MI_INFO-base']['metrics'];recent=s['recent-MI_INFO-base']['metrics'];status='기각' if not sel['passed'] else '개발 관문 통과 · 전진 검증 전';gates=[[k,'통과' if val else '미달'] for part in ('checks','information_increment') for k,val in sel[part].items()]
 html='''<!doctype html><html lang="ko"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta http-equiv="Content-Security-Policy" content="default-src 'self';script-src 'none';style-src 'self';img-src 'self' data:;connect-src 'none';object-src 'none';base-uri 'none';form-action 'none'"><title>BTC 마진 숏 잔고 추가정보 검증</title><link rel="icon" href="assets/icon.svg"><link rel="stylesheet" href="assets/btc-continuation.css"></head><body><a class="skip" href="#results">결과로 이동</a><header><a href="./">BTC RESEARCH</a><nav><a href="btc-web-research.html">전체 연구 기록</a><a href="#downloads">검증 자료</a></nav></header><main><p class="eyebrow">BTC PERPETUAL ONLY · BUILD1004m1</p><h1>마진 숏 잔고에<br>추가 방향정보가 있는가?</h1><p class="lead">BTC/USD 마진 숏 잔고의 주간 변화가 롱 잔고·이미 정산된 펀딩·가격 추세를 넘어 다음 주 방향을 알려주는지 검증했습니다. 주규칙과 모든 대조군·실패 조건을 함께 공개합니다.</p>'''
 html+=f'<div class="facts"><article><b>72</b><span>순수 BTC 선물 조건계좌</span></article><article><b>{status}</b><span>MI_INFO 기본 후보</span></article><article><b>{rep["matched_files"]}</b><span>소켓차단 바이트 일치</span></article></div><p class="boundary">2022–2025 및 2026.01–08은 반복해서 본 개발 이력입니다. 새 미사용 OOS나 미래 수익 보장이 아닙니다. 검산 통과와 전략 채택은 별개이며 실거래·상시 모의서비스는 시작하지 않았습니다.</p>'
 html+='<section id="results"><h2>기본과 모든 대조군</h2><p>각1,000USDT, 수익·낙폭은 %. 모든 체결은 BTCUSDT 무기한선물입니다. Bitfinex 마진 잔고는 정보로만 쓰며 현물 매매·차입은 없습니다.</p>'+table(['규칙','4년 수익','4년 DD','최근 수익','최근 DD'],base,'base-results')
 html+=f'<p>MI_INFO 주기간 {pct(main["return_pct"])}%·DD {main["max_drawdown_pct"]:.2f}%·Sharpe {number(main["sharpe"])}, 최근 {pct(recent["return_pct"])}%입니다. 주수익52.838713%·DD13.561952%, 최근수익4.628391% 등 사전기준을 유지했습니다. INV나 다른 대조군이 더 좋아도 주규칙으로 바꾸지 않습니다.</p><details><summary>사전 선정 관문 전체</summary>'+table(['고정 관문','결과'],gates,'selection-results')+'</details></section>'
 html+='''<section><h2>차입을 수반하는 숏 잔고는 별도 정보인가</h2><p>새 정보는 BTC/USD 현물마진의 롱·숏 총 BTC 잔고입니다. 각 주간 변화 L과 S를 이전 주 대비 로그비율로 계산합니다. 선물의 균형 잡힌 양방향 미결제약정이나 당일 체결량과 다릅니다. 다만 잔고 변화에는 신규 진입과 청산·헤지가 섞이며, 개인 신원·소매 비중·정보거래 확률을 알아낸 것은 아닙니다. 거래소의 자금·출금 마찰도 해석에 영향을 줄 수 있습니다.</p><p>INFO는 완료7/28일 가격수익·settled7일 펀딩·L·S, LONG은 S 제외, SHORT는 L 제외, PRICE는 두 마진변화 제외입니다. PRICE에도 기존 펀딩을 통제합니다. INFO의 S계수가 음수이고 예측이 비용·추정오차를 넘으며 LONG 대비 같은 방향의 추가정보를 줄 때만 발동합니다. LONG은 L계수 양수, SHORT는 S계수 음수를 요구합니다. INV는 INFO의 발동 사건만 반대로, TREND는 고정 추세 그대로입니다.</p><p>동일104달력주·최소52행의 완료된 과거 목표만 학습하며 무제약 회귀계수와 달력1주 HAC 오차를 보존했습니다. 조건 미달이면 사전에 고정한 양방향 추세를 유지하고 위험만 매일 갱신합니다. 부호·창·기각 기준을 사후에 바꾸지 않았습니다.</p></section>'''
 html+='<section><h2>추가 예측력과 실제 발동</h2>'+table(['기간','모형','공통주','MSE','방향정확도%','마지막 계수 음수주','마지막 계수 중앙'],forecast,'forecast-results')
 html+=f'<p>공통 예측 주기간 {fc["main"]["0"]["n"]}주/coverage {fc["main"]["0"]["coverage"]*100:.2f}%, 최근 {fc["recent"]["0"]["n"]}주/{fc["recent"]["0"]["coverage"]*100:.2f}%입니다. 마지막 계수는 INFO/SHORT의 S, LONG의 L, PRICE의 펀딩으로 서로 다른 경제량입니다. 예측오차와 실제 비용 후 계좌 관문을 별도로 판단합니다.</p>'+table(['기간','규칙','발동주','발동일','추세유지일','피처무효일','모형무효일'],activity,'activity-results')+'<p>피처무효와 모형무효 일수는 중복될 수 있어 합산한 탈락일이 아닙니다. 새 정보가 작동하지 않고 추세만 상속한 경우를 성공으로 처리하지 않습니다.</p></section>'
 html+=f'<section><h2>정확한 분 관측과 가용시계</h2><p>공식 공개집계 700개 작은 구간·{source["minute_rows"]:,}분행 중 유효 snapshot {source["valid_snapshots"]}, 무효 {source["invalid_snapshots"]}입니다. 원시 분 누락 {source["missing_minutes"]}, 비양수·무효 값 {source["invalid_minutes"]}를 숨기지 않았습니다. 2019.12.22–2026.08.30의 일요일 경계350개, 각 long/short의 직전60분만 수집했습니다. 4개 사전 시계표본은 재사용했습니다.</p><p>월요일00UTC 판단에 일요일00 직전 마지막 분과 그 이전 주 같은 분을 비교합니다. 선택 분이 끝난 뒤24시간 게시 여유를 두었지만 최초 게시·과거 수정 부재를 증명한 것은 아닙니다. 정확한 분이 없으면 과거 값으로 채우지 않습니다. 추가7일 조건은 마진 자료만 늦추고 가격·실제ms 기준 이미 정산된21개 펀딩은 현재 시계를 유지합니다.</p><p>공식15회/분 제한에 맞춰4.5초 간격으로 수집했습니다. 현재 조회본·source SHA·독립 검사 일치는 당시 실시간 체결 가능성을 대신하지 않습니다. 다른 BTC-quote 시장까지 포함할 수 있는 광역 fBTC 대차 총량을 BTCUSD 숏 잔고로 대체하지 않았습니다.</p></section>'
 html+='<section><h2>비용·펀딩·실행 지연</h2><p>선물 편도5bp수수료+1.5bp 불리한 impact, 실제 펀딩×시간 mark시가 대용. 기본1h 후집행·추가1h/24h지연, 수량0.001BTC·최소50USDT·감축예외, 총목표명목≤1배. 호가·부분체결·역사규정·정확청산·운영비·세금은 미복원입니다. Bitfinex에서 차입하지 않아 그 시장 차입이자를 이 계좌에 잘못 부과하지 않습니다.</p>'+table(['주규칙 조건','4년 수익%','최근 수익%'],stress,'stress-results')+'<details><summary>연도별 수익</summary>'+table(['규칙','기간','2022','2023','2024','2025','2026.01–08'],annual,'annual-results')+'</details><details><summary>가격손익·비용·펀딩</summary><p>금액USDT. 선물 롱에도 펀딩을 적용했습니다.</p>'+table(['규칙','기간','가격손익','비용','펀딩','연변동성%','Sharpe'],cost,'cost-results')+'</details><details><summary>주규칙 롱·숏 기여</summary><p>금액USDT, 독립 원장 기준.</p>'+table(['기간','방향','가격손익','비용','펀딩','순손익'],side,'direction-results')+'</details><details><summary>수익차의 불확실성</summary><p>14일 원형블록2,000회95%구간(%/일), 전체7/14/28일 결과는 다운로드에 보존했습니다. 반복탐색 편향을 해소한 OOS는 아닙니다.</p>'+table(['기간','규칙','대조','일수익차95%구간'],ci,'uncertainty-results')+'</details></section>'
 html+='<section><h2>모든72조건 보존</h2><details id="matrix"><summary>72계좌 전체 보기</summary>'+table(['규칙','기간','조건','수익%','DD%','연변동성%','보유구간','펀딩USDT'],[[r['strategy'],r['period'],r['scenario'],pct(r['return_pct']),f"{r['max_drawdown_pct']:.2f}",f"{r['realized_vol_pct']:.2f}",r['round_trips'],pct(r['funding'])] for r in rows],'all-accounts')+'</details></section>'
 html+=f'<section id="proof"><h2>독립 검산과 차단 재현</h2><p>사전명세d08d271→24합성검사 구현7ac027b→자료동결5808fbf 뒤 최초 성과계산 순서입니다. 새700응답 별도Decimal 감사, {v["raw_feature_weeks"]:,}피처주·{v["independent_model_fits"]:,}정규방정식/HAC·{v["raw_daily_decisions"]:,}일판단·{v["independent_target_quantities"]:,}폐형식수량·{v["raw_mark_funding_events"]:,}펀딩·{v["daily_equities"]:,}일말자산·선정·{v["return_block_bootstrap_checks"]}구간을 검산했습니다. 계좌최대차 {v["max_numeric_error"]:.3g}USDT. 새 {rep["matched_files"]}파일은 소켓차단에서 바이트 일치했습니다.</p><p>기존329시장ZIP 및80개월 선물 원자료는 고정SHA 영수증을 재사용했으며 무변경 전체 감사·옛 계좌 재실행은 하지 않았습니다. 원시 공개집계가 일치해도 투자자 유형·최초 게시 빈티지·실거래 유효성이 확인되는 것은 아닙니다.</p></section>'
 html+='''<section id="downloads"><h2>검증 자료</h2><div class="downloads"><a download href="downloads/btc-margin-evidence.zip">72계좌·원자료·검산 ZIP ↓</a><a download href="downloads/btc-margin-evidence.json">전체 수치·불확실성 JSON ↓</a><a download href="downloads/btc-margin-summary.csv">72조건 CSV ↓</a><a download href="EXPERIMENT_BTC_MARGIN_20261004.md">성과 전 명세 ↓</a></div><p><a href="BTC_WEB_RESEARCH_20261002.md">원문 감사·실패 기록</a> · <a href="https://doi.org/10.1016/j.frl.2022.102689">경제 질문의 동기 논문</a> · <a href="https://docs.bitfinex.com/reference/rest-public-stats">공식 공개집계 정의</a></p><p>ZIP은 새 원시 응답·피처·모형·72계좌·검산·재현해시를 포함합니다. 공통시장·과거영수증·공유모듈·의존성은 별도로 필요해 독립 실행환경은 아닙니다. 논문PDF는 재배포하지 않습니다.</p><p>누적 외부2,094조건계좌이며 독립전략2,094개가 아닙니다. 기존198계좌/273파일을 보존했고 채택0입니다. 공개자료와 오프라인 가상검증만 수행했습니다.</p></section><footer>BUILD1004m1 · BTC-only · 실거래 없음</footer></main></body></html>'''
 (DOC/'btc-margin-research.html').write_text(html);p=DOC/'btc-web-research.html';old=p.read_text()
 if 'id="margin-followup"' not in old:p.write_text(old.replace('<h1>','<p id="margin-followup" class="boundary">새72순수선물계좌·외부2,094조건: <a href="btc-margin-research.html">마진 숏 잔고의 추가정보 검증 ↗</a></p><h1>',1))
 files=['btc-margin-research.html','btc-web-research.html','downloads/btc-margin-evidence.zip','downloads/btc-margin-evidence.json','downloads/btc-margin-summary.csv','EXPERIMENT_BTC_MARGIN_20261004.md','BTC_WEB_RESEARCH_20261002.md'];o=ROOT/'runs/btc-margin-report-20261004';o.mkdir(exist_ok=True);(o/'public-manifest.json').write_bytes(canonical({n:{'sha256':sha((DOC/n).read_bytes()),'bytes':(DOC/n).stat().st_size} for n in files}));print({'accounts':len(rows),'public_files':len(files),'zip_bytes':(DOWN/'btc-margin-evidence.zip').stat().st_size,'selected':sel['passed']})
if __name__=='__main__':run()
