"""Publish only new, independently verified TS72 outputs; no research reruns."""
import csv,json,zipfile
from pathlib import Path
from build_btc_web_report import table,read
from btc_perp_bot.research.archive import canonical,sha
ROOT=Path(__file__).resolve().parents[1];DOC=ROOT/'docs';DOWN=DOC/'downloads';RUN=ROOT/'runs/btc-term-20261004';BUILD='1004f1'
def pct(x):return f'{x:+.2f}'
def run():
 s=read(RUN/'summary.json');v=read(RUN/'verification.json');rep=read(RUN/'reproduction.json');sel=read(RUN/'selection.json');fc=read(RUN/'forecast-summary.json');unc=read(RUN/'uncertainty.json');diag=read(RUN/'diagnostics.json');act=read(RUN/'activity.json');assert len(s)==v['accounts']==72 and rep['all_bytes_equal'];names=('TS_INFO','TS_FUND','TS_TERM','TS_PRICE','TS_INV','TS_TREND');base=[];annual=[];cost=[];forecast=[];ci=[];rows=[];stress=[];side=[]
 for n in names:
  a,b=[s[p+'-'+n+'-base']['metrics'] for p in ('main','recent')];base.append([n+(' · 기본' if n=='TS_INFO' else ' · 대조'),pct(a['return_pct']),f"{a['max_drawdown_pct']:.2f}",pct(b['return_pct']),f"{b['max_drawdown_pct']:.2f}"])
  for p in ('main','recent'):
   e=s[p+'-'+n+'-base'];m=e['metrics'];annual.append([n,p,*[pct(e['annual'][y]['return_pct']) if y in e['annual'] else '해당 없음' for y in ('2022','2023','2024','2025','2026')]]);cost.append([n,p,pct(m['gross_pnl']),f"{m['fees']+m['impact']:.2f}",pct(m['funding']),f"{m['realized_vol_pct']:.2f}",f"{m['sharpe']:.3f}"])
   if n in fc[p]['0']['models']:
    f=fc[p]['0']['models'][n];forecast.append([p,n,f['n'],f"{f['mse']:.9g}",f"{f['sign_accuracy']*100:.2f}",f['negative_last_beta_weeks'],f"{f['median_last_beta']:.6f}"])
   for ctrl in ('TS_FUND','TS_TREND'):
    u=unc[p+'-'+n]['vs_'+ctrl][1]['ci95'];ci.append([p,n,ctrl,f'{u[0]:+.5f} ~ {u[1]:+.5f}'])
 for p in ('main','recent'):
  for direction,z in diag[p+'-TS_INFO-base.json.gz']['long_short'].items():side.append([p,direction,pct(z['gross']),f"{z['fees']+z['impact']:.2f}",pct(z['funding']),pct(z['net'])])
 for scenario in ('base','cost_x2','delay1','delay24','risk10','data_delay7'):stress.append([scenario,*[pct(s[p+'-TS_INFO-'+scenario]['metrics']['return_pct']) for p in ('main','recent')]])
 for key,e in s.items():
  p,n,c=key.split('-');m=e['metrics'];rows.append({'strategy':n,'period':p,'scenario':c,**{k:m[k] for k in ('return_pct','max_drawdown_pct','realized_vol_pct','sharpe','round_trips','fees','impact','funding','mean_exposure')}})
 evidence={'build':BUILD,'account_rows':rows,'summary':s,'verification':v,'reproduction':rep,'selection':sel,'forecast_summary':fc,'uncertainty':unc,'diagnostics':diag,'activity':act,'scope':'BTC dated USD quote information only; all trades BTCUSDT perpetual, no coin-margined futures or spot trades. Current archive/date-proxy maturity, repeated development history, no accepted strategy or running trading service.'};(DOWN/'btc-term-evidence.json').write_bytes(canonical(evidence))
 with (DOWN/'btc-term-summary.csv').open('w',newline='') as f:w=csv.DictWriter(f,fieldnames=list(rows[0]));w.writeheader();w.writerows(rows)
 with zipfile.ZipFile(DOWN/'btc-term-evidence.zip','w',compression=zipfile.ZIP_STORED) as z:
  files=[(p,'run/'+p.name) for p in sorted(RUN.iterdir()) if p.is_file()]
  for n in ('collect_btc_term_data.py','audit_btc_term_data.py','btc_term_study.py','test_btc_term_study.py','verify_btc_term_study.py','reproduce_btc_term_study.py','btc_target_ledger.py','btc_continuity_study.py','btc_persistence_study.py'):files.append((ROOT/'tools'/n,'source/'+n))
  for n in ('contracts.json.gz','prepare-audit.json','independent-audit.json'):files.append((ROOT/'data/btc-term-20261004'/n,'input/btc-term-20261004/'+n))
  files.append((DOC/'EXPERIMENT_BTC_TERM_STRUCTURE_20261004.md','source/EXPERIMENT_BTC_TERM_STRUCTURE_20261004.md'))
  for p,n in files:z.writestr(zipfile.ZipInfo(n,(2026,10,4,0,0,0)),p.read_bytes())
  z.writestr(zipfile.ZipInfo('DATA-SOURCES.txt',(2026,10,4,0,0,0)),'''72 BTCUSDT perpetual-only simulated accounts, no spot or dated-futures executions. All 26 dated BTCUSD contract raw hourly field strings (including 433 invalid hours), their 173 official ZIP URLs/checksums and independent receipts are included. No invented USD/USDT conversion or exact settlement time: YYMMDD UTC00 is a nominal expiry date proxy, not exchange deliveryTime. Current archive listings and checksums do not prove original publication vintage or historic completeness. Old 329-market and 80-perp raw audits reused by pinned receipts, not wholly rerun. The common market, prior receipts, original archives, pressure raw-hour tuple input, shared modules/repository layout and Python dependencies remain separately required; this ZIP is NOT a standalone environment. No paper PDFs, personal data, credentials, account access or live-order programs.
Mechanism reference: BIS Working Paper1087 Crypto Carry https://www.bis.org/publ/work1087.htm . Same-currency near/far quote conditional hypothesis is our own, not replication of its paid Skew constant-maturity spot basis. Current official source https://data.binance.vision/ .
''')
 main=s['main-TS_INFO-base']['metrics'];recent=s['recent-TS_INFO-base']['metrics'];status='기각' if not sel['passed'] else '개발 관문 통과 · 전진 검증 전'
 html='''<!doctype html><html lang="ko"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta http-equiv="Content-Security-Policy" content="default-src 'self';script-src 'none';style-src 'self';img-src 'self' data:;connect-src 'none';object-src 'none';base-uri 'none';form-action 'none'"><title>BTC 선물 만기곡선 추가정보 검증</title><link rel="icon" href="assets/icon.svg"><link rel="stylesheet" href="assets/btc-continuation.css"></head><body><a class="skip" href="#results">결과로 이동</a><header><a href="./">BTC RESEARCH</a><nav><a href="btc-web-research.html">전체 연구 기록</a><a href="#downloads">검증 자료</a></nav></header><main><p class="eyebrow">BTC PERPETUAL ONLY · BUILD1004f1</p><h1>만기간 가격 차이도<br>비용 후 전략 기준을 넘지 못했습니다.</h1><p class="lead">먼 만기와 가까운 만기의 BTC 가격 차이가 기존 펀딩·가격·만기 달력에 없는 다음 주 정보를 주는지 검증했습니다. 4년 주기간 순손실과 양기간 예측오차 악화로 기각했습니다.</p>'''
 html+=f'<div class="facts"><article><b>72</b><span>순수 BTC 선물 조건계좌</span></article><article><b>{status}</b><span>TS_INFO 기본 후보</span></article><article><b>{rep["matched_files"]}</b><span>소켓차단 바이트 일치</span></article></div><p class="boundary">2022–2025 및 2026.01–08은 반복해서 본 개발 이력입니다. 새 미사용 OOS나 미래 수익 보장이 아닙니다. 검산 통과와 전략 채택은 별개이며 실거래·상시 모의서비스는 시작하지 않았습니다.</p>'
 html+='<section id="results"><h2>기본과 모든 대조군</h2><p>각 1,000USDT. 수익과 최대낙폭(DD)은 %. 모든 체결은 BTCUSDT 무기한선물이며 만기선물은 정보로만 사용했습니다.</p>'+table(['규칙','4년 수익','4년 DD','최근 수익','최근 DD'],base,'base-results')
 html+=f'<p>주규칙 {pct(main["return_pct"])}%·DD {main["max_drawdown_pct"]:.2f}%·Sharpe {main["sharpe"]:.3f}, 최근 {pct(recent["return_pct"])}%입니다. 주수익 52.838713%·DD 13.561952%, 최근수익 4.628391% 등 사전기준을 유지했습니다. 역방향 INV의 수익이 더 높아도 사후에 주규칙으로 바꾸지 않았습니다.</p></section>'
 html+='''<section><h2>같은 USD 만기간 비율, 새로운 조건부 질문</h2><p>K = ln(먼 만기 가격 / 가까운 만기 가격) ÷ 두 명목만기의 연 단위 간격입니다. 같은 USD 가격끼리 비교하며 BTCUSD와 BTCUSDT 현물 가격을 변환 없이 섞지 않습니다. K가 클수록 차익거래 제약 아래 레버리지 수요가 과도할 수 있다는 음의 방향정보 가설입니다. 관측 가격 차이가 실제 수요나 무위험 수익을 직접 측정하는 것은 아닙니다.</p><p>INFO는 완료된 7/28일 BTCUSDT 수익, 가까운 만기까지의 날짜, 이미 정산된 7일 펀딩, K를 사용합니다. FUND는 K를 제외, TERM은 펀딩을 제외, PRICE는 가격·만기 달력만 사용합니다. INV는 INFO가 발동할 때만 반대 방향, TREND는 기존 추세 대조입니다. 네 모형은 동일한 과거 104달력주·최소52행, 미래 목표가 끝난 자료만 학습합니다.</p><p>INFO는 K계수 음수, 예측수익이 비용과 추정오차를 초과하고 FUND보다 같은 방향의 추가정보를 줄 때만 발동합니다. 실패하면 미리 정한 양방향 추세를 유지합니다. 계수를 원하는 부호로 잘라내거나 더 좋은 대조군을 선택하지 않습니다.</p></section>'''
 html+='<section><h2>예측력과 실제 발동</h2>'+table(['기간','모형','공통주','MSE','방향정확도%','마지막 계수 음수주','마지막 계수 중앙'],forecast,'forecast-results')
 html+=f'<p>공통 예측은 주 {fc["main"]["0"]["n"]}주, 최근 {fc["recent"]["0"]["n"]}주로 두 기간 모두 100%입니다. INFO의 MSE는 FUND와 PRICE보다 두 기간 모두 나쁩니다. 음의 K계수 중앙값만으로 충분한 추가정보라고 판단하지 않습니다. 표의 마지막 계수는 INFO/TERM의 K, FUND의 펀딩, PRICE의 만기 날짜이므로 서로 같은 경제량이 아닙니다.</p><p>INFO 신규 발동은 주 {act["main"]["TS_INFO-base"]["override_weeks"]}주/{act["main"]["TS_INFO-base"]["override_days"]}일, 최근 {act["recent"]["TS_INFO-base"]["override_weeks"]}주/{act["recent"]["TS_INFO-base"]["override_days"]}일입니다. 최근 최소5주 관문도 미달했습니다. 두 기간 평가의 피처·모형 결측은0이고, 모든 반대부호 계수와 fallback을 보존했습니다.</p></section>'
 html+='''<section><h2>공식 자료라도 유효시세와 가용시계를 따로 확인했습니다</h2><p>BTC 만기계약 26개·173개 공식 ZIP, 108,842시간 중 433시간은 무효로 보존했습니다. 만기 후 거래량0인 봉도 아카이브에 존재하므로 파일 존재를 거래 가능 시세로 간주하지 않습니다. 판단 전에 상장·거래가 관측된 가장 가까운 두 계약을 먼저 선택하고, 둘 중 한 시간봉이 무효면 더 먼 계약으로 바꾸지 않습니다.</p><p>매주 월요일00UTC, 정확 직전1시간의 완료 종가만 사용합니다. 만기는 계약명 YYMMDD의 UTC00 날짜 대용값이며 실제 거래소 정산시각을 확인했다는 뜻이 아닙니다. 모든 만기 날짜는 금요일임을 검사했습니다. 펀딩은 저장 버킷 시간이 아닌 실제 ms 정산시각이 cutoff보다 이른21개만 사용합니다. 7일 자료지연에서는 만기곡선·펀딩만 늦추고 현재 가격 통제는 유지합니다.</p><p>현재 아카이브의 목록·checksum은 최초 발표 빈티지나 과거 상장목록의 완전성을 입증하지 않습니다. 이 한계를 성과와 별도로 남겼습니다.</p></section>'''
 html+='<section><h2>비용·펀딩·실행 지연</h2><p>양방향 선물5bp수수료+편도1.5bp 불리한 impact, 실제펀딩×시간 mark 시가 대용. 기본1h 뒤 집행, 추가1h/24h 지연, 수량0.001BTC·최소50USDT·감축예외, 목표명목≤1배. 실제호가·부분체결·역사 규정·정확청산·세금·운영비는 미복원입니다.</p>'+table(['주규칙 조건','4년 수익%','최근 수익%'],stress,'stress-results')+'<details><summary>연도별 수익</summary>'+table(['규칙','기간','2022','2023','2024','2025','2026.01–08'],annual,'annual-results')+'</details><details><summary>가격손익·비용·펀딩</summary><p>금액USDT. 현물 계좌와 달리 선물 롱에도 펀딩을 적용했습니다.</p>'+table(['규칙','기간','가격손익','비용','펀딩','연변동성%','Sharpe'],cost,'cost-results')+'</details><details><summary>기본의 롱·숏 기여</summary><p>금액USDT. 독립 원장 기준입니다.</p>'+table(['기간','방향','가격손익','비용','펀딩','순손익'],side,'direction-results')+'</details><details><summary>수익차의 불확실성</summary><p>14일 원형블록2,000회95%구간(%/일). 전체7/14/28일 구간을 보존했으며 반복탐색 편향을 해소한 새 OOS는 아닙니다.</p>'+table(['기간','규칙','대조','일수익차95%구간'],ci,'uncertainty-results')+'</details></section>'
 html+='<section><h2>모든 실패·조건 보존</h2><details id="matrix"><summary>72계좌 전체 보기</summary>'+table(['규칙','기간','조건','수익%','DD%','연변동성%','보유구간','펀딩USDT'],[[r['strategy'],r['period'],r['scenario'],pct(r['return_pct']),f"{r['max_drawdown_pct']:.2f}",f"{r['realized_vol_pct']:.2f}",r['round_trips'],pct(r['funding'])] for r in rows],'all-accounts')+'</details></section>'
 html+=f'<section id="proof"><h2>독립 검산과 재현</h2><p>명세 aa65557→입력·20합성검사 구현 c033ad6 후 최초 성과를 계산했습니다. 신규173개ZIP의별도 Decimal 입력감사, {v["raw_feature_weeks"]:,}주간피처·{v["independent_model_fits"]:,}정규방정식/HAC·{v["raw_daily_decisions"]:,}일판단·{v["independent_target_quantities"]:,}폐형식수량·{v["raw_mark_funding_events"]:,}펀딩·{v["daily_equities"]:,}일말자산·선정·{v["return_block_bootstrap_checks"]}구간을 검산했습니다. 계좌최대차 {v["max_numeric_error"]:.3g}USDT. 새 {rep["matched_files"]}파일은 소켓차단에서 바이트 일치했습니다.</p><p>기존329시장ZIP 및80개월 선물 원자료는 고정 SHA 검산영수증을 재사용했고 무변경 전체 재감사하지 않았습니다. 수집의 상대경로 오류와 검산의 이전 구현파일명 참조 오류는 수정 전 로그를 보존했습니다. 전략·원자료·성과·선정기준 변경은 없습니다.</p></section>'
 html+='''<section id="downloads"><h2>검증 자료</h2><div class="downloads"><a download href="downloads/btc-term-evidence.zip">72계좌·피처·검산 ZIP ↓</a><a download href="downloads/btc-term-evidence.json">전체 수치·불확실성 JSON ↓</a><a download href="downloads/btc-term-summary.csv">72조건 CSV ↓</a><a download href="EXPERIMENT_BTC_TERM_STRUCTURE_20261004.md">성과 전 명세 ↓</a></div><p><a href="BTC_WEB_RESEARCH_20261002.md">원문 감사·실패 기록</a> · <a href="https://www.bis.org/publ/work1087.htm">Crypto Carry 원문</a> · <a href="https://data.binance.vision/">공식 시장자료</a></p><p>ZIP은 새 만기 원시행·모든피처/모형/72계좌·검산·재현해시를 포함합니다. 공통시장·과거영수증·원래ZIP·공유모듈·의존성은 별도로 필요하여 독립 실행환경은 아닙니다. 논문 PDF는 재배포하지 않습니다.</p><p>누적 외부1,950조건계좌이며 독립전략1,950개라는 뜻이 아닙니다. 기존198계좌/273파일을 보존했고 채택0입니다. 공개자료와 오프라인 가상검증만 수행했습니다.</p></section><footer>BUILD1004f1 · BTC-only · 실거래 없음</footer></main></body></html>'''
 (DOC/'btc-term-research.html').write_text(html);p=DOC/'btc-web-research.html';old=p.read_text()
 if 'id="term-followup"' not in old:p.write_text(old.replace('<h1>','<p id="term-followup" class="boundary">새72순수선물계좌·외부1,950조건: <a href="btc-term-research.html">만기간 가격 차이의 비용 후 검증 ↗</a></p><h1>',1))
 files=['btc-term-research.html','btc-web-research.html','downloads/btc-term-evidence.zip','downloads/btc-term-evidence.json','downloads/btc-term-summary.csv','EXPERIMENT_BTC_TERM_STRUCTURE_20261004.md','BTC_WEB_RESEARCH_20261002.md'];o=ROOT/'runs/btc-term-report-20261004';o.mkdir(exist_ok=True);(o/'public-manifest.json').write_bytes(canonical({n:{'sha256':sha((DOC/n).read_bytes()),'bytes':(DOC/n).stat().st_size} for n in files}));print({'accounts':len(rows),'public_files':len(files),'zip_bytes':(DOWN/'btc-term-evidence.zip').stat().st_size,'selected':sel['passed']})
if __name__=='__main__':run()
