"""Publish every audited COT/option account; no winner promotion."""
import csv,json,zipfile
from pathlib import Path
from build_btc_web_report import read,table
from btc_perp_bot.research.archive import canonical,sha
ROOT=Path(__file__).resolve().parents[1];DOC=ROOT/'docs';D=DOC/'downloads';DATA=ROOT/'data/btc-cot-20261002'
def run():
 studies={};rows=[];base=[];years=[];cost=[];ci=[];sides=[];proof=[];fore=[]
 for tag,folder,count,replay_count in [('COT','btc-cot-20261002',40,63),('OPTIONS','btc-options-20261002',56,98)]:
  R=ROOT/'runs'/folder;s=read(R/'summary.json');v=read(R/'verification.json');replay=read(R/'reproduction.json');sel=read(R/'selection.json');unc=read(R/'uncertainty.json');diag=read(R/'diagnostics.json');assert replay['all_bytes_equal'] and replay['matched_files']==replay_count and v['accounts']==count and not sel['passed'];studies[tag]={'summary':s,'verification':v,'reproduction':replay,'selection':sel,'uncertainty':unc,'diagnostics':diag,'information_age':read(R/'information-age.json')}
  proof.append([tag,v['raw_daily_decisions'],v['independent_target_quantities'],v['no_trade_decisions'],v['events'],v['daily_equities'],replay_count])
  if tag=='OPTIONS':
   f=read(R/'forecast-summary.json');studies[tag]['forecast']=f
   for p,z in f.items():
    for n,e in z['base'].items():fore.append([p,n,e['n'],f"{e['mse']:.7f}",f"{e['sign_accuracy']*100:.2f}",f"{e['cash_gate_fraction']*100:.2f}",str(e['training_n_min_max'])])
  for key,x in s.items():
   p,n,c=key.split('-');m=x['metrics'];rows.append({'experiment':tag,'strategy':n,'period':p,'scenario':c,**{k:m[k] for k in ('return_pct','max_drawdown_pct','realized_vol_pct','sharpe','round_trips','fees','impact','funding','mean_exposure','max_exposure')}})
   if c!='base':continue
   years.append([n,p,*[f"{x['annual'][y]['return_pct']:+.2f}" if y in x['annual'] else '해당 없음' for y in ('2022','2023','2024','2025','2026')]])
   cost.append([n,p,f"{m['gross_pnl']:+.2f}",f"{m['fees']+m['impact']:.2f}",f"{m['funding']:+.2f}",f"{m['mean_exposure']*100:.2f}",f"{m['realized_vol_pct']:.2f}"])
   for ctrl in ('E_SPOT','COT_PRICE','COT_NET') if tag=='COT' else ('E_SPOT','OP_FUT','OP_PRICE'):
    q=unc[p+'-'+n]['vs_'+ctrl][1]['ci95'];ci.append([n,p,ctrl,f'{q[0]:+.5f} ~ {q[1]:+.5f}'])
   z=diag[key+'.json.gz']['sides'];sides.append([n,p,f"{z['BS']['net']:+.2f}",f"{z['BP']['net']:+.2f}"])
   if p=='main':
    b=s['recent-'+n+'-base']['metrics'];base.append([n+(' · 기본' if n in ('COT_SHORT','OP_INC') else ' · 대조'),f"{m['return_pct']:+.2f}",f"{m['max_drawdown_pct']:.2f}",f"{b['return_pct']:+.2f}",f"{b['max_drawdown_pct']:.2f}",f"{m['round_trips']} / {b['round_trips']}"])
 evidence={'build':'1002p1','account_rows':rows,'studies':studies,'clock_audit':read(DATA/'clock-audit.json'),'options_units_audit':read(DATA/'combined-rounding-audit.json'),'scope':'BTC-only development; incomplete original COT vintages; delta-equivalent option holdings, not new option trades or causal impact; no live execution'};(D/'btc-position-evidence.json').write_bytes(canonical(evidence))
 with (D/'btc-position-summary.csv').open('w',newline='') as f:w=csv.DictWriter(f,fieldnames=list(rows[0]));w.writeheader();w.writerows(rows)
 with zipfile.ZipFile(D/'btc-position-evidence.zip','w',compression=zipfile.ZIP_STORED) as z:
  files=[]
  for tag,folder in [('cot','btc-cot-20261002'),('options','btc-options-20261002')]:files += [(p,tag+'/'+p.name) for p in sorted((ROOT/'runs'/folder).iterdir()) if p.is_file()]
  files += [(p,'position-data/'+p.name) for p in sorted(DATA.iterdir()) if p.is_file()]
  for name in ('prepare_btc_cot_data.py','btc_cot_study.py','verify_btc_cot_study.py','test_btc_cot_study.py','reproduce_btc_cot_study.py','btc_options_study.py','verify_btc_options_study.py','test_btc_options_study.py','reproduce_btc_options_study.py','btc_target_ledger.py','btc_persistence_study.py','btc_session_study.py'):files.append((ROOT/'tools'/name,'source/'+name))
  for p,name in files:z.writestr(zipfile.ZipInfo(name,(2026,10,2,0,0,0)),p.read_bytes())
 body='''<!doctype html><html lang="ko"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta http-equiv="Content-Security-Policy" content="default-src 'self';script-src 'none';style-src 'self';img-src 'self' data:;connect-src 'none';object-src 'none';base-uri 'none';form-action 'none'"><title>BTC 포지션 정보 검증 · 선물 주체와 옵션 추가정보</title><link rel="icon" href="assets/icon.svg"><link rel="stylesheet" href="assets/btc-continuation.css"></head><body><a class="skip" href="#results">결과로 이동</a><header><a href="./">BTC RESEARCH</a><nav><a href="btc-web-research.html">세션·체결압력</a><a href="btc-macro-research.html">거시정보</a><a href="#downloads">다운로드</a></nav></header><main><p class="eyebrow">BTC-ONLY · BUILD1002p1</p><h1>포지션을 따라가도,<br>최근 수익은 남지 않았습니다.</h1><p class="lead">기관 주체별 선물 숏 변화와 가격·선물 포지션을 통제한 옵션 추가정보를 따로 검증했습니다. 두 기본 후보 모두 사전 기준에 미달했습니다.</p><div class="facts"><article><b>96</b><span>새 가상계좌 · 전부 보존</span></article><article><b>기각</b><span>COT_SHORT · OP_INC</span></article><article><b>352주</b><span>동일 BTC 계약 자료</span></article></div><p class="boundary">2022–2025와 2026.01–08은 이미 본 개발 자료입니다. 미사용 OOS·실전 수익·최적 전략이 아닙니다. 반대 방향의 한 구간 수익이나 옵션 반올림 위상 중 좋은 것만 골라 채택하지 않았습니다.</p><section id="results"><h2>기본과 대조군을 함께 봅니다</h2><p>각1,000USDT, 수익·최대낙폭(DD)은 %. COT_SHORT는 leveraged-money 숏 감소→롱·증가→숏, COT_NET은 순잔고 변화, COT_PRICE는 이전 보고주 가격, COT_INV는 반대 방향입니다. OP_INC는 자산운용사 옵션 순노출의 추가정보, OP_FUT는 가격+선물 잔고, OP_PRICE는 가격만, OP_INV는 기본 허용 신호의 정확한 반대입니다.</p>'''
 body+=table(['규칙','4년 수익','4년 DD','최근 수익','최근 DD','주/최근 보유구간'],base,'base-results')
 body+='''<p>옵션 기본은 주+32.34%에도 DD23.62%가 상한13.56%를 넘었고, 최근−13.82%·DD19.08%였습니다. 선물-only 대조보다 양기간 순수익이 높거나 예측오차가 작다는 추가정보 기준도 충족하지 못했습니다. COT_INV 주+61.10%, OP_INV 최근+15.81%만 골라 새 전략으로 승격하지 않습니다.</p></section><section id="availability"><h2>화요일 잔고를 화요일에 안다고 하지 않습니다</h2><p>CFTC의 CME5BTC 계약(code133741)만 사용했습니다. Micro/Nano·다른 코인을 섞지 않았습니다. 기본 정보는 보고일+10일00UTC부터, 공식 특수 공개일+2일이 더 늦으면 그때부터 사용합니다. 보고일+21일이 지나면 현금으로 전환하고, 최신 보고가 무효라고 오래된 좋은 예측을 찾아 쓰지 않습니다.</p><p>2023 ION 중단과2025 정부 셧다운 등21개 예외 시각을 반영했습니다. 2023 공지는 실제 발행 서술,2025 표는 개정된 예정 공개표입니다. 모든 역사적 최초 수신 시각·최초 빈티지를 확보한 것은 아니므로 완전한 point-in-time 자료라고 주장하지 않습니다. 현재 API 기록의 사후 정정 가능성도 남습니다.</p><h3>옵션 계약 수가 아닌 델타 환산값</h3><p>Combined−FuturesOnly의 자산운용사 순(롱−숏)으로 옵션 환산 순노출을 구했습니다. 이는 신규 매매량·감마 노출이 아니며 가격만 변해도 델타가 바뀔 수 있습니다. 개별 정수 범주 합과 OI의 ±2 차이는18방향 관측에 있었지만, 총 reportable+nonreportable은704양면 전부 정확히 맞았습니다. 원인을 반올림이라고 확정하거나 행을 지우지 않았습니다.</p><p>옵션 순노출에 교대로±1계약을 더하는 두 위상을 모두 다시 학습·검증했습니다. 가능한 모든 오차의 최악 경계는 아니며, 성공한 위상으로 기본을 교체하지 않았습니다.</p></section><section><h2>공개 이후에 남는 예측만 검증</h2><p>옵션 모형은 이전104보고 중 가용시각 이후7일 수익이 이미 완료된 최소78쌍만 학습합니다. 원논문의 정확한 ‘둘째 주’ 복제가 아닌 보수적 공개지연 후 자체 검정입니다. 평균 예측의 표준오차에 롱23bp·숏13bp 왕복 비용을 더한 문턱을 넘을 때만 거래합니다. 표준오차는 전체 미래수익의 예측구간이 아닙니다.</p><details><summary>공통 보고행의 예측 진단</summary>'''
 body+=table(['기간','모형','예측수','MSE','부호일치%','현금문턱%','학습쌍 범위'],fore,'forecast-results')+'</details></section>'
 body+='''<section><h2>비용·위험·불확실성</h2><p>완료현물20일 변동성 목표20%, 명목1배 상한. 현물 롱/선물 숏, 기본 판단1시간 뒤 시가,5%p 밴드. 현물0.00001BTC·최소5USDT·편도수수료10bp, 선물0.001BTC·최소50USDT·5bp, 양쪽충격1.5bp, 최종청산비용·실제 펀딩 포함. 정산 순간가 대신 원시 시간봉 mark 시가를 썼으며 실제 호가·부분체결·과거 주문규정은 복원하지 못했습니다.</p><p>옵션 최근 기본 보유구간은2개뿐입니다. 352주가 모두 독립 거래기회인 것도 아닙니다. 중첩 라벨·연속 보유·누적 가설 선택 편향과 정보가용 가정은 남으며, 수익 확대만으로 알파라고 부르지 않습니다.</p><details><summary>연도별 수익</summary>'''+table(['규칙','기간','2022','2023','2024','2025','2026'],years,'annual-results')+'</details><details><summary>가격손익·비용·펀딩·노출</summary>'+table(['규칙','기간','가격손익USDT','비용USDT','펀딩USDT','평균노출%','연변동성%'],cost,'cost-results')+'</details><details><summary>현물 롱·선물 숏 귀속</summary>'+table(['규칙','기간','롱 순손익USDT','숏 순손익USDT'],sides,'side-results')+'</details><details><summary>대조군 대비 불확실성</summary><p>14일 블록2,000회95%구간(%/일).7/28일도JSON보존.</p>'+table(['규칙','기간','대조군','일수익차 95%구간'],ci,'uncertainty-results')+'</details></section><section><h2>모든 조건을 보존합니다</h2><details id="matrix"><summary>96개 조건별 계좌</summary>'
 body+=table(['규칙','기간','조건','수익%','DD%','연변동성%','보유구간','비용USDT'],[[r['strategy'],r['period'],r['scenario'],f"{r['return_pct']:+.2f}",f"{r['max_drawdown_pct']:.2f}",f"{r['realized_vol_pct']:.2f}",r['round_trips'],f"{r['fees']+r['impact']:.2f}"] for r in rows],'all-accounts')+'</details></section><section id="proof"><h2>원자료와 다른 계산으로 검산</h2><p>원시 CFTC 정수 포지션·공개시각과 BTC ZIP329개를 대조했습니다. 옵션 평균/표준오차2,412개는 별도 중심화 정규방정식으로 확인했습니다(최대차5.48×10⁻¹⁶). 수량·무거래는 폐형식 계산, 자산·실제 펀딩·시간 DD는 Decimal 원장으로 검산했으며 최대차2×10⁻¹¹입니다. 새14개 경계검사 통과. COT63파일·옵션98파일 소켓 차단 바이트 일치.</p>'
 body+=table(['실험','판단','수량','무거래','이벤트','일말자산','일치파일'],proof,'proof-results')
 body+='''<p>옵션 검산기의 첫 버전은 학습에 필요한2020년1월 원시 가격을 누락하여 중단했습니다. 해당 월을 포함해 전수 재검산했고 전략·성과는 변경하지 않았습니다. 다른 구현 오류/이전 실패도 연구 기록에 보존했습니다.</p><p>연구 목표는 아직 미완료입니다. 이 정적 페이지는 작업 지속이나 실거래 상태를 보장하는 표시가 아닙니다.</p></section><section id="downloads"><h2>검증 자료</h2><div class="downloads"><a download href="downloads/btc-position-evidence.zip">96계좌·포지션원시·검산 ZIP ↓</a><a download href="downloads/btc-position-evidence.json">전체 수치·불확실성 JSON ↓</a><a download href="downloads/btc-position-summary.csv">96조건 요약 CSV ↓</a></div><p>ZIP에 계좌·CFTC 공개자료·검산 소스를 담았습니다. 별도 BTC 가격 아카이브와 공통 의존성은 저장소의 재현 절차를 참조해야 하며, ZIP 단독으로 원시 BTC 전체가 제공되는 것은 아닙니다.</p><p><a href="EXPERIMENT_BTC_COT_20261002.md">COT 성과 전 명세</a> · <a href="EXPERIMENT_BTC_OPTIONS_20261002.md">옵션 성과 전 명세</a> · <a href="BTC_WEB_RESEARCH_20261002.md">원문·실패 기록</a></p><p>출처: <a href="https://publicreporting.cftc.gov/">CFTC 공개자료</a> · <a href="https://doi.org/10.1002/fut.22332">Baur/Smales2022</a> · <a href="https://doi.org/10.1016/j.frl.2026.110300">Shen/Li/Luo2026</a>. 두 논문은 초록·등록정보 검토이며 전문 복제가 아닙니다.</p></section><footer>BUILD1002p1 · BTC-only · 실거래 없음</footer></main></body></html>'''
 (DOC/'btc-position-research.html').write_text(body)
 p=DOC/'btc-web-research.html';old=p.read_text()
 if 'id="position-followup"' not in old:p.write_text(old.replace('<h1>','<p id="position-followup" class="boundary">후속96계좌: <a href="btc-position-research.html">주체별 선물·옵션 추가정보 검증 ↗</a></p><h1>',1))
 files=['btc-position-research.html','btc-web-research.html','downloads/btc-position-evidence.zip','downloads/btc-position-evidence.json','downloads/btc-position-summary.csv','EXPERIMENT_BTC_COT_20261002.md','EXPERIMENT_BTC_OPTIONS_20261002.md','BTC_WEB_RESEARCH_20261002.md','assets/btc-continuation.css','assets/icon.svg'];o=ROOT/'runs/btc-position-report-20261002';o.mkdir(exist_ok=True);(o/'public-manifest.json').write_bytes(canonical({n:{'sha256':sha((DOC/n).read_bytes()),'bytes':(DOC/n).stat().st_size} for n in files}));print(json.dumps({'accounts':len(rows),'public_files':len(files)}))
if __name__=='__main__':run()
