"""Publish ONLY newly verified TC72 BTC-perpetual results, no research reruns."""
import csv,json,zipfile
from pathlib import Path
from html import escape
from build_btc_web_report import table,read
from btc_perp_bot.research.archive import canonical,sha
ROOT=Path(__file__).resolve().parents[1];DOC=ROOT/'docs';DOWN=DOC/'downloads';RUN=ROOT/'runs/btc-tradecount-20261004';BUILD='1004n1'
def pct(x):return f'{x:+.2f}'
def run():
 s=read(RUN/'summary.json');v=read(RUN/'verification.json');rep=read(RUN/'reproduction.json');sel=read(RUN/'selection.json');fc=read(RUN/'forecast-summary.json');unc=read(RUN/'uncertainty.json');diag=read(RUN/'diagnostics.json');act=read(RUN/'activity.json');assert len(s)==v['accounts']==72 and rep['all_bytes_equal'];names=('TC_INFO','TC_FLOW','TC_COUNT','TC_HAR','TC_INV','TC_TREND');base=[];annual=[];cost=[];forecast=[];ci=[];rows=[];stress=[];side=[]
 for n in names:
  a,b=[s[p+'-'+n+'-base']['metrics'] for p in ('main','recent')];base.append([n+(' · 기본' if n=='TC_INFO' else ' · 대조'),pct(a['return_pct']),f"{a['max_drawdown_pct']:.2f}",pct(b['return_pct']),f"{b['max_drawdown_pct']:.2f}"])
  for p in ('main','recent'):
   e=s[p+'-'+n+'-base'];m=e['metrics'];annual.append([n,p,*[pct(e['annual'][y]['return_pct']) if y in e['annual'] else '해당 없음' for y in ('2022','2023','2024','2025','2026')]]);cost.append([n,p,pct(m['gross_pnl']),f"{m['fees']+m['impact']:.2f}",pct(m['funding']),f"{m['realized_vol_pct']:.2f}",f"{m['sharpe']:.3f}"])
   f=fc[p]['models'][n];forecast.append([p,n,f['n'],f"{f['mse']:.9g}",f"{f['qlike']:.6f}",f['floor_count']])
   for ctrl in ('TC_FLOW','TC_HAR'):
    u=unc[p+'-'+n]['vs_'+ctrl][1]['ci95'];ci.append([p,n,ctrl,f'{u[0]:+.5f} ~ {u[1]:+.5f}'])
 for p in ('main','recent'):
  for direction,z in diag[p+'-TC_INFO-base.json.gz']['long_short'].items():side.append([p,direction,pct(z['gross']),f"{z['fees']+z['impact']:.2f}",pct(z['funding']),pct(z['net'])])
 for scenario in ('base','cost_x2','delay1','delay24','risk10','data_delay7'):stress.append([scenario,*[pct(s[p+'-TC_INFO-'+scenario]['metrics']['return_pct']) for p in ('main','recent')]])
 for key,e in s.items():
  p,n,c=key.split('-');m=e['metrics'];rows.append({'strategy':n,'period':p,'scenario':c,**{k:m[k] for k in ('return_pct','max_drawdown_pct','realized_vol_pct','sharpe','round_trips','fees','impact','funding','mean_exposure')}})
 evidence={'build':BUILD,'account_rows':rows,'summary':s,'verification':v,'reproduction':rep,'selection':sel,'forecast_summary':fc,'uncertainty':unc,'diagnostics':diag,'activity':act,'source_audit':read(ROOT/'data/btc-tradecount-20261004/independent-audit.json'),'scope':'BTCUSDT perpetual-only; aggregate trade-count risk conditional on current variance/volume/pressure, not orders or trader identity. Extra7day moves count only; current-vintage repeated development history, no adopted strategy or live service.'};(DOWN/'btc-tradecount-evidence.json').write_bytes(canonical(evidence))
 with (DOWN/'btc-tradecount-summary.csv').open('w',newline='') as f:w=csv.DictWriter(f,fieldnames=list(rows[0]));w.writeheader();w.writerows(rows)
 with zipfile.ZipFile(DOWN/'btc-tradecount-evidence.zip','w',compression=zipfile.ZIP_STORED) as z:
  files=[(p,'run/'+p.name) for p in sorted(RUN.iterdir()) if p.is_file()]
  for n in ('prepare_btc_tradecount_data.py','audit_btc_tradecount_data.py','btc_tradecount_study.py','test_btc_tradecount_study.py','verify_btc_tradecount_study.py','reproduce_btc_tradecount_study.py','btc_target_ledger.py','btc_periodic_study.py','verify_btc_periodic_study.py'):files.append((ROOT/'tools'/n,'source/'+n))
  for folder,ns in [('btc-tradecount-20261004',('daily.json.gz','prepare-audit.json','independent-audit.json'))]:
   for n in ns:files.append((ROOT/'data'/folder/n,'input/'+folder+'/'+n))
  files.append((DOC/'EXPERIMENT_BTC_TRADECOUNT_20261004.md','source/EXPERIMENT_BTC_TRADECOUNT_20261004.md'))
  for p,n in files:z.writestr(zipfile.ZipInfo(n,(2026,10,4,0,0,0)),p.read_bytes())
  z.writestr(zipfile.ZipInfo('DATA-SOURCES.txt',(2026,10,4,0,0,0)),'''72 BTCUSDT perpetual-only simulated accounts; no spot trades. New input: positive integer matching-engine counts per completed hour, aggregated to daily count. Counts are not distinct orders, traders, news events or identified retail/whale positions. All price, quote-volume, net/gross flow risk controls stay current when only the new count source is additionally delayed7days. Identical common validity/training masks are used across four models. New daily counts/independent receipt and all new plans, fits, accounts, verification included.
Stored original80-month pressure raw-hour field strings, old market329ZIP/RV80month data and their pinned verification receipts, shared modules/repository layout and dependencies remain separate. This ZIP is NOT a standalone environment. Unchanged original archives/old account studies were not rerun or republished. No paper PDFs, private data, financial-account access, credentials or live-order programs.
Motivation, not replication: https://doi.org/10.3389/fphy.2021.644102 (minute-level volume/spread/tweet volatility, not a count or costed account experiment); https://doi.org/10.3390/jrfm12010025 (descriptive trade-size/count and microstructure facts).
''')
 status='기각' if not sel['passed'] else '개발 관문 통과 · 전진 검증 전';main=s['main-TC_INFO-base']['metrics'];recent=s['recent-TC_INFO-base']['metrics']
 html='''<!doctype html><html lang="ko"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta http-equiv="Content-Security-Policy" content="default-src 'self';script-src 'none';style-src 'self';img-src 'self' data:;connect-src 'none';object-src 'none';base-uri 'none';form-action 'none'"><title>BTC 체결건수 위험 추가정보 검증</title><link rel="icon" href="assets/icon.svg"><link rel="stylesheet" href="assets/btc-continuation.css"></head><body><a class="skip" href="#results">결과로 이동</a><header><a href="./">BTC RESEARCH</a><nav><a href="btc-web-research.html">전체 연구 기록</a><a href="#downloads">검증 자료</a></nav></header><main><p class="eyebrow">BTC PERPETUAL ONLY · BUILD1004n1</p><h1>같은 거래량, 더 많은 체결은<br>다음 날 위험의 정보인가?</h1><p class="lead">기존 실현위험·거래대금·순불균형·시간별 절대불균형이 같아도 체결건수가 다른 경우의 추가 위험정보를 검정했습니다. 위험예측과 비용 후 선물 계좌의 관문을 별도로 공개합니다.</p>'''
 html+=f'<div class="facts"><article><b>72</b><span>순수 BTC 선물 조건계좌</span></article><article><b>{status}</b><span>TC_INFO 기본 후보</span></article><article><b>{rep["matched_files"]}</b><span>소켓차단 바이트 일치</span></article></div><p class="boundary">2022–2025 및2026.01–08은 여러 번 본 개발 이력이며 새 미사용 OOS가 아닙니다. 검산 성공과 전략 성공은 별개입니다. 실거래·상시 모의서비스는 시작하지 않았습니다.</p>'
 html+='<section id="results"><h2>기본과 모든 대조군</h2><p>각1,000USDT. 수익과 최대낙폭(DD)은 %. 전 계좌는 BTCUSDT 무기한선물만 거래하며 현물·혼합 성과가 아닙니다.</p>'+table(['규칙','4년 수익','4년 DD','최근 수익','최근 DD'],base,'base-results')
 html+=f'<p>기본 주 {pct(main["return_pct"])}%·DD{main["max_drawdown_pct"]:.2f}%·연변동성{main["realized_vol_pct"]:.2f}%·Sharpe{main["sharpe"]:.3f}, 최근 {pct(recent["return_pct"])}%·DD{recent["max_drawdown_pct"]:.2f}%. 주수익52.838713%·DD13.561952%·연변동성13.343621%,최근수익4.628391% 등 사전기준을 그대로 유지했습니다. 더 좋은 대조군·지연조건으로 기본을 교체하지 않았습니다.</p></section>'
 html+='''<section><h2>거래대금과 체결건수를 구별했습니다</h2><p>같은 금액이 적은 큰 체결 또는 많은 작은 체결로 이뤄질 수 있습니다. 새 N은 완료된24개 시간의 양의 정수 체결건수 합이며 c=ln(N/직전28일 평균N)입니다. 현재일은 분모에서 제외합니다. matching prints는 실제 주문·투자자·정보사건 수가 아니며, 봇·엔진의 쪼개기도 영향을 줄 수 있습니다.</p><p>INFO는 완료1/5/22일 logRV와 거래대금충격·순불균형·절대시간불균형·c를 사용합니다. FLOW는c만 제외, COUNT는위험과c만, HAR는위험만입니다. INV는FLOW²/INFO의 반대위험이고 TREND는기존20일위험입니다. 모든 계좌의 양방향 추세는 동일하며 새c로 방향을 고르지 않습니다.</p><p>365달력일·최소300공통완료목표,무제약OLS와훈련잔차smearing/floor1e−8을 사전 고정했습니다. 현재flow29일과RV22일을 사용하고 추가7일 조건은 새count29일만 늦춥니다. 지연된count 결측이공통학습 마스크에도영향을줄수있어대조계좌가무조건동일하다고하지않습니다.</p><p>이미 검산된58,440시간문자열에서새정수합을별도로감사했고2,435일 중2,431일 유효·기존4일 품질무효를 유지했습니다. 원80개월ZIP·기존329시장·RV전체 재감사는 하지 않았습니다. 누락·소수건수·0·음수·중복·종료시계오류를유리하게복원하지않습니다.</p><p>동기 논문의 분 단위 GARCH 정보와 과거 주문장 통계가 우리 일별 체결건수의 미래계좌 성공을 증명하는 것은 아닙니다. 현재 아카이브와1h실행 여유는 최초게시 빈티지 증거도 아닙니다.</p></section>'''
 html+='<section><h2>위험예측과 계좌 성과의 관문</h2>'+table(['기간','모형','공통일','MSE','QLIKE','floor'],forecast,'forecast-results')
 html+=f'<p>공통목표 주{fc["main"]["n"]}일({fc["main"]["coverage"]*100:.2f}%),최근{fc["recent"]["n"]}일({fc["recent"]["coverage"]*100:.2f}%)입니다. c계수중앙값은 주{fc["main"]["count_coefficient"]["median"]:.6f}/최근{fc["recent"]["count_coefficient"]["median"]:.6f}입니다. 양수계수만으로 채택하지 않으며 양기간QLIKE/MSE·순익·낙폭·비용/지연 관문을 함께 적용했습니다. 모든 음수계수·공통목표·7/14/28일손실차구간은JSON에보존했습니다. 위험예측의목표는다음UTC일전체이며첫1h는집행전입니다.</p><details><summary>사전 선정 관문 전체</summary>'+table(['고정 관문','결과'],[[k,'통과' if val else '미달'] for part in ('checks','information_increment') for k,val in sel[part].items()],'selection-results')+'</details></section>'
 html+='<section><h2>비용·펀딩·실행 지연</h2><p>선물 양방향5bp수수료+편도1.5bp불리한 impact,실제펀딩×시간mark시가대용. 원목표를 고정한 기본1h·추가1h/24h지연,수량0.001BTC·최소50USDT·감축예외·5%p밴드·종료비용. 목표명목≤1배이며 실제호가·부분체결·역사규정·정확청산·세금·운영비는 미복원입니다.</p>'+table(['기본 후보 조건','4년 수익%','최근 수익%'],stress,'stress-results')+'<details><summary>연도별 수익</summary>'+table(['규칙','기간','2022','2023','2024','2025','2026.01–08'],annual,'annual-results')+'</details><details><summary>가격손익·비용·펀딩</summary><p>금액USDT. 방향은동일하고위험량만다릅니다. 양방향모두펀딩이있으며현물성과와다릅니다.</p>'+table(['규칙','기간','가격손익','비용','펀딩','연변동성%','Sharpe'],cost,'cost-results')+'</details><details><summary>기본의 롱·숏 기여</summary><p>금액USDT. 선물롱과선물숏을분리한독립원장검산입니다.</p>'+table(['기간','방향','가격손익','비용','펀딩','순손익'],side,'direction-results')+'</details><details><summary>수익차의 불확실성</summary><p>14일 원형블록2,000회95%구간(%/일). 전체7/14/28일구간은다운로드에있으며다중탐색을해소한새OOS가아닙니다.</p>'+table(['기간','규칙','대조','일수익차95%구간'],ci,'uncertainty-results')+'</details></section>'
 html+='<section><h2>모든 실패·조건 보존</h2><details id="matrix"><summary>72계좌 전체 보기</summary>'+table(['규칙','기간','조건','수익%','DD%','연변동성%','보유구간','펀딩USDT'],[[r['strategy'],r['period'],r['scenario'],pct(r['return_pct']),f"{r['max_drawdown_pct']:.2f}",f"{r['realized_vol_pct']:.2f}",r['round_trips'],pct(r['funding'])] for r in rows],'all-accounts')+'</details></section>'
 html+=f'<section id="proof"><h2>독립 검산과 재현</h2><p>사전663c473→새정수집계·25합성검사구현d231983 이후 첫성과 순서입니다. 새count독립Decimal합 차이0. {v["raw_feature_days"]:,}피처일·{v["raw_forecast_days"]:,}예측일·{v["independent_model_fits"]:,}별도정규방정식/smearing·{v["raw_daily_decisions"]:,}일판단·{v["independent_target_quantities"]:,}폐형식수량·{v["raw_mark_funding_events"]:,}펀딩·{v["daily_equities"]:,}일말자산·선정·{v["return_and_loss_block_bootstrap_checks"]}수익/손실구간을 검산했습니다. 계좌최대차{v["max_numeric_error"]:.3g}USDT.</p><p>기존 raw-hour 원시문자열을읽어 새count/피처를독립재구성하고,무변경원본ZIP검산은고정SHA영수증을재사용했습니다. 새{rep["matched_files"]}파일은소켓차단에서바이트일치했습니다. 숫자의재현성은미사용OOS·미래수익·실체결의증거와다릅니다.</p></section>'
 html+='''<section id="downloads"><h2>검증 자료</h2><div class="downloads"><a download href="downloads/btc-tradecount-evidence.zip">72계좌·피처·모형·검산 ZIP ↓</a><a download href="downloads/btc-tradecount-evidence.json">전체 수치·불확실성 JSON ↓</a><a download href="downloads/btc-tradecount-summary.csv">72조건 CSV ↓</a><a download href="EXPERIMENT_BTC_TRADECOUNT_20261004.md">성과 전 명세 ↓</a></div><p><a href="BTC_WEB_RESEARCH_20261002.md">원문 감사·실패 기록</a> · <a href="https://doi.org/10.3389/fphy.2021.644102">BTC 정보도착·위험 원문</a> · <a href="https://doi.org/10.3390/jrfm12010025">BTC 거래 크기·빈도 원문</a></p><p>ZIP에는새입력·모든피처/예측/잔차·72계좌·독립검산·재현해시가있습니다. 기존시장·raw시간문자열/RV자료·공통의존성·경로·이전검산영수증은별도로필요해완전독립실행환경은아닙니다. 논문PDF는재배포하지않습니다.</p><p>이후속으로외부검증은2,166조건계좌이며독립전략2,166개라는뜻이아닙니다. 기존198계좌/273파일도그대로보존했습니다. 채택전략0,공개자료·오프라인가상검증만수행했습니다.</p></section><footer>BUILD1004n1 · BTC-only · 실거래 없음</footer></main></body></html>'''
 (DOC/'btc-tradecount-research.html').write_text(html);p=DOC/'btc-web-research.html';old=p.read_text()
 if 'id="tradecount-followup"' not in old:p.write_text(old.replace('<h1>','<p id="tradecount-followup" class="boundary">새72순수선물계좌·외부2,166조건: <a href="btc-tradecount-research.html">체결건수의 추가 위험정보 검증 ↗</a></p><h1>',1))
 files=['btc-tradecount-research.html','btc-web-research.html','downloads/btc-tradecount-evidence.zip','downloads/btc-tradecount-evidence.json','downloads/btc-tradecount-summary.csv','EXPERIMENT_BTC_TRADECOUNT_20261004.md','BTC_WEB_RESEARCH_20261002.md'];o=ROOT/'runs/btc-tradecount-report-20261004';o.mkdir(exist_ok=True);(o/'public-manifest.json').write_bytes(canonical({n:{'sha256':sha((DOC/n).read_bytes()),'bytes':(DOC/n).stat().st_size} for n in files}));print({'accounts':len(rows),'public_files':len(files),'zip_bytes':(DOWN/'btc-tradecount-evidence.zip').stat().st_size,'selected':sel['passed']})
if __name__=='__main__':run()
