"""Publish ONLY newly verified TP72 BTC-perpetual results, no research reruns."""
import csv,json,zipfile
from pathlib import Path
from html import escape
from build_btc_web_report import table,read
from btc_perp_bot.research.archive import canonical,sha
ROOT=Path(__file__).resolve().parents[1];DOC=ROOT/'docs';DOWN=DOC/'downloads';RUN=ROOT/'runs/btc-pressure-20261004';BUILD='1004t1'
def pct(x):return f'{x:+.2f}'
def run():
 s=read(RUN/'summary.json');v=read(RUN/'verification.json');rep=read(RUN/'reproduction.json');sel=read(RUN/'selection.json');fc=read(RUN/'forecast-summary.json');unc=read(RUN/'uncertainty.json');diag=read(RUN/'diagnostics.json');act=read(RUN/'activity.json');assert len(s)==v['accounts']==72 and rep['all_bytes_equal'];names=('TP_INFO','TP_NET','TP_VOL','TP_HAR','TP_INV','TP_TREND');base=[];annual=[];cost=[];forecast=[];ci=[];rows=[];stress=[];side=[]
 for n in names:
  a,b=[s[p+'-'+n+'-base']['metrics'] for p in ('main','recent')];base.append([n+(' · 기본' if n=='TP_INFO' else ' · 대조'),pct(a['return_pct']),f"{a['max_drawdown_pct']:.2f}",pct(b['return_pct']),f"{b['max_drawdown_pct']:.2f}"])
  for p in ('main','recent'):
   e=s[p+'-'+n+'-base'];m=e['metrics'];annual.append([n,p,*[pct(e['annual'][y]['return_pct']) if y in e['annual'] else '해당 없음' for y in ('2022','2023','2024','2025','2026')]]);cost.append([n,p,pct(m['gross_pnl']),f"{m['fees']+m['impact']:.2f}",pct(m['funding']),f"{m['realized_vol_pct']:.2f}",f"{m['sharpe']:.3f}"])
   f=fc[p]['models'][n];forecast.append([p,n,f['n'],f"{f['mse']:.9g}",f"{f['qlike']:.6f}",f['floor_count']])
   for ctrl in ('TP_NET','TP_HAR'):
    u=unc[p+'-'+n]['vs_'+ctrl][1]['ci95'];ci.append([p,n,ctrl,f'{u[0]:+.5f} ~ {u[1]:+.5f}'])
 for p in ('main','recent'):
  for direction,z in diag[p+'-TP_INFO-base.json.gz']['long_short'].items():side.append([p,direction,pct(z['gross']),f"{z['fees']+z['impact']:.2f}",pct(z['funding']),pct(z['net'])])
 for scenario in ('base','cost_x2','delay1','delay24','risk10','data_delay7'):stress.append([scenario,*[pct(s[p+'-TP_INFO-'+scenario]['metrics']['return_pct']) for p in ('main','recent')]])
 for key,e in s.items():
  p,n,c=key.split('-');m=e['metrics'];rows.append({'strategy':n,'period':p,'scenario':c,**{k:m[k] for k in ('return_pct','max_drawdown_pct','realized_vol_pct','sharpe','round_trips','fees','impact','funding','mean_exposure')}})
 evidence={'build':BUILD,'account_rows':rows,'summary':s,'verification':v,'reproduction':rep,'selection':sel,'forecast_summary':fc,'uncertainty':unc,'diagnostics':diag,'activity':act,'scope':'BTCUSDT perpetual only, no spot account; gross hourly pressure risk evidence, not VPIN or new OOS; no accepted strategy, no real orders or operating service'};(DOWN/'btc-pressure-evidence.json').write_bytes(canonical(evidence))
 with (DOWN/'btc-pressure-summary.csv').open('w',newline='') as f:w=csv.DictWriter(f,fieldnames=list(rows[0]));w.writeheader();w.writerows(rows)
 with zipfile.ZipFile(DOWN/'btc-pressure-evidence.zip','w',compression=zipfile.ZIP_STORED) as z:
  files=[(p,'run/'+p.name) for p in sorted(RUN.iterdir()) if p.is_file()]
  for n in ('collect_btc_pressure_data.py','audit_btc_pressure_data.py','btc_pressure_study.py','test_btc_pressure_study.py','verify_btc_pressure_study.py','reproduce_btc_pressure_study.py','btc_target_ledger.py','btc_periodic_study.py','verify_btc_periodic_study.py'):files.append((ROOT/'tools'/n,'source/'+n))
  for folder,ns in [('btc-pressure-20261004',('daily.json.gz','prepare-audit.json','independent-audit.json')),('btc-rv-20261002',('daily-rv.json.gz','audit.json','verification.json'))]:
   for n in ns:files.append((ROOT/'data'/folder/n,'input/'+folder+'/'+n))
  files.append((DOC/'EXPERIMENT_BTC_PRESSURE_20261004.md','source/EXPERIMENT_BTC_PRESSURE_20261004.md'))
  for p,n in files:z.writestr(zipfile.ZipInfo(n,(2026,10,4,0,0,0)),p.read_bytes())
  z.writestr(zipfile.ZipInfo('DATA-SOURCES.txt',(2026,10,4,0,0,0)),'''72 BTCUSDT perpetual-only simulated accounts; no spot trades. Both long and short funding included. Fixed hourly taker quote imbalance is not volume-time VPIN, informed-trader identification, the original paper replication, or unused OOS. Binance public candle aggregates; 80 original perp hourly ZIPs checked in the new pressure input audit. Stored raw hourly fields, G/N, frozen RV and receipts included. Unchanged 329 market-ZIP and 80-month five-minute RV checks reused by pinned receipts, not rerun wholesale. Common market inputs, original archive ZIPs/CHECKSUMs, CF masks, prior market audit receipt, repository layout and Python dependencies remain necessary. This ZIP is NOT a standalone executable environment. No paper PDFs, private data, credentials or live-order programs are included.
Economic sources: Kitvanitphasu et al, Bitcoin wild moves (2026), DOI10.1016/j.ribaf.2025.103163 https://hdl.handle.net/11250/5321697 . Econometric counterargument: Andersen/Bondarenko, Reflecting on the VPIN dispute, DOI10.1016/j.finmar.2013.08.002 https://pure.au.dk/ws/files/83819068/rp13_42.pdf . Only general benchmark/classification methodology used from the latter; no other instruments studied.
''')
 status='기각' if not sel['passed'] else '개발 관문 통과 · 전진 검증 전';main=s['main-TP_INFO-base']['metrics'];recent=s['recent-TP_INFO-base']['metrics']
 html='''<!doctype html><html lang="ko"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta http-equiv="Content-Security-Policy" content="default-src 'self';script-src 'none';style-src 'self';img-src 'self' data:;connect-src 'none';object-src 'none';base-uri 'none';form-action 'none'"><title>BTC 선물 체결압력 위험 검증</title><link rel="icon" href="assets/icon.svg"><link rel="stylesheet" href="assets/btc-continuation.css"></head><body><a class="skip" href="#results">결과로 이동</a><header><a href="./">BTC RESEARCH</a><nav><a href="btc-web-research.html">전체 연구 기록</a><a href="#downloads">검증 자료</a></nav></header><main><p class="eyebrow">BTC PERPETUAL ONLY · BUILD1004t1</p><h1>체결압력의 위험 정보는<br>채택할 선물 전략으로 이어지지 않았습니다.</h1><p class="lead">시간별 순매수·순매도가 하루 전체로는 상쇄돼도 위험 정보가 남는지 검정했습니다. 최근 위험예측은 일부 개선됐지만 4년 주기간·비용 후 순계좌·지연 내구성 기준을 충족하지 못했습니다.</p>'''
 html+=f'<div class="facts"><article><b>72</b><span>순수 BTC 선물 조건계좌</span></article><article><b>{status}</b><span>TP_INFO 기본 후보</span></article><article><b>{rep["matched_files"]}</b><span>소켓차단 바이트 일치</span></article></div><p class="boundary">2022–2025 및2026.01–08은 여러 번 본 개발 이력이며 새 미사용 OOS가 아닙니다. 검산 성공과 전략 성공은 별개입니다. 실거래·상시 모의서비스는 시작하지 않았습니다.</p>'
 html+='<section id="results"><h2>기본과 모든 대조군</h2><p>각1,000USDT. 수익과 최대낙폭(DD)은 %. 전 계좌는 BTCUSDT 무기한선물만 거래하며 현물·혼합 성과가 아닙니다.</p>'+table(['규칙','4년 수익','4년 DD','최근 수익','최근 DD'],base,'base-results')
 html+=f'<p>기본 주 {pct(main["return_pct"])}%·DD{main["max_drawdown_pct"]:.2f}%·연변동성{main["realized_vol_pct"]:.2f}%·Sharpe{main["sharpe"]:.3f}, 최근 {pct(recent["return_pct"])}%·DD{recent["max_drawdown_pct"]:.2f}%. 주수익52.838713%·DD13.561952%·연변동성13.343621%,최근수익4.628391% 등 사전기준을 그대로 유지했습니다. 더 좋은 대조군·지연조건으로 기본을 교체하지 않았습니다.</p></section>'
 html+='''<section><h2>하루 순압력과 시간별 압력을 구별했습니다</h2><p>공식1시간 집계의 총체결액Q와 taker-buy액B로 S=2B−Q를 계산했습니다. N=|일합S|/일합Q, G=일합|S|/일합Q입니다. 반대방향 시간들이 상쇄되면 N은0이어도 G는양수일 수 있습니다. 매수·매도분류를 가격변화로 추측하지 않으며 G를 정보거래자 확률이나 원문의 volume-time VPIN으로 부르지 않습니다.</p><p>TP_INFO는 완료1/5/22일 실현분산의 로그,총거래량 충격,일순압력N,시간별압력G로 다음 날 분산을 예측합니다. NET은G만 제외, VOL은N/G를 제외, HAR는위험 지속성만 사용합니다. INV는NET²/INFO의 반대위험 대조이지 방향반전이 아닙니다. TREND는같은 방향에 기존20일 위험을 부여합니다.</p><p>365달력일·최소300공통완료목표의 무제약OLS,훈련잔차 smearing을 고정했습니다. 모든 모형에 같은 누락 행을 적용하며 미래 label은 제외했습니다. 자료 결측은 보유유지이고 유리한대조로 전환하지 않습니다. 기본일00UTC에서 전날까지22일RV와29일flow만 사용하며,7일 자료지연은 flow만 늦춥니다.</p><p>원문 Q180은 bucket시작시점과 이후16개bucket 사용 설명이 있어 실시간 가용시계가 불명확합니다. 당일 점프크기도 실제 종가수익과 다릅니다. 우리는 그 시계를 복제하지 않고 완료된 고정시간 집계의 별도 가설을 만들었습니다.</p></section>'''
 html+='<section><h2>위험예측 개선은 기간별로 달랐습니다</h2>'+table(['기간','모형','공통일','MSE','QLIKE','floor'],forecast,'forecast-results')
 html+=f'<p>공통목표 주{fc["main"]["n"]}일({fc["main"]["coverage"]*100:.2f}%),최근{fc["recent"]["n"]}일. INFO의 주기간QLIKE와MSE는NET보다 나쁘고,최근에는개선됐습니다. G계수의중앙값은주{fc["main"]["gross_coefficient"]["median"]:.3f}/최근{fc["recent"]["gross_coefficient"]["median"]:.3f}로양수이나양의계수만으로채택하지 않습니다. 14일 블록구간에서 NET 대비 MSE·QLIKE 개선은 두 기간 모두0을 포함합니다. 모든 음수계수·예측오차·7/14/28일 불확실성을 보존했습니다.</p></section>'
 html+='<section><h2>비용·펀딩·실행 지연</h2><p>선물 양방향5bp수수료+편도1.5bp불리한 impact,실제펀딩×시간mark시가대용. 원목표를 고정한 기본1h·추가1h/24h지연,수량0.001BTC·최소50USDT·감축예외·5%p밴드·종료비용. 목표명목≤1배이며 실제호가·부분체결·역사규정·정확청산·세금·운영비는 미복원입니다.</p>'+table(['기본 후보 조건','4년 수익%','최근 수익%'],stress,'stress-results')+'<details><summary>연도별 수익</summary>'+table(['규칙','기간','2022','2023','2024','2025','2026.01–08'],annual,'annual-results')+'</details><details><summary>가격손익·비용·펀딩</summary><p>금액USDT. 방향은동일하고위험량만다릅니다. 양방향모두펀딩이있으며현물성과와다릅니다.</p>'+table(['규칙','기간','가격손익','비용','펀딩','연변동성%','Sharpe'],cost,'cost-results')+'</details><details><summary>기본의 롱·숏 기여</summary><p>금액USDT. 선물롱과선물숏을분리한독립원장검산입니다.</p>'+table(['기간','방향','가격손익','비용','펀딩','순손익'],side,'direction-results')+'</details><details><summary>수익차의 불확실성</summary><p>14일 원형블록2,000회95%구간(%/일). 전체7/14/28일구간은다운로드에있으며다중탐색을해소한새OOS가아닙니다.</p>'+table(['기간','규칙','대조','일수익차95%구간'],ci,'uncertainty-results')+'</details></section>'
 html+='<section><h2>모든 실패·조건 보존</h2><details id="matrix"><summary>72계좌 전체 보기</summary>'+table(['규칙','기간','조건','수익%','DD%','연변동성%','보유구간','펀딩USDT'],[[r['strategy'],r['period'],r['scenario'],pct(r['return_pct']),f"{r['max_drawdown_pct']:.2f}",f"{r['realized_vol_pct']:.2f}",r['round_trips'],pct(r['funding'])] for r in rows],'all-accounts')+'</details></section>'
 html+=f'<section id="proof"><h2>독립 검산과 재현</h2><p>사전c3e4ea3→입력da044fc→19합성검사구현a2d5537 후 첫성과. 새80원시perp ZIP/58,440시간 집계·4,870피처/예측일·{v["independent_model_fits"]:,}별도정규방정식·{v["independent_target_quantities"]:,}폐형식수량·{v["raw_mark_funding_events"]:,}펀딩·{v["daily_equities"]:,}일말자산과선정·204수익/손실구간을검산했습니다. 계좌최대차{v["max_numeric_error"]:.3g}USDT. 무변경329시장ZIP과70만5분봉은과거SHA검산영수증을재사용했고전체재검사하지않았습니다.</p><p>초기float순압력의작은상쇄오차는성과전에Decimal60자리로수정하고초기자료/로그를보존했습니다. 원자료·가설·판정기준변경은없습니다. 새{rep["matched_files"]}파일은소켓차단에서바이트일치했습니다. 현재배포아카이브빈티지는역사최초수신을보증하지않습니다.</p></section>'
 html+='''<section id="downloads"><h2>검증 자료</h2><div class="downloads"><a download href="downloads/btc-pressure-evidence.zip">72계좌·피처·모형·검산 ZIP ↓</a><a download href="downloads/btc-pressure-evidence.json">전체 수치·불확실성 JSON ↓</a><a download href="downloads/btc-pressure-summary.csv">72조건 CSV ↓</a><a download href="EXPERIMENT_BTC_PRESSURE_20261004.md">성과 전 명세 ↓</a></div><p><a href="BTC_WEB_RESEARCH_20261002.md">원문 감사·실패 기록</a> · <a href="https://hdl.handle.net/11250/5321697">BTC 주문흐름·점프 원문</a> · <a href="https://doi.org/10.1016/j.finmar.2013.08.002">VPIN 방법론 반론</a></p><p>ZIP에는새입력·모든피처/예측/잔차·72계좌·독립검산·재현해시가있습니다. 원래시장자료·원시ZIP·CF마스크·공통의존성·경로·이전시장검산영수증은별도로필요해완전독립실행환경은아닙니다. 논문PDF는재배포하지않습니다.</p><p>이후속으로외부검증은1,878조건계좌이며독립전략1,878개라는뜻이아닙니다. 기존198계좌/273파일도그대로보존했습니다. 채택전략0,공개자료·오프라인가상검증만수행했습니다.</p></section><footer>BUILD1004t1 · BTC-only · 실거래 없음</footer></main></body></html>'''
 (DOC/'btc-pressure-research.html').write_text(html);p=DOC/'btc-web-research.html';old=p.read_text()
 if 'id="pressure-followup"' not in old:p.write_text(old.replace('<h1>','<p id="pressure-followup" class="boundary">새72순수선물계좌·외부1,878조건: <a href="btc-pressure-research.html">시간별 체결압력 위험의 비용 후 검증 ↗</a></p><h1>',1))
 files=['btc-pressure-research.html','btc-web-research.html','downloads/btc-pressure-evidence.zip','downloads/btc-pressure-evidence.json','downloads/btc-pressure-summary.csv','EXPERIMENT_BTC_PRESSURE_20261004.md','BTC_WEB_RESEARCH_20261002.md'];o=ROOT/'runs/btc-pressure-report-20261004';o.mkdir(exist_ok=True);(o/'public-manifest.json').write_bytes(canonical({n:{'sha256':sha((DOC/n).read_bytes()),'bytes':(DOC/n).stat().st_size} for n in files}));print({'accounts':len(rows),'public_files':len(files),'zip_bytes':(DOWN/'btc-pressure-evidence.zip').stat().st_size,'selected':sel['passed']})
if __name__=='__main__':run()
