"""Publish only the independently verified MI72 experiment; no new calculations or old reruns."""
import csv,json,zipfile
from pathlib import Path
from build_btc_web_report import table,read
from btc_perp_bot.research.archive import canonical,sha
ROOT=Path(__file__).resolve().parents[1];DOC=ROOT/'docs';DOWN=DOC/'downloads';RUN=ROOT/'runs/btc-collateral-20261004';INPUT=ROOT/'data/btc-collateral-20261004';BUILD='1004c1'
def pct(x):return f'{x:+.2f}'
def number(x):return '자료 부족' if x is None else f'{x:.9g}'
def run():
 s=read(RUN/'summary.json');v=read(RUN/'verification.json');rep=read(RUN/'reproduction.json');sel=read(RUN/'selection.json');fc=read(RUN/'forecast-summary.json');unc=read(RUN/'uncertainty.json');diag=read(RUN/'diagnostics.json');act=read(RUN/'activity.json');source=read(INPUT/'independent-audit.json');assert len(s)==v['accounts']==72 and rep['all_bytes_equal'];names=('CD_INFO','CD_FUND','CD_COIN','CD_PRICE','CD_INV','CD_TREND');base=[];annual=[];cost=[];forecast=[];ci=[];rows=[];stress=[];side=[];activity=[]
 for n in names:
  a,b=[s[p+'-'+n+'-base']['metrics'] for p in ('main','recent')];base.append([n+(' · 기본' if n=='CD_INFO' else ' · 대조'),pct(a['return_pct']),f"{a['max_drawdown_pct']:.2f}",pct(b['return_pct']),f"{b['max_drawdown_pct']:.2f}"])
  for p in ('main','recent'):
   e=s[p+'-'+n+'-base'];m=e['metrics'];annual.append([n,p,*[pct(e['annual'][y]['return_pct']) if y in e['annual'] else '해당 없음' for y in ('2022','2023','2024','2025','2026')]]);cost.append([n,p,pct(m['gross_pnl']),f"{m['fees']+m['impact']:.2f}",pct(m['funding']),f"{m['realized_vol_pct']:.2f}",number(m['sharpe'])]);ac=act[p][n+'-base'];activity.append([p,n,ac['override_weeks'],ac['override_days'],ac['fallback_days'],ac['invalid_feature_days'],ac['model_missing_days']])
   if n in fc[p]['0']['models']:
    f=fc[p]['0']['models'][n];forecast.append([p,n,f['n'],number(f['mse']),number(None if f['sign_accuracy'] is None else f['sign_accuracy']*100),f['negative_last_beta_weeks'],number(f['median_last_beta'])])
   for ctrl in ('CD_FUND','CD_TREND'):
    u=unc[p+'-'+n]['vs_'+ctrl][1]['ci95'];ci.append([p,n,ctrl,f'{u[0]:+.5f} ~ {u[1]:+.5f}'])
 for p in ('main','recent'):
  for direction,z in diag[p+'-CD_INFO-base.json.gz']['long_short'].items():side.append([p,direction,pct(z['gross']),f"{z['fees']+z['impact']:.2f}",pct(z['funding']),pct(z['net'])])
 for c in ('base','cost_x2','delay1','delay24','risk10','data_delay7'):stress.append([c,*[pct(s[p+'-CD_INFO-'+c]['metrics']['return_pct']) for p in ('main','recent')]])
 for key,e in s.items():
  p,n,c=key.split('-');m=e['metrics'];rows.append({'strategy':n,'period':p,'scenario':c,**{k:m[k] for k in ('return_pct','max_drawdown_pct','realized_vol_pct','sharpe','round_trips','fees','impact','funding','mean_exposure')}})
 evidence={'build':BUILD,'account_rows':rows,'summary':s,'verification':v,'reproduction':rep,'selection':sel,'forecast_summary':fc,'uncertainty':unc,'diagnostics':diag,'activity':act,'source_audit':source,'scope':'Same-BTC coin-versus-USDT settled funding is information only, not a collateral causal identification or cross-contract arbitrage. Only BTCUSDT perpetual simulated executions. Actual rate timestamps retained; current API vintage is not original-publication evidence. Repeated development history, no live service.'};(DOWN/'btc-collateral-evidence.json').write_bytes(canonical(evidence))
 with (DOWN/'btc-collateral-summary.csv').open('w',newline='') as f:w=csv.DictWriter(f,fieldnames=list(rows[0]));w.writeheader();w.writerows(rows)
 with zipfile.ZipFile(DOWN/'btc-collateral-evidence.zip','w',compression=zipfile.ZIP_STORED) as z:
  files=[(p,'run/'+p.name) for p in sorted(RUN.iterdir()) if p.is_file()]
  for n in ('collect_btc_collateral_data.py','audit_btc_collateral_data.py','btc_collateral_study.py','test_btc_collateral_study.py','verify_btc_collateral_study.py','reproduce_btc_collateral_study.py','btc_target_ledger.py','btc_continuity_study.py','btc_persistence_study.py'):files.append((ROOT/'tools'/n,'source/'+n))
  for n in ('funding.json.gz','prepare-audit.json','independent-audit.json'):files.append((INPUT/n,'input/btc-collateral-20261004/'+n))
  files += [(p,'input/btc-collateral-20261004/'+str(p.relative_to(INPUT))) for folder in ('raw','failures') for p in sorted((INPUT/folder).glob('*')) if p.is_file()]
  files.append((DOC/'EXPERIMENT_BTC_COLLATERAL_20261004.md','source/EXPERIMENT_BTC_COLLATERAL_20261004.md'))
  for p,n in files:z.writestr(zipfile.ZipInfo(n,(2026,10,4,0,0,0)),p.read_bytes())
  z.writestr(zipfile.ZipInfo('DATA-SOURCES.txt',(2026,10,4,0,0,0)),'''72 BTCUSDT perpetual-only accounts. New signal D is the past 7-day settled BTCUSD_PERP coin-margined funding rate sum minus the same-window BTCUSDT rate sum, simply annualized by 365/7. Coin contract is information only; no coin trades, spot hedges, collateral holding or cross-contract carry accounts. BTCUSD_PERP public /dapi/v1/fundingRate only, 80 fixed UTC monthly windows Jan2020-Aug2026. Empty first seven months and missing June30 2026 08UTC bucket retained, no interpolation. Current-vintage API and actual-ms timestamps do not prove first publication or live execution. All 21 nominal eight-hour buckets must contain exactly one already-settled record. Extra7d moves the spread window and coin-rate control, not current USDT-funding/price controls.
All new raw public responses, source receipts, plans/forecasts/accounts/checks included. Common prior market and original audits, pressure raw-hour tuples, shared modules, repository layout and Python dependencies remain separately required; NOT a standalone environment. No PDFs, individual records, credentials or financial-account access. Motivation only: Giagkiozis/Said2024 https://doi.org/10.5195/ledger.2024.325 ; Haghani/White2026 https://elmwealth.com/perpetual-futures/ . Neither demonstrates this strategy alpha.
''')
 main=s['main-CD_INFO-base']['metrics'];recent=s['recent-CD_INFO-base']['metrics'];status='기각' if not sel['passed'] else '개발 관문 통과 · 전진 검증 전';gates=[[k,'통과' if val else '미달'] for part in ('checks','information_increment') for k,val in sel[part].items()]
 html='''<!doctype html><html lang="ko"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta http-equiv="Content-Security-Policy" content="default-src 'self';script-src 'none';style-src 'self';img-src 'self' data:;connect-src 'none';object-src 'none';base-uri 'none';form-action 'none'"><title>BTC 담보계약 펀딩 추가정보 검증</title><link rel="icon" href="assets/icon.svg"><link rel="stylesheet" href="assets/btc-continuation.css"></head><body><a class="skip" href="#results">결과로 이동</a><header><a href="./">BTC RESEARCH</a><nav><a href="btc-web-research.html">전체 연구 기록</a><a href="#downloads">검증 자료</a></nav></header><main><p class="eyebrow">BTC PERPETUAL ONLY · BUILD1004c1</p><h1>담보계약별 펀딩 차이가<br>추가 방향정보를 주는가?</h1><p class="lead">같은 BTC의 코인 담보·USDT 담보 선물 간 이미 정산된 펀딩 차이를 검증했습니다. 주규칙과 모든 대조·실패 조건을 함께 보존합니다.</p>'''
 html+=f'<div class="facts"><article><b>72</b><span>순수 BTC 선물 조건계좌</span></article><article><b>{status}</b><span>CD_INFO 기본 후보</span></article><article><b>{rep["matched_files"]}</b><span>소켓차단 바이트 일치</span></article></div><p class="boundary">2022–2025 및 2026.01–08은 반복해서 본 개발 이력입니다. 새 미사용 OOS나 미래 수익 보장이 아닙니다. 검산 통과와 전략 채택은 별개이며 실거래·상시 모의서비스는 시작하지 않았습니다.</p>'
 html+='<section id="results"><h2>기본과 모든 대조군</h2><p>각1,000USDT, 수익·낙폭은 %. 모든 체결은 BTCUSDT 무기한선물입니다. BTCUSD 코인 담보 선물은 정보로만 쓰며 코인 포지션·현물 헤지·차익거래를 하지 않습니다.</p>'+table(['규칙','4년 수익','4년 DD','최근 수익','최근 DD'],base,'base-results')
 html+=f'<p>CD_INFO 주기간 {pct(main["return_pct"])}%·DD {main["max_drawdown_pct"]:.2f}%·Sharpe {number(main["sharpe"])}, 최근 {pct(recent["return_pct"])}%입니다. 주수익52.838713%·DD13.561952%, 최근수익4.628391% 등 사전기준을 유지했습니다. 더 유리한 대조·지연 조건으로 주규칙을 바꾸지 않습니다.</p><details><summary>사전 선정 관문 전체</summary>'+table(['고정 관문','결과'],gates,'selection-results')+'</details></section>'
 html+='<section><h2>새 정보와 해석의 범위</h2><p>D는 BTCUSD_PERP의 지난7일 정산율 합에서 같은 시계의 BTCUSDT 정산율 합을 뺀 값입니다. 단순연율365/7은 표현 단위이며 복리수익이 아닙니다. 코인 담보 롱의 담보가치·포지션이 함께 하락할 위험이 조건부 음의 정보를 주는지 반증합니다. 담보·청산·투자자 신원을 직접 관측하지 않았으며 계약 유동성·헤저 선호·펀딩 공식·USD/USDT 차이도 영향을 줄 수 있습니다. 같은 거래소여도 담보의 인과효과가 식별되는 것은 아닙니다.</p><p>INFO는 가격r7/r28·현재 USDT펀딩F·차이D, FUND는 D 제외, COIN은 가격과 코인펀딩만, PRICE는 가격만입니다. INFO는 D계수 음수·비용과 추정오차를 넘는 예측·FUND 대비 같은 방향의 증분을 모두 요구합니다. FUND/COIN은 자기 펀딩계수 음수, PRICE는 자기 비용·오차 기준을 씁니다. INV는 INFO 발동 방향만 반대, TREND는 기존 양방향 추세입니다.</p><p>104달력주·최소52행의 공통 유효 과거만 학습하며 1일 purge·무제약 회귀·달력1주 HAC를 적용했습니다. 실패하면 고정 signed 추세를 상속하고 위험만 일별 갱신합니다. 한 후보 실패를 부호·창·레버리지 조정으로 구제하지 않았습니다.</p></section>'
 html+='<section><h2>추가 예측력과 실제 발동</h2>'+table(['기간','모형','공통주','MSE','방향정확도%','마지막 계수 음수주','마지막 계수 중앙'],forecast,'forecast-results')
 html+=f'<p>공통 예측 주기간 {fc["main"]["0"]["n"]}주/{fc["main"]["0"]["coverage"]*100:.2f}%, 최근 {fc["recent"]["0"]["n"]}주/{fc["recent"]["0"]["coverage"]*100:.2f}%입니다. 마지막 계수는 INFO의 D, FUND의 F, COIN의 코인펀딩, PRICE의 r28로 서로 다른 경제량입니다. 예측오차 개선은 비용 후 계좌 성공을 뜻하지 않습니다.</p>'+table(['기간','규칙','발동주','발동일','추세유지일','피처무효일','모형무효일'],activity,'activity-results')+'<p>피처무효·모형무효 일수는 중복될 수 있습니다. 발동 없는 추세 상속을 새 정보 성과로 세지 않습니다.</p></section>'
 html+=f'<section><h2>원시 정산시각과 자료 누락</h2><p>공식 BTC 전용 공개 REST의 고정80개월·{source["funding_rows"]:,}건을 별도 Decimal로 재구성했습니다. 2020.01–07의 빈 배열7개, 내부8시간 관측 누락 {len(source["missing_internal_8h_buckets"])}개를 보존했습니다. 실제 지급 시각의 명목경계 대비 편차는 {source["actual_clock_offsets_ms"]["min"]}–{source["actual_clock_offsets_ms"]["max"]}ms입니다. 빈 markPrice는 정산율 결측으로 오인하지 않았습니다.</p><p>월요일00UTC 직전7일의 각 명목8시간 구간에 실제시각이 판단 이전인 정산율이 정확1개씩, 총21개 있어야 합니다. T나T+ms 정산을 미리 쓰지 않습니다. extra7 조건은 D와코인 정보만 늦추고 현재 USDT펀딩과 가격은 유지합니다. 결측은 보간하지 않습니다.</p><p>공식 July2022 ZIP은 checksum이 맞아도90행으로 마지막 하루3행이 빠졌고 REST는93행입니다. 겹치는90개 실제시각·율은 일치했습니다. 전체 연구는 사전지정 REST를 사용하며 ZIP과 합성하지 않았습니다. 현재조회본 일치는 당시 최초게시·실시간 실행을 입증하지 않습니다.</p></section>'
 html+='<section><h2>비용·펀딩·실행 지연</h2><p>선물 편도5bp수수료+1.5bp불리impact, 실제USDT펀딩×시간mark시가 대용. 기본1h 후집행·추가1h/24h, .001BTC·최소50USDT·감축예외, 목표명목≤1배. 코인펀딩은 정보일 뿐 이 원장에 이중 부과하지 않습니다. 호가·부분체결·과거규정·정확청산·운영비·세금 미복원.</p>'+table(['주규칙 조건','4년 수익%','최근 수익%'],stress,'stress-results')+'<details><summary>연도별 수익</summary>'+table(['규칙','기간','2022','2023','2024','2025','2026.01–08'],annual,'annual-results')+'</details><details><summary>가격손익·비용·펀딩</summary>'+table(['규칙','기간','가격손익USDT','비용USDT','펀딩USDT','연변동성%','Sharpe'],cost,'cost-results')+'</details><details><summary>주규칙 롱·숏 기여</summary>'+table(['기간','방향','가격손익USDT','비용USDT','펀딩USDT','순손익USDT'],side,'direction-results')+'</details><details><summary>수익차의 불확실성</summary><p>14일 원형블록2,000회95%구간(%/일). 모든7/14/28일 결과 보존, 반복탐색 편향을 해소한 OOS 아님.</p>'+table(['기간','규칙','대조','일수익차95%구간'],ci,'uncertainty-results')+'</details></section>'
 html+='<section><h2>모든72조건 보존</h2><details id="matrix"><summary>72계좌 전체 보기</summary>'+table(['규칙','기간','조건','수익%','DD%','연변동성%','보유구간','펀딩USDT'],[[r['strategy'],r['period'],r['scenario'],pct(r['return_pct']),f"{r['max_drawdown_pct']:.2f}",f"{r['realized_vol_pct']:.2f}",r['round_trips'],pct(r['funding'])] for r in rows],'all-accounts')+'</details></section>'
 html+=f'<section id="proof"><h2>독립 검산과 차단 재현</h2><p>사전5a49448→원자료·25합성검사·해시동결7c67acf 뒤 최초 계산. {v["raw_feature_weeks"]:,}피처주·{v["independent_model_fits"]:,}별도 정규방정식/HAC·{v["raw_daily_decisions"]:,}일판단·{v["independent_target_quantities"]:,}폐형식수량·{v["raw_mark_funding_events"]:,}펀딩·{v["daily_equities"]:,}일말자산·선정·{v["return_block_bootstrap_checks"]}구간을 검산했습니다. 계좌최대차 {v["max_numeric_error"]:.3g}USDT. 새 {rep["matched_files"]}파일 소켓차단 바이트 일치.</p><p>기존329시장/80개월 선물 원시 감사 영수증은 고정SHA로 재사용했고 무변경 전체감사나 옛 계좌 재실행은 하지 않았습니다. 최초2원응답은 경로·상태 갱신 오류 뒤 보존 재사용했으며 초기 요청시각은 별도 로그가 없어 현재빈티지 한계로 표시합니다. 규칙·수익 변경은 없습니다.</p></section>'
 html+='<section id="downloads"><h2>검증 자료</h2><div class="downloads"><a download href="downloads/btc-collateral-evidence.zip">72계좌·원자료·검산 ZIP ↓</a><a download href="downloads/btc-collateral-evidence.json">전체 수치·불확실성 JSON ↓</a><a download href="downloads/btc-collateral-summary.csv">72조건 CSV ↓</a><a download href="EXPERIMENT_BTC_COLLATERAL_20261004.md">성과 전 명세 ↓</a></div><p><a href="BTC_WEB_RESEARCH_20261002.md">원문 감사·실패 기록</a> · <a href="https://doi.org/10.5195/ledger.2024.325">담보·자료구조 원문</a> · <a href="https://elmwealth.com/perpetual-futures/">펀딩 기전 설명</a></p><p>ZIP은 새 원응답·피처·모형·72계좌·검산·재현해시를 포함합니다. 공통시장·과거영수증·공유모듈·의존성은 별도로 필요해 독립 실행환경은 아닙니다. 논문PDF는 재배포하지 않습니다.</p><p>누적 외부2,238조건계좌이지 독립전략2,238개가 아닙니다. 기존198계좌/273파일 보존, 채택0. 공개집계와 오프라인 가상검증만 수행했습니다.</p></section><footer>BUILD1004c1 · BTC-only · 실거래 없음</footer></main></body></html>'
 (DOC/'btc-collateral-research.html').write_text(html);p=DOC/'btc-web-research.html';old=p.read_text()
 if 'id="collateral-followup"' not in old:p.write_text(old.replace('<h1>','<p id="collateral-followup" class="boundary">새72순수선물계좌·외부2,238조건: <a href="btc-collateral-research.html">담보계약별 펀딩 추가정보 검증 ↗</a></p><h1>',1))
 files=['btc-collateral-research.html','btc-web-research.html','downloads/btc-collateral-evidence.zip','downloads/btc-collateral-evidence.json','downloads/btc-collateral-summary.csv','EXPERIMENT_BTC_COLLATERAL_20261004.md','BTC_WEB_RESEARCH_20261002.md'];o=ROOT/'runs/btc-collateral-report-20261004';o.mkdir(exist_ok=True);(o/'public-manifest.json').write_bytes(canonical({n:{'sha256':sha((DOC/n).read_bytes()),'bytes':(DOC/n).stat().st_size} for n in files}));print({'accounts':len(rows),'public_files':len(files),'zip_bytes':(DOWN/'btc-collateral-evidence.zip').stat().st_size,'selected':sel['passed']})
if __name__=='__main__':run()
