"""Publish only the independently verified MI72 experiment; no new calculations or old reruns."""
import csv,json,zipfile
from pathlib import Path
from build_btc_web_report import table,read
from btc_perp_bot.research.archive import canonical,sha
ROOT=Path(__file__).resolve().parents[1];DOC=ROOT/'docs';DOWN=DOC/'downloads';RUN=ROOT/'runs/btc-dollar-funding-20261004';INPUT=ROOT/'data/btc-dollar-funding-20261004';BUILD='1004d1'
def pct(x):return f'{x:+.2f}'
def number(x):return '자료 부족' if x is None else f'{x:.9g}'
def run():
 s=read(RUN/'summary.json');v=read(RUN/'verification.json');rep=read(RUN/'reproduction.json');sel=read(RUN/'selection.json');fc=read(RUN/'forecast-summary.json');unc=read(RUN/'uncertainty.json');diag=read(RUN/'diagnostics.json');act=read(RUN/'activity.json');source=read(INPUT/'independent-audit.json');assert len(s)==v['accounts']==72 and rep['all_bytes_equal'];names=('DF_INFO','DF_BANK','DF_GAP','DF_PRICE','DF_INV','DF_TREND');base=[];annual=[];cost=[];forecast=[];ci=[];rows=[];stress=[];side=[];activity=[]
 for n in names:
  a,b=[s[p+'-'+n+'-base']['metrics'] for p in ('main','recent')];base.append([n+(' · 기본' if n=='DF_INFO' else ' · 대조'),pct(a['return_pct']),f"{a['max_drawdown_pct']:.2f}",pct(b['return_pct']),f"{b['max_drawdown_pct']:.2f}"])
  for p in ('main','recent'):
   e=s[p+'-'+n+'-base'];m=e['metrics'];annual.append([n,p,*[pct(e['annual'][y]['return_pct']) if y in e['annual'] else '해당 없음' for y in ('2022','2023','2024','2025','2026')]]);cost.append([n,p,pct(m['gross_pnl']),f"{m['fees']+m['impact']:.2f}",pct(m['funding']),f"{m['realized_vol_pct']:.2f}",number(m['sharpe'])]);ac=act[p][n+'-base'];activity.append([p,n,ac['override_weeks'],ac['override_days'],ac['fallback_days'],ac['invalid_feature_days'],ac['model_missing_days']])
   if n in fc[p]['0']['models']:
    f=fc[p]['0']['models'][n];forecast.append([p,n,f['n'],number(f['mse']),number(None if f['sign_accuracy'] is None else f['sign_accuracy']*100),f['negative_last_beta_weeks'],number(f['median_last_beta'])])
   for ctrl in ('DF_BANK','DF_TREND'):
    u=unc[p+'-'+n]['vs_'+ctrl][1]['ci95'];ci.append([p,n,ctrl,f'{u[0]:+.5f} ~ {u[1]:+.5f}'])
 for p in ('main','recent'):
  for direction,z in diag[p+'-DF_INFO-base.json.gz']['long_short'].items():side.append([p,direction,pct(z['gross']),f"{z['fees']+z['impact']:.2f}",pct(z['funding']),pct(z['net'])])
 for c in ('base','cost_x2','delay1','delay24','risk10','data_delay7'):stress.append([c,*[pct(s[p+'-DF_INFO-'+c]['metrics']['return_pct']) for p in ('main','recent')]])
 for key,e in s.items():
  p,n,c=key.split('-');m=e['metrics'];rows.append({'strategy':n,'period':p,'scenario':c,**{k:m[k] for k in ('return_pct','max_drawdown_pct','realized_vol_pct','sharpe','round_trips','fees','impact','funding','mean_exposure')}})
 evidence={'build':BUILD,'account_rows':rows,'summary':s,'verification':v,'reproduction':rep,'selection':sel,'forecast_summary':fc,'uncertainty':unc,'diagnostics':diag,'activity':act,'source_audit':source,'scope':'External public SOFR-EFFR reference-rate difference conditions BTC-only perpetual exposure. No other-asset trades, structural funding-flow identification or live service. Current-vintage rates, delayed weekly information and repeated development history; not unused OOS or first-publication proof.'};(DOWN/'btc-dollar-funding-evidence.json').write_bytes(canonical(evidence))
 with (DOWN/'btc-dollar-funding-summary.csv').open('w',newline='') as f:w=csv.DictWriter(f,fieldnames=list(rows[0]));w.writeheader();w.writerows(rows)
 with zipfile.ZipFile(DOWN/'btc-dollar-funding-evidence.zip','w',compression=zipfile.ZIP_STORED) as z:
  files=[(p,'run/'+p.name) for p in sorted(RUN.iterdir()) if p.is_file()]
  for n in ('collect_btc_dollar_funding_data.py','audit_btc_dollar_funding_data.py','btc_dollar_funding_study.py','test_btc_dollar_funding_study.py','verify_btc_dollar_funding_study.py','reproduce_btc_dollar_funding_study.py','btc_target_ledger.py','btc_continuity_study.py','btc_persistence_study.py'):files.append((ROOT/'tools'/n,'source/'+n))
  for n in ('rates.json.gz','prepare-audit.json','independent-audit.json'):files.append((INPUT/n,'input/btc-dollar-funding-20261004/'+n))
  files += [(p,'input/btc-dollar-funding-20261004/'+str(p.relative_to(INPUT))) for folder in ('raw','failures') for p in sorted((INPUT/folder).glob('*')) if p.is_file()]
  files.append((DOC/'EXPERIMENT_BTC_DOLLAR_FUNDING_20261004.md','source/EXPERIMENT_BTC_DOLLAR_FUNDING_20261004.md'))
  for p,n in files:z.writestr(zipfile.ZipInfo(n,(2026,10,4,0,0,0)),p.read_bytes())
  z.writestr(zipfile.ZipInfo('DATA-SOURCES.txt',(2026,10,4,0,0,0)),'''72 BTCUSDT perpetual-only simulated accounts. SOFR and EFFR public macro reference rates are information only; no bonds, forex, rate trades or repo borrowing. Primary asks whether secured-minus-bank cash financing rate adds negative BTC return information beyond bank rate, current BTC funding and price. Effective-date weeks end at least seven calendar days before Monday decisions; additional7d sensitivity. Exact date sets with 3-5 observations required, no intersection repair or forward filling. Percent annual EFFR and basis-point difference are distinct units, not realized investment returns.
162 official NYFed monthly raw responses Dec2019-Aug2026, metadata, exact Decimal input receipts and 4 independent same-provider probe comparisons included. Ten EFFR-only dates, one unresolved footnote row in each series preserved; strict invalidation, no performance-driven cleaning. Original publication/vintage and emergency revisions not fully proven. Separate quarterly revised statistics not used. All new simulations/verifications included; prior market/pressure audit receipts, shared modules/repo layout/dependencies remain separately needed. NOT a standalone environment. No PDFs, secrets or individual records. Motivation, not reproduction or alpha proof: Augustin/Rubtsov/Shin https://doi.org/10.1287/mnsc.2023.4900 .
''')
 main=s['main-DF_INFO-base']['metrics'];recent=s['recent-DF_INFO-base']['metrics'];status='기각' if not sel['passed'] else '개발 관문 통과 · 전진 검증 전';gates=[[k,'통과' if val else '미달'] for part in ('checks','information_increment') for k,val in sel[part].items()]
 html='''<!doctype html><html lang="ko"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta http-equiv="Content-Security-Policy" content="default-src 'self';script-src 'none';style-src 'self';img-src 'self' data:;connect-src 'none';object-src 'none';base-uri 'none';form-action 'none'"><title>BTC 외부 달러 조달 압력 검증</title><link rel="icon" href="assets/icon.svg"><link rel="stylesheet" href="assets/btc-continuation.css"></head><body><a class="skip" href="#results">결과로 이동</a><header><a href="./">BTC RESEARCH</a><nav><a href="btc-web-research.html">전체 연구 기록</a><a href="#downloads">검증 자료</a></nav></header><main><p class="eyebrow">BTC PERPETUAL ONLY · BUILD1004d1</p><h1>외부 달러 조달 압력이<br>BTC 방향을 알려주는가?</h1><p class="lead">담보부 현금조달과 은행 조달금리의 차이가 기존 은행금리·BTC 펀딩·가격을 넘어 추가 정보를 주는지 검증했습니다. 모든 대조와 실패 조건을 보존합니다.</p>'''
 html+=f'<div class="facts"><article><b>72</b><span>순수 BTC 선물 조건계좌</span></article><article><b>{status}</b><span>DF_INFO 기본 후보</span></article><article><b>{rep["matched_files"]}</b><span>소켓차단 바이트 일치</span></article></div><p class="boundary">반복해서 본 2022–2025 및 2026.01–08 개발 이력입니다. 미사용 OOS나 미래 수익 보장이 아닙니다. 검산과 채택은 별개이며, 실거래·상시 모의서비스는 시작하지 않았습니다.</p>'
 html+='<section id="results"><h2>기본과 모든 대조군</h2><p>각1,000USDT, 수익·낙폭은 %. BTCUSDT 무기한선물만 가상 체결했습니다. SOFR/EFFR는 거시 입력뿐이며 채권·금리·외환 거래와 repo 차입은 없습니다.</p>'+table(['규칙','4년 수익','4년 DD','최근 수익','최근 DD'],base,'base-results')
 html+=f'<p>DF_INFO 주기간 {pct(main["return_pct"])}%·DD {main["max_drawdown_pct"]:.2f}%·Sharpe {number(main["sharpe"])}, 최근 {pct(recent["return_pct"])}%입니다. 주수익52.838713%·DD13.561952%, 최근수익4.628391% 등 기존 관문을 유지했습니다. 대조군이나 지연 조건의 수익을 보고 주규칙을 바꾸지 않았습니다.</p><details><summary>사전 선정 관문 전체</summary>'+table(['고정 관문','결과'],gates,'selection-results')+'</details></section>'
 html+='<section><h2>외부 자금조달과 BTC 자체 펀딩을 분리</h2><p>M은 같은 날짜 SOFR−EFFR 차이의 주평균(연율bp), E는 EFFR의 주평균(연율%)입니다. 중개기관의 현금조달 마찰이 위험수용능력을 줄일 수 있다는 자체 음의 정보 가설입니다. 실제 BTC 대출·담보·투자자 자금을 관측하지 않았고, repo 담보 수급·분기말 규제·금리정책도 차이를 설명할 수 있습니다. 인과적인 조달 충격이나 정책 surprise라고 부르지 않습니다.</p><p>INFO는 r7/r28·현재BTC펀딩F·E·M, BANK는 M 제외, GAP은 E 제외, PRICE는 E/M 제외입니다. PRICE에도 F를 통제합니다. INFO는 M계수 음수·비용과 추정오차 초과·BANK 대비 같은 방향의 증분을 모두 요구합니다. BANK는 E계수 음수, GAP은 M계수 음수, PRICE는 자기 비용·오차 기준입니다. INV는 같은 INFO 발동 방향만 반대, TREND는 기존 signed 추세입니다.</p><p>동일104달력주·최소52행, 1일 purge·무제약 회귀·달력1주 HAC를 고정했습니다. 조건 미달은 signed 추세 상속, 위험은 일별 갱신합니다. 부호나 학습창을 사후 수정하지 않았습니다.</p></section>'
 html+='<section><h2>추가 예측력과 실제 발동</h2>'+table(['기간','모형','공통주','MSE','방향정확도%','마지막 계수 음수주','마지막 계수 중앙'],forecast,'forecast-results')
 html+=f'<p>공통 예측 주기간 {fc["main"]["0"]["n"]}주/{fc["main"]["0"]["coverage"]*100:.2f}%, 최근 {fc["recent"]["0"]["n"]}주/{fc["recent"]["0"]["coverage"]*100:.2f}%입니다. 마지막 계수는 INFO/GAP의 M, BANK의 E, PRICE의 F로 경제량이 다릅니다. 예측오차와 비용 후 계좌를 별도 관문으로 평가합니다.</p>'+table(['기간','규칙','발동주','발동일','추세유지일','피처무효일','모형무효일'],activity,'activity-results')+'<p>피처·모형 무효 일수는 중복됩니다. extra7 최근 INFO의 양수 수익은 발동0주의 추세 상속이며 새 정보 성과가 아닙니다.</p></section>'
 html+=f'<section><h2>관측일과 발표·수정 시각</h2><p>공식 고정162월 응답, SOFR {source["rows"]["SOFR"]:,}일·EFFR {source["rows"]["EFFR"]:,}일을 독립 Decimal로 재구성했습니다. SOFR-only {len(source["SOFR_only_dates"])}일/EFFR-only {len(source["EFFR_only_dates"])}일, 불명 footnote SOFR {source["invalid_rows"]["SOFR"]}행/EFFR {source["invalid_rows"]["EFFR"]}행을 보존했습니다. 4개 소량 probe의22행은 부가필드까지 일치했습니다.</p><p>SOFR 약08ET, EFFR 약09ET의 다음 영업일 공표와 당일14:30ET 정정을 구분합니다. 금리 관측 주가 끝난 뒤 최소7일을 기다리고 추가7일을 검증합니다. 양쪽 날짜집합이 정확히 같고3–5개여야 유효하며, 휴일 차이를 교집합·보간·전일 값으로 구제하지 않습니다. extra7은 E/M만 늦추고 현재 BTC가격·실제ms 기준 settled funding은 유지합니다.</p><p>분기 후 수정 통계는 수집하지 않았습니다. 그래도 현재 API와7일 여유가 전체 과거 최초공표·비상정정 부재를 증명하지는 않습니다. 원문·원응답의 불명 footnote는 사전 규칙대로 무효 처리했습니다. 동결명세 요약의 무효행0 오기는 각1행으로 문서만 정정했으며 실제 입력·마스크·성과는 처음부터 각1행 무효였습니다.</p></section>'
 html+='<section><h2>비용·펀딩·실행 지연</h2><p>선물 편도5bp수수료+1.5bp불리impact, 실제 BTC펀딩×시간mark시가 대용. 기본1h 후집행·추가1h/24h, 수량 .001BTC·최소50USDT·감축예외, 목표명목≤1배. repo 거래·차입이 없어 그 금리를 원장에 부과하지 않습니다. 호가·부분체결·과거규정·정확청산·운영비·세금 미복원.</p>'+table(['주규칙 조건','4년 수익%','최근 수익%'],stress,'stress-results')+'<details><summary>연도별 수익</summary>'+table(['규칙','기간','2022','2023','2024','2025','2026.01–08'],annual,'annual-results')+'</details><details><summary>가격손익·비용·펀딩</summary>'+table(['규칙','기간','가격손익USDT','비용USDT','펀딩USDT','연변동성%','Sharpe'],cost,'cost-results')+'</details><details><summary>주규칙 롱·숏 기여</summary>'+table(['기간','방향','가격손익USDT','비용USDT','펀딩USDT','순손익USDT'],side,'direction-results')+'</details><details><summary>수익차의 불확실성</summary><p>14일 원형블록2,000회95%구간(%/일). 전체7/14/28일 보존, 반복탐색 편향을 해소한 OOS는 아닙니다.</p>'+table(['기간','규칙','대조','일수익차95%구간'],ci,'uncertainty-results')+'</details></section>'
 html+='<section><h2>모든72조건 보존</h2><details id="matrix"><summary>72계좌 전체 보기</summary>'+table(['규칙','기간','조건','수익%','DD%','연변동성%','보유구간','펀딩USDT'],[[r['strategy'],r['period'],r['scenario'],pct(r['return_pct']),f"{r['max_drawdown_pct']:.2f}",f"{r['realized_vol_pct']:.2f}",r['round_trips'],pct(r['funding'])] for r in rows],'all-accounts')+'</details></section>'
 html+=f'<section id="proof"><h2>독립 검산과 차단 재현</h2><p>사전bf1ca9f→원시 감사·25합성검사·해시동결30286cc 뒤 첫 성과 계산. {v["raw_feature_weeks"]:,}피처주·{v["independent_model_fits"]:,}별도 정규방정식/HAC·{v["raw_daily_decisions"]:,}일판단·{v["independent_target_quantities"]:,}폐형식수량·{v["raw_mark_funding_events"]:,}펀딩·{v["daily_equities"]:,}일말·선정·{v["return_block_bootstrap_checks"]}구간을 검산했습니다. 계좌최대차 {v["max_numeric_error"]:.3g}USDT. 새 {rep["matched_files"]}파일 소켓차단 바이트 일치.</p><p>기존 시장/선물 원시 감사 영수증은 고정SHA로 재사용했습니다. 옛 전체 자료나 완료 계좌를 다시 실행하지 않았습니다. 회계 검산이 독립 경제 증거나 전략 성공을 뜻하지 않습니다.</p></section>'
 html+='<section id="downloads"><h2>검증 자료</h2><div class="downloads"><a download href="downloads/btc-dollar-funding-evidence.zip">72계좌·원자료·검산 ZIP ↓</a><a download href="downloads/btc-dollar-funding-evidence.json">전체 수치·불확실성 JSON ↓</a><a download href="downloads/btc-dollar-funding-summary.csv">72조건 CSV ↓</a><a download href="EXPERIMENT_BTC_DOLLAR_FUNDING_20261004.md">성과 전 명세 ↓</a></div><p><a href="BTC_WEB_RESEARCH_20261002.md">원문 감사·실패 기록</a> · <a href="https://www.newyorkfed.org/markets/reference-rates/additional-information-about-reference-rates">공식 발표·수정 정책</a> · <a href="https://doi.org/10.1287/mnsc.2023.4900">BTC 자금제약 기전 원문</a></p><p>ZIP은 새 원응답·피처·모형·72계좌·검산·재현해시를 포함합니다. 공통시장·과거영수증·공유모듈·의존성은 별도로 필요해 독립 실행환경은 아닙니다. 논문PDF는 재배포하지 않습니다.</p><p>누적 외부2,310조건계좌이지 독립전략2,310개가 아닙니다. 기존198계좌/273파일 보존, 채택0. 공개집계와 오프라인 가상검증만 수행했습니다.</p></section><footer>BUILD1004d1 · BTC-only · 실거래 없음</footer></main></body></html>'
 (DOC/'btc-dollar-funding-research.html').write_text(html);p=DOC/'btc-web-research.html';old=p.read_text()
 if 'id="dollar-funding-followup"' not in old:p.write_text(old.replace('<h1>','<p id="dollar-funding-followup" class="boundary">새72순수선물계좌·외부2,310조건: <a href="btc-dollar-funding-research.html">외부 달러 조달 압력 검증 ↗</a></p><h1>',1))
 files=['btc-dollar-funding-research.html','btc-web-research.html','downloads/btc-dollar-funding-evidence.zip','downloads/btc-dollar-funding-evidence.json','downloads/btc-dollar-funding-summary.csv','EXPERIMENT_BTC_DOLLAR_FUNDING_20261004.md','BTC_WEB_RESEARCH_20261002.md'];o=ROOT/'runs/btc-dollar-funding-report-20261004';o.mkdir(exist_ok=True);(o/'public-manifest.json').write_bytes(canonical({n:{'sha256':sha((DOC/n).read_bytes()),'bytes':(DOC/n).stat().st_size} for n in files}));print({'accounts':len(rows),'public_files':len(files),'zip_bytes':(DOWN/'btc-dollar-funding-evidence.zip').stat().st_size,'selected':sel['passed']})
if __name__=='__main__':run()
