"""Publish only the independently verified UV72 experiment; no new calculations or old reruns."""
import csv,json,zipfile
from pathlib import Path
from build_btc_web_report import table,read
from btc_perp_bot.research.archive import canonical,sha
ROOT=Path(__file__).resolve().parents[1];DOC=ROOT/'docs';DOWN=DOC/'downloads';RUN=ROOT/'runs/btc-upside-20261004';INPUT=ROOT/'data/btc-upside-20261004';BUILD='1004u1'
def pct(x):return f'{x:+.2f}'
def number(x):return '자료 부족' if x is None else f'{x:.9g}'
def run():
 s=read(RUN/'summary.json');v=read(RUN/'verification.json');rep=read(RUN/'reproduction.json');sel=read(RUN/'selection.json');fc=read(RUN/'forecast-summary.json');unc=read(RUN/'uncertainty.json');diag=read(RUN/'diagnostics.json');act=read(RUN/'activity.json');source=read(INPUT/'input-audit.json');assert len(s)==v['accounts']==72 and rep['all_bytes_equal'];names=('UV_INFO','UV_COUNT','UV_SEMI','UV_PRICE','UV_INV','UV_TREND');base=[];annual=[];cost=[];forecast=[];ci=[];rows=[];stress=[];side=[];activity=[]
 for n in names:
  a,b=[s[p+'-'+n+'-base']['metrics'] for p in ('main','recent')];base.append([n+(' · 기본' if n=='UV_INFO' else ' · 대조'),pct(a['return_pct']),f"{a['max_drawdown_pct']:.2f}",pct(b['return_pct']),f"{b['max_drawdown_pct']:.2f}"])
  for p in ('main','recent'):
   e=s[p+'-'+n+'-base'];m=e['metrics'];annual.append([n,p,*[pct(e['annual'][y]['return_pct']) if y in e['annual'] else '해당 없음' for y in ('2022','2023','2024','2025','2026')]]);cost.append([n,p,pct(m['gross_pnl']),f"{m['fees']+m['impact']:.2f}",pct(m['funding']),f"{m['realized_vol_pct']:.2f}",number(m['sharpe'])]);ac=act[p][n+'-base'];activity.append([p,n,ac['override_weeks'],ac['override_days'],ac['fallback_days'],ac['invalid_feature_days'],ac['model_missing_days']])
   if n in fc[p]['0']['models']:
    f=fc[p]['0']['models'][n];forecast.append([p,n,f['n'],number(f['mse']),number(None if f['sign_accuracy'] is None else f['sign_accuracy']*100),f['positive_last_beta_weeks'],number(f['median_last_beta'])])
   for ctrl in ('UV_COUNT','UV_TREND'):
    u=unc[p+'-'+n]['vs_'+ctrl][1]['ci95'];ci.append([p,n,ctrl,f'{u[0]:+.5f} ~ {u[1]:+.5f}'])
 for p in ('main','recent'):
  for direction,z in diag[p+'-UV_INFO-base.json.gz']['long_short'].items():side.append([p,direction,pct(z['gross']),f"{z['fees']+z['impact']:.2f}",pct(z['funding']),pct(z['net'])])
 for c in ('base','cost_x2','delay1','delay24','risk10','data_delay7'):stress.append([c,*[pct(s[p+'-UV_INFO-'+c]['metrics']['return_pct']) for p in ('main','recent')]])
 for key,e in s.items():
  p,n,c=key.split('-');m=e['metrics'];rows.append({'strategy':n,'period':p,'scenario':c,**{k:m[k] for k in ('return_pct','max_drawdown_pct','realized_vol_pct','sharpe','round_trips','fees','impact','funding','mean_exposure')}})
 evidence={'build':BUILD,'account_rows':rows,'summary':s,'verification':v,'reproduction':rep,'selection':sel,'forecast_summary':fc,'uncertainty':unc,'diagnostics':diag,'activity':act,'source_audit':source,'scope':'BTC signed semivariance composition is price-state information only; all executions BTCUSDT perpetual. No investor/news identity or future-quantile regime. Current archive and repeated development history; no strategy adopted or live trading service.'};(DOWN/'btc-upside-evidence.json').write_bytes(canonical(evidence))
 with (DOWN/'btc-upside-summary.csv').open('w',newline='') as f:w=csv.DictWriter(f,fieldnames=list(rows[0]));w.writeheader();w.writerows(rows)
 with zipfile.ZipFile(DOWN/'btc-upside-evidence.zip','w',compression=zipfile.ZIP_STORED) as z:
  files=[(p,'run/'+p.name) for p in sorted(RUN.iterdir()) if p.is_file()]
  for n in ('btc_upside_study.py','test_btc_upside_study.py','verify_btc_upside_study.py','reproduce_btc_upside_study.py','btc_target_ledger.py','btc_continuity_study.py','btc_persistence_study.py'):files.append((ROOT/'tools'/n,'source/'+n))
  files.append((INPUT/'input-audit.json','input/btc-upside-20261004/input-audit.json'))
  files.append((DOC/'EXPERIMENT_BTC_UPSIDE_20261004.md','source/EXPERIMENT_BTC_UPSIDE_20261004.md'))
  for p,n in files:z.writestr(zipfile.ZipInfo(n,(2026,10,4,0,0,0)),p.read_bytes())
  z.writestr(zipfile.ZipInfo('DATA-SOURCES.txt',(2026,10,4,0,0,0)),'''72 BTCUSDT perpetual-only simulated accounts. New information is upper/lower hourly squared-return composition over a fixed seven-day window, conditional on price returns, total realized variance, sign counts and settled funding. Exact169completed positive-volume hourly closes/168returns; missing invalidates, no compressed time/forward-fill. Extra7day scenario delays only the variance/count information. Original papers use different frequencies/models and do not establish our costed directional alpha; this is our own conditional test, not replication. No future target quantile or full-sample tail threshold defines a current regime.
New features/plans/forecasts/accounts/independent checks and source qualification receipt included. Previously audited80monthly BTC perp raw-hour field strings (input SHA b7bcc90d73a29cf1f2d84dcd752025a6034d356ab337d7ce48eab82f09869d5f), common market329ZIP source, older receipts/shared modules/dependencies remain separate. Existing pressure input is not republished or recomputed here. This ZIP is NOT a standalone environment. No paper PDFs, personal records, credentials, financial-account access or live-order service.
References https://doi.org/10.2139/ssrn.7226305 (abstract only); https://doi.org/10.3390/jrfm13120312 (future volatility, not directional strategy). Official raw source https://data.binance.vision/ .
''')
 main=s['main-UV_INFO-base']['metrics'];recent=s['recent-UV_INFO-base']['metrics'];status='기각' if not sel['passed'] else '개발 관문 통과 · 전진 검증 전';gates=[[k,'통과' if val else '미달'] for part in ('checks','information_increment') for k,val in sel[part].items()]
 html='''<!doctype html><html lang="ko"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta http-equiv="Content-Security-Policy" content="default-src 'self';script-src 'none';style-src 'self';img-src 'self' data:;connect-src 'none';object-src 'none';base-uri 'none';form-action 'none'"><title>BTC 상방 분산 추가정보 검증</title><link rel="icon" href="assets/icon.svg"><link rel="stylesheet" href="assets/btc-continuation.css"></head><body><a class="skip" href="#results">결과로 이동</a><header><a href="./">BTC RESEARCH</a><nav><a href="btc-web-research.html">전체 연구 기록</a><a href="#downloads">검증 자료</a></nav></header><main><p class="eyebrow">BTC PERPETUAL ONLY · BUILD1004u1</p><h1>큰 움직임의 방향은<br>다음 주 수익의 정보인가?</h1><p class="lead">상승 쪽의 큰 움직임이 가격 추세·총위험·상승 횟수·이미 정산된 펀딩을 넘어 다음 주 방향정보를 주는지 검증했습니다. 주규칙과 모든 대조군·실패 조건을 함께 공개합니다.</p>'''
 html+=f'<div class="facts"><article><b>72</b><span>순수 BTC 선물 조건계좌</span></article><article><b>{status}</b><span>UV_INFO 기본 후보</span></article><article><b>{rep["matched_files"]}</b><span>소켓차단 바이트 일치</span></article></div><p class="boundary">2022–2025 및 2026.01–08은 반복해서 본 개발 이력입니다. 새 미사용 OOS나 미래 수익 보장이 아닙니다. 검산 통과와 전략 채택은 별개이며 실거래·상시 모의서비스는 시작하지 않았습니다.</p>'
 html+='<section id="results"><h2>기본과 모든 대조군</h2><p>각1,000USDT, 수익·낙폭은 %. 모든 체결은 BTCUSDT 무기한선물입니다. 상·하방 분산은 정보로만 쓰며 현물 매매·옵션·추가 차입은 없습니다.</p>'+table(['규칙','4년 수익','4년 DD','최근 수익','최근 DD'],base,'base-results')
 html+=f'<p>UV_INFO 주기간 {pct(main["return_pct"])}%·DD {main["max_drawdown_pct"]:.2f}%·Sharpe {number(main["sharpe"])}, 최근 {pct(recent["return_pct"])}%입니다. 주수익52.838713%·DD13.561952%, 최근수익4.628391% 등 사전기준을 유지했습니다. INV나 다른 대조군이 더 좋아도 주규칙으로 바꾸지 않습니다.</p><details><summary>사전 선정 관문 전체</summary>'+table(['고정 관문','결과'],gates,'selection-results')+'</details></section>'
 html+='''<section><h2>같은 수익·총위험·횟수, 다른 큰 움직임</h2><p>7일의168개 완료 시간수익을 양수·음수로 나눠 제곱합을 구합니다. A=(상방분산−하방분산)/총분산, Q=(상승시간수−하락시간수)/168입니다. 총수익과 총분산·부호횟수가 같아도 A는 다를 수 있습니다. 큰 상승 충격이 랠리의 추가정보를 줄 수 있다는 가설이지, 원인을 가진 뉴스나 정보거래자를 관측한 것은 아닙니다.</p><p>INFO는7/28일 수익·settled펀딩·log총RV·Q·A, COUNT는 A 제외, SEMI는 Q 제외, PRICE는 둘을 제외합니다. 모든 모형은 같은 과거104달력주·최소52행의 완료된 목표를 사용합니다. INFO는 A계수 양수, 비용·추정오차 초과, COUNT 대비 같은 방향의 추가정보가 있을 때만 발동합니다. COUNT/SEMI는 마지막 계수 양수와 자기 비용·오차 관문, PRICE는 비용·오차 관문을 적용합니다.</p><p>INV는 INFO의 발동 사건만 반대, TREND는 기존 양방향 추세입니다. 실패하면 고정 추세를 유지합니다. 미래 변동성의 사후 quantile을 현재 시장상태로 삼거나, 전체표본 꼬리문턱·최적창·대조군을 골라 성공으로 처리하지 않습니다.</p></section>'''
 html+='<section><h2>추가 예측력과 실제 발동</h2>'+table(['기간','모형','공통주','MSE','방향정확도%','마지막 계수 양수주','마지막 계수 중앙'],forecast,'forecast-results')
 html+=f'<p>공통 예측 주기간 {fc["main"]["0"]["n"]}주/coverage {fc["main"]["0"]["coverage"]*100:.2f}%, 최근 {fc["recent"]["0"]["n"]}주/{fc["recent"]["0"]["coverage"]*100:.2f}%입니다. 마지막 계수는 INFO/SEMI의 A, COUNT의 Q, PRICE의 log총RV로 서로 다른 경제량입니다. 예측오차와 실제 비용 후 계좌 관문을 별도로 판단합니다.</p>'+table(['기간','규칙','발동주','발동일','추세유지일','피처무효일','모형무효일'],activity,'activity-results')+'<p>피처무효와 모형무효 일수는 중복될 수 있어 합산한 탈락일이 아닙니다. 새 정보가 작동하지 않고 추세만 상속한 경우를 성공으로 처리하지 않습니다.</p></section>'
 html+=f'<section><h2>완료된 시간 가격만 사용했습니다</h2><p>이전에 독립검산한 공식80개월 BTC 선물 원시필드의 {source["hour_rows"]:,}시간 중 새 가격시계·양수거래량 조건에 {source["qualified_hours"]:,}시간이 유효하고 {len(source["invalid_hours"])}시간이 무효입니다. 기존 전체 ZIP를 재감사하지 않고 고정 SHA 영수증을 재사용했습니다.</p><p>월요일00UTC마다 직전7일의169개 정확한 시간경계 완료 종가가 모두 있어야168개 수익을 만듭니다. 시작경계나 중간 한 시간이라도 거래량0·결측·미완료면 그 주 위험정보는 무효입니다. 시간압축·ffill·epsilon분산 대체는 없습니다. 추가7일 조건은 A/Q/RV만 늦추며 가격통제와 실제ms 기준 이미 정산된21개 펀딩은 현재시계를 유지합니다.</p><p>1h/7일 분해는 원문의5분·다른 시계/모형을 복제한 것이 아닌 자체 고정 규칙입니다. 현재 아카이브·checksum·독립 검산은 최초 게시 빈티지나 실제 체결가능성을 증명하지 않습니다.</p></section>'
 html+='<section><h2>비용·펀딩·실행 지연</h2><p>선물 편도5bp수수료+1.5bp 불리한 impact, 실제 펀딩×시간 mark시가 대용. 기본1h 후집행·추가1h/24h지연, 수량0.001BTC·최소50USDT·감축예외, 총목표명목≤1배. 호가·부분체결·역사규정·정확청산·운영비·세금은 미복원입니다. 가격 위험 구성으로 실제 거래비용이나 펀딩을 낮춰 계산하지 않았습니다.</p>'+table(['주규칙 조건','4년 수익%','최근 수익%'],stress,'stress-results')+'<details><summary>연도별 수익</summary>'+table(['규칙','기간','2022','2023','2024','2025','2026.01–08'],annual,'annual-results')+'</details><details><summary>가격손익·비용·펀딩</summary><p>금액USDT. 선물 롱에도 펀딩을 적용했습니다.</p>'+table(['규칙','기간','가격손익','비용','펀딩','연변동성%','Sharpe'],cost,'cost-results')+'</details><details><summary>주규칙 롱·숏 기여</summary><p>금액USDT, 독립 원장 기준.</p>'+table(['기간','방향','가격손익','비용','펀딩','순손익'],side,'direction-results')+'</details><details><summary>수익차의 불확실성</summary><p>14일 원형블록2,000회95%구간(%/일), 전체7/14/28일 결과는 다운로드에 보존했습니다. 반복탐색 편향을 해소한 OOS는 아닙니다.</p>'+table(['기간','규칙','대조','일수익차95%구간'],ci,'uncertainty-results')+'</details></section>'
 html+='<section><h2>모든72조건 보존</h2><details id="matrix"><summary>72계좌 전체 보기</summary>'+table(['규칙','기간','조건','수익%','DD%','연변동성%','보유구간','펀딩USDT'],[[r['strategy'],r['period'],r['scenario'],pct(r['return_pct']),f"{r['max_drawdown_pct']:.2f}",f"{r['realized_vol_pct']:.2f}",r['round_trips'],pct(r['funding'])] for r in rows],'all-accounts')+'</details></section>'
 html+=f'<section id="proof"><h2>독립 검산과 차단 재현</h2><p>사전명세861cf94→입력 동결·22합성검사 구현bec2cb3 뒤 최초 성과계산 순서입니다. 기존 원시 시간행에서 새 부호별 분산을 Decimal로 독립 재구성해, {v["raw_feature_weeks"]:,}피처주·{v["independent_model_fits"]:,}정규방정식/HAC·{v["raw_daily_decisions"]:,}일판단·{v["independent_target_quantities"]:,}폐형식수량·{v["raw_mark_funding_events"]:,}펀딩·{v["daily_equities"]:,}일말자산·선정·{v["return_block_bootstrap_checks"]}구간을 검산했습니다. 계좌최대차 {v["max_numeric_error"]:.3g}USDT. 새 {rep["matched_files"]}파일은 소켓차단에서 바이트 일치했습니다.</p><p>기존329시장ZIP 및80개월 선물 원자료는 고정SHA 영수증을 재사용했으며 무변경 전체 감사·옛 계좌 재실행은 하지 않았습니다. 부호별 위험 구성이 일치해도 뉴스의 원인·미래 시장상태·실거래 유효성이 확인되는 것은 아닙니다.</p></section>'
 html+='''<section id="downloads"><h2>검증 자료</h2><div class="downloads"><a download href="downloads/btc-upside-evidence.zip">72계좌·피처·검산 ZIP ↓</a><a download href="downloads/btc-upside-evidence.json">전체 수치·불확실성 JSON ↓</a><a download href="downloads/btc-upside-summary.csv">72조건 CSV ↓</a><a download href="EXPERIMENT_BTC_UPSIDE_20261004.md">성과 전 명세 ↓</a></div><p><a href="BTC_WEB_RESEARCH_20261002.md">원문 감사·실패 기록</a> · <a href="https://doi.org/10.2139/ssrn.7226305">경제 질문의 동기 논문</a> · <a href="https://www.econstor.eu/handle/10419/239398">상·하방 변동성 공개 원문</a></p><p>ZIP은 새 피처·모형·72계좌·검산·재현해시를 포함합니다. 공통시장·과거영수증·공유모듈·의존성은 별도로 필요해 독립 실행환경은 아닙니다. 논문PDF는 재배포하지 않습니다.</p><p>누적 외부2,022조건계좌이며 독립전략2,022개가 아닙니다. 기존198계좌/273파일을 보존했고 채택0입니다. 공개자료와 오프라인 가상검증만 수행했습니다.</p></section><footer>BUILD1004u1 · BTC-only · 실거래 없음</footer></main></body></html>'''
 (DOC/'btc-upside-research.html').write_text(html);p=DOC/'btc-web-research.html';old=p.read_text()
 if 'id="upside-followup"' not in old:p.write_text(old.replace('<h1>','<p id="upside-followup" class="boundary">새72순수선물계좌·외부2,022조건: <a href="btc-upside-research.html">상방 분산의 추가정보 검증 ↗</a></p><h1>',1))
 files=['btc-upside-research.html','btc-web-research.html','downloads/btc-upside-evidence.zip','downloads/btc-upside-evidence.json','downloads/btc-upside-summary.csv','EXPERIMENT_BTC_UPSIDE_20261004.md','BTC_WEB_RESEARCH_20261002.md'];o=ROOT/'runs/btc-upside-report-20261004';o.mkdir(exist_ok=True);(o/'public-manifest.json').write_bytes(canonical({n:{'sha256':sha((DOC/n).read_bytes()),'bytes':(DOC/n).stat().st_size} for n in files}));print({'accounts':len(rows),'public_files':len(files),'zip_bytes':(DOWN/'btc-upside-evidence.zip').stat().st_size,'selected':sel['passed']})
if __name__=='__main__':run()
