"""Static report of verified new BTC web-grounded research; no old-study reruns."""
import csv,gzip,html,io,json,zipfile
from pathlib import Path
from btc_perp_bot.research.archive import canonical,sha
ROOT=Path(__file__).resolve().parents[1];DOC=ROOT/'docs';D=DOC/'downloads';esc=html.escape
GROUPS={'session':('동일 세션 반전','btc-session-20261002'),'flow':('가격통제 체결압력','btc-flow-20261002')}
def read(p):return json.loads(gzip.decompress(p.read_bytes())) if p.suffix=='.gz' else json.loads(p.read_text())
def table(head,rows,ident):return '<div class="scroll" role="region" tabindex="0" aria-label="'+esc(ident)+'"><table id="'+ident+'"><thead><tr>'+''.join('<th scope="col">'+esc(h)+'</th>' for h in head)+'</tr></thead><tbody>'+''.join('<tr>'+''.join('<td>'+esc(str(c))+'</td>' for c in row)+'</tr>' for row in rows)+'</tbody></table></div>'
def run():
 allrows=[];base=[];proof={};unc=[];annual=[];sides=[];public=[];links=[];full={}
 for key,(label,directory) in GROUPS.items():
  source=ROOT/'runs'/directory;v=read(source/'verification.json');r=read(source/'reproduction.json');assert r['all_bytes_equal'];summary=read(source/'summary.json');u=read(source/'uncertainty.json');selection=read(source/'selection.json');full[key]={'summary':summary,'uncertainty':u,'selection':selection,'verification':v,'reproduction':r};proof[key]={'v':v,'r':r};primary=selection['primary'];assert not selection['passed']
  for name,m in summary.items():
   period,family,scenario=name.split('-');row={'group':key,'strategy':family,'period':period,'scenario':scenario,**{k:m[k] for k in ('return_pct','cagr_pct','dd_pct','realized_vol_pct','sharpe','round_trips','fees','impact','funding','gross','mean_exposure','max_exposure','margin_breach_bars')}};allrows.append(row)
   if scenario=='base':
    if period=='main':
     b=summary['recent-'+family+'-base'];base.append([family+(' · 기본' if family==primary else ' · 대조'),f"{m['return_pct']:+.2f}",f"{m['dd_pct']:.2f}",f"{b['return_pct']:+.2f}",f"{b['dd_pct']:.2f}",f"{m['realized_vol_pct']:.2f} / {b['realized_vol_pct']:.2f}",f"{m['round_trips']} / {b['round_trips']}"])
    annual.append([family,period,*[f"{m['annual'][y]:+.2f}" if y in m['annual'] else '해당 없음' for y in ('2022','2023','2024','2025','2026')]])
    ci=u[period+'-'+family]['mean'][1]['ci95'];unc.append([family,period,f"{ci[0]:+.5f} ~ {ci[1]:+.5f}"])
    sides.append([family,period,f"{m['sides']['long']['net']:+.2f}",f"{m['sides']['short']['net']:+.2f}",f"{m['gross']:+.2f}",f"{m['fees']+m['impact']:.2f}",f"{m['funding']:+.2f}"])
  dest=D/f'btc-web-{key}.zip'
  with zipfile.ZipFile(dest,'w',compression=zipfile.ZIP_STORED) as z:
   for f in sorted(source.iterdir()):
    if f.is_file():z.writestr(zipfile.ZipInfo(f.name,(2026,10,2,0,0,0)),f.read_bytes())
  public.append(dest);links.append((dest.name,label+' 全계좌·입력·신호·검산 ZIP'))
 data={'build':'1002w1','account_rows':allrows,'groups':full,'scope':'all inspected development paths, no new OOS; no live or ongoing paper trading','source_audit':'BTC_WEB_RESEARCH_20261002.md','boundary_tests':{'session':7,'flow':4}}
 p=D/'btc-web-evidence.json';p.write_bytes(canonical(data));public.append(p);links.append((p.name,'전체 수치·민감도·신뢰구간 JSON'))
 p=D/'btc-web-summary.csv'
 with p.open('w',newline='') as f:w=csv.DictWriter(f,fieldnames=list(allrows[0]));w.writeheader();w.writerows(allrows)
 public.append(p);links.append((p.name,'80조건 전체 요약 CSV'))
 events=sum(x['v']['events'] for x in proof.values());days=sum(x['v']['daily_equities'] for x in proof.values());files=sum(x['r']['matched_files'] for x in proof.values())
 body='''<!doctype html><html lang="ko"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta http-equiv="Content-Security-Policy" content="default-src 'self';script-src 'none';style-src 'self';img-src 'self' data:;connect-src 'none';object-src 'none';base-uri 'none';form-action 'none'"><title>BTC 인터넷 근거 검증 · 세션과 주문흐름</title><link rel="icon" href="assets/icon.svg"><link rel="stylesheet" href="assets/btc-continuation.css"></head><body><a class="skip" href="#results">결과로 이동</a><header><a href="./">BTC RESEARCH</a><nav><a href="btc-continuation.html">이전 198계좌</a><a href="#proof">검산</a><a href="#downloads">다운로드</a></nav></header><main><p class="eyebrow">BTC-ONLY · 2026.10.02 · BUILD1002w1</p><h1>논문의 수익을,<br>우리 계좌의 근거로.</h1><p class="lead">가격통제 체결압력은 과거 수익을 개선했지만 최근 손실을 넘어선 전략은 아직 아닙니다.</p><div class="facts"><article><b>80</b><span>새 조건별 가상계좌</span></article><article><b>0 / 2</b><span>기본 후보 종합통과</span></article><article><b>BTC만</b><span>실거래·상시모의 없음</span></article></div><p class="boundary">이미 관찰한 Binance BTC 역사 경로의 탐색입니다. 미사용 OOS·Hyperliquid 실적·수익 보장이 아닙니다. 대조군이나 더 좋은 민감도로 실패한 기본 후보를 바꾸지 않았습니다.</p><section><h2>새 근거와 판정</h2><ul><li><b>동일 세션 반전:</b> 2026 논문의 공식 전문·저자 코드를 감사했습니다. 저자 자신의 BTC 선택보정 검정도 실패하며, 낮은 0–2bp 비용·펀딩 누락·경계체결 가정이 있습니다. 기본 UTC00/12 반전은 4년 −73.52%, 최근 −34.76%로 기각. 저자 선택 UTC08/20도 손실입니다.</li><li><b>가격통제 체결압력:</b> 같은 가격 변화에서 예상되는 매수/매도량을 빼고 남은 비정상 압력을 거래했습니다. 4년 +103.53%는 원시흐름 +44.91%보다 높지만 최근 −3.36%, 4년 DD13.70%·실현위험 미달로 기각합니다. 원문 세계11통화·84코인 연구를 BTC 단일로 복제했다고 주장하지 않습니다.</li><li><b>근거를 좁힌 결과:</b> 새로운 perpetual basis 논문은 BTC 계수가 거의0이고 HAR-RV 대비 예측 개선도 없다고 명시합니다. 다종목 pooled 결과를 BTC 수익 근거로 사용하지 않습니다.</li></ul></section><section id="results"><h2>기본 규칙과 모든 대조군</h2><p>주:2022–2025, 최근:2026.01–08. 각1,000USDT, 기간 내 연속. 수익·DD·변동성은 %. SR00·OF_RES만 사전 기본후보, 나머지는 반증·위험·가격 대조입니다.</p>'''
 body+=table(['규칙','4년 수익','4년 DD','최근 수익','최근 DD','주/최근 연변동성','주/최근 보유구간'],base,'base-results')
 body+='''<p>공통 관문: 주수익&gt;52.84%·DD≤13.56%, 최근수익&gt;4.63%·DD≤10.45%, 실현위험·연도·거래수·2배비용·지연을 함께 평가. 위험을 늘린 수익은 새 알파로 취급하지 않습니다.</p></section><section><h2>어떻게 거래 가능한 규칙으로 바꿨나</h2><p>신호 완료 후5분 시가, 추가60/240분 지연에서도 원래 신호 고정. 무거래봉에는 체결하지 않고 유효기간 안 다음 거래봉으로 대기합니다. 수수료5bp+불리한 체결1.5bp/편도, 실제 펀딩률×시간별mark시가, 최소수량.001BTC/최소50USDT, 종료비용을 반영했습니다. 변동성목표20%/명목1배 상한은 진입시 기준입니다.</p><p>정확한 공표 빈티지·호가·부분체결·강제청산·세금·운영비·역사별 거래규정은 복원하지 못했습니다. 선물 비용을 적용한 결과이며 현물/다른 거래소 성과와 혼동하지 않습니다. 잔차흐름은 학습365일에서 현재일을 제외했고, 알려진4개 거래량 상충일은 입력에서 제외했습니다.</p><details><summary>연도별 수익</summary>'''+table(['규칙','기간','2022','2023','2024','2025','2026'],annual,'annual-results')+'</details><details><summary>롱·숏과 비용·펀딩 분해</summary>'+table(['규칙','기간','롱 순손익 USDT','숏 순손익 USDT','고정거래 가격손익','체결비용','펀딩'],sides,'cost-results')+'</details><details><summary>기본 일평균 수익의 불확실성</summary><p>14일 블록2,000회95%구간(%/일). 7/28일·가격/원시흐름 차이는 JSON. 누적 탐색 선택편향을 제거하는 증명이 아닙니다.</p>'+table(['규칙','기간','95% 구간'],unc,'uncertainty-results')+'</details></section><section><h2>실패와 민감도를 전부 보존</h2><details id="matrix"><summary>80개 조건별 계좌 보기</summary>'
 body+=table(['연구','규칙','기간','조건','수익%','DD%','연변동성%','보유구간','체결비용 USDT','펀딩 USDT'],[[r['group'],r['strategy'],r['period'],r['scenario'],f"{r['return_pct']:+.2f}",f"{r['dd_pct']:.2f}",f"{r['realized_vol_pct']:.2f}",r['round_trips'],f"{r['fees']+r['impact']:.2f}",f"{r['funding']:+.2f}"] for r in allrows],'all-accounts')+'</details></section>'
 body+=f'<section id="proof"><h2>독립 검산</h2><p><b>{events:,}개 원장 이벤트·{days:,}개 일말 자산·{files}개 소켓차단 산출물</b>을 검증했습니다. 원시1h/5m·mark·funding ZIP에서 다시 읽어 신호와 수량을 재계산하고 별도 Decimal 원장/5m낙폭을 대조했습니다. 최대 오차7.48×10⁻¹¹USDT 수준, 파일은 전부 바이트 일치. 11개 경계검사에는 미래 가격/체결량 교란·전일동일세션·숏 펀딩·반전 비용·최소량·무거래가 포함됩니다.</p><p>첫 최소금액 테스트의 수량0 fixture와 검산기의 daily mark 복구 누락을 수정한 이력도 연구노트에 남겼습니다. 전략 규칙과 계산 결과는 바꾸지 않았습니다.</p></section>'
 body+='<section><h2>조사 범위와 다음 근거</h2><p>Q1 공식31쪽 PDF의 BTC 방법·검정·한계, Q3 제1저자 학위논문의 자료·잔차화·학습을 읽었습니다. 일부 논문은 초록/기관 메타데이터까지만 확보했으며 전문 열람과 구분했습니다. 문헌 목록의 끝이나 후보 기각은 연구 목표 완료가 아닙니다. 새로운 BTC 전용 변동성·정보흡수·현물/선물 가격발견 근거를 검토합니다.</p><p>이 페이지는 정적 증거 기록으로 실행 상태 표시기가 아닙니다. 상시 모의거래나 실거래 서비스는 가동하지 않았습니다.</p><p><a href="BTC_WEB_RESEARCH_20261002.md">검색질문·원문 URL·읽은 범위·탈락 이유</a></p></section><section id="downloads"><h2>직접 확인할 자료</h2><div class="downloads">'
 for name,label in links:body+='<a download href="downloads/'+esc(name)+'">'+esc(label)+' ↓</a>'
 body+='</div><h3>성과 전 고정한 명세</h3><ul><li><a href="EXPERIMENT_BTC_SESSION_20261002.md">동일 세션 반전 명세</a></li><li><a href="EXPERIMENT_BTC_FLOW_20261002.md">가격통제 체결압력 명세</a></li></ul></section><footer><a href="btc-continuation.html">이전 BTC 연구</a> · <a href="https://github.com/JavisLab/btc-perp-bot">검증 코드</a><p>BUILD1002w1 · BTC-only · 실거래 연결 없음</p></footer></main></body></html>'
 p=DOC/'btc-web-research.html';p.write_text(body);public.append(p)
 p=DOC/'btc-continuation.html';old=p.read_text()
 if 'id="web-frontier-update"' not in old:old=old.replace('<h1>','<p class="boundary" id="web-frontier-update">후속 인터넷 조사·80계좌 검산: <a href="btc-web-research.html">세션과 가격통제 체결압력 결과 ↗</a>. 아래 198계좌는 이전 연구 이력입니다.</p><h1>',1);p.write_text(old)
 public.append(p)
 public += [DOC/n for n in ('BTC_WEB_RESEARCH_20261002.md','EXPERIMENT_BTC_SESSION_20261002.md','EXPERIMENT_BTC_FLOW_20261002.md','assets/btc-continuation.css','assets/icon.svg')]
 manifest={str(p.relative_to(DOC)):{'sha256':sha(p.read_bytes()),'bytes':p.stat().st_size} for p in public};out=ROOT/'runs/btc-web-report-20261002';out.mkdir(exist_ok=True);(out/'public-manifest.json').write_bytes(canonical(manifest));print(json.dumps({'accounts':len(allrows),'events':events,'days':days,'matched_files':files,'public_files':len(public)}))
if __name__=='__main__':run()
