"""Publish only audited HAR/SRV risk results; preserve earlier account studies."""
import csv,gzip,json,zipfile
from pathlib import Path
from build_btc_web_report import read,table,esc
from btc_perp_bot.research.archive import canonical,sha
ROOT=Path(__file__).resolve().parents[1];DOC=ROOT/'docs';D=DOC/'downloads';R=ROOT/'runs/btc-risk-20261002'
def run():
 s=read(R/'summary.json');v=read(R/'verification.json');replay=read(R/'reproduction-v2.json');sel=read(R/'selection.json');assert replay['all_bytes_equal'] and not sel['passed'];forecast=read(R/'forecast-summary.json');unc=read(R/'uncertainty.json');rows=[];base=[];years=[];cost=[];ci=[]
 for key,x in s.items():
  p,n,c=key.split('-');m=x['metrics'];rows.append({'strategy':n,'period':p,'scenario':c,**{k:m[k] for k in ['return_pct','max_drawdown_pct','realized_vol_pct','sharpe','round_trips','fees','impact','funding','mean_exposure','max_exposure']}})
  if c!='base':continue
  years.append([n,p,*[f"{x['annual'][y]['return_pct']:+.2f}" if y in x['annual'] else '해당 없음' for y in ['2022','2023','2024','2025','2026']]])
  cost.append([n,p,f"{m['gross_pnl']:+.2f}",f"{m['fees']+m['impact']:.2f}",'0',f"{m['mean_exposure']*100:.2f}",f"{m['realized_vol_pct']:.2f}"])
  q=unc[p+'-'+n]['vs_E_SPOT'][1]['ci95'];ci.append([n,p,f'{q[0]:+.5f} ~ {q[1]:+.5f}'])
  if p=='main':
   b=s['recent-'+n+'-base']['metrics'];base.append([n+(' · 기본' if n=='V_SRV' else ' · 대조'),f"{m['return_pct']:+.2f}",f"{m['max_drawdown_pct']:.2f}",f"{b['return_pct']:+.2f}",f"{b['max_drawdown_pct']:.2f}",f"{m['round_trips']} / {b['round_trips']}"])
 old=[]
 for p in ['main','recent']:
  m=read(ROOT/f'runs/search-1458/{p}-E_SPOT.json.gz')['metrics'];old.append([p,f"{m['return_pct']:+.2f}",f"{m['max_drawdown_pct']:.2f}",f"{m['realized_vol_pct']:.2f}"])
 evidence={'build':'1002r1','account_rows':rows,'summary':s,'uncertainty':unc,'forecast':forecast,'selection':sel,'verification':v,'reproduction':replay,'data_audit':read(ROOT/'data/btc-rv-20261002/audit.json'),'data_verification':read(ROOT/'data/btc-rv-20261002/verification.json'),'scope':'observed development paths, unchanged long-only BTC spot trend signal; no live trading'}
 (D/'btc-risk-evidence.json').write_bytes(canonical(evidence))
 with (D/'btc-risk-summary.csv').open('w',newline='') as f:w=csv.DictWriter(f,fieldnames=list(rows[0]));w.writeheader();w.writerows(rows)
 with zipfile.ZipFile(D/'btc-risk-evidence.zip','w',compression=zipfile.ZIP_STORED) as z:
  for p in sorted(R.iterdir()):
   if p.is_file():z.writestr(zipfile.ZipInfo(p.name,(2026,10,2,0,0,0)),p.read_bytes())
 body='''<!doctype html><html lang="ko"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta http-equiv="Content-Security-Policy" content="default-src 'self';script-src 'none';style-src 'self';img-src 'self' data:;connect-src 'none';object-src 'none';base-uri 'none';form-action 'none'"><title>BTC 위험예측 검증 · 상승·하락 변동성</title><link rel="icon" href="assets/icon.svg"><link rel="stylesheet" href="assets/btc-continuation.css"></head><body><a class="skip" href="#results">결과로 이동</a><header><a href="./">BTC RESEARCH</a><nav><a href="btc-web-research.html">세션·체결압력 80계좌</a><a href="#downloads">다운로드</a></nav></header><main><p class="eyebrow">BTC-ONLY · BUILD1002r1</p><h1>위험을 더 잘 알아도,<br>수익이 더 낫지는 않습니다.</h1><p class="lead">완료된 5분봉의 상승·하락 변동성을 나눠 기존 방향 신호의 투자 비중을 정했습니다. 기본 후보의 최근 수익은 +0.89%, 종합 기준 미달입니다.</p><div class="facts"><article><b>30</b><span>추가 가상계좌</span></article><article><b>기각</b><span>V_SRV 기본 후보</span></article><article><b>49</b><span>소켓 차단 일치 파일</span></article></div><p class="boundary">2022–2025년과 2026.01–08의 이미 본 개발 자료입니다. 미사용 OOS·실전 수익·최적 전략이 아닙니다. 대조군이나 민감도의 좋은 수치로 기본 후보를 교체하지 않았습니다.</p><section id="results"><h2>같은 방향 신호, 다른 위험 예측</h2><p>각 1,000USDT. V_SRV는 상승/하락 실현분산, V_HAR는 총 실현분산, V_RV20은 단순 20일 평균분산을 사용합니다. 방향은 기존 현물 추세 6신호의 양수 부분 그대로입니다. 수익·낙폭은 %.</p>'''
 body+=table(['규칙','4년 수익','4년 DD','최근 수익','최근 DD','주/최근 보유구간'],base,'base-results')
 body+='<h3>기존 기준 · 저장 결과 참조, 재실행하지 않음</h3>'+table(['E_SPOT 기간','수익%','DD%','연변동성%'],old,'baseline-results')
 body+='''<p>V_SRV는 주수익 &gt;52.84%·최근 &gt;4.63%와 연도별 일관성을 충족하지 못했습니다. 24시간 추가지연 및 주구간 MSE 비교도 탈락했습니다. 낙폭 감소에는 노출 감소가 함께 있으므로 방향 알파로 부르지 않습니다.</p></section><section><h2>예측 오차와 계좌 성과를 분리</h2><p>작을수록 좋은 MSE·QLIKE를 모든 대조군과 비교합니다. 기본 후보는 주구간에서 QLIKE는 개선했지만 MSE는 HAR보다 나쁩니다. 최근 예측 오차 개선도 충분한 순수익 개선을 만들지 못했습니다.</p>'''
 body+=table(['기간','모형','완료 라벨 수','MSE','QLIKE','분산 하한 적용'],[[p,n,x['n'],f"{x['mse']:.9g}",f"{x['qlike']:.6f}",f"{x['floor_fraction']*100:.2f}%"] for p,g in forecast.items() for n,x in g['models'].items()],'forecast-results')
 body+='''</section><section><h2>비용·가용시각·불확실성</h2><p>일말 완료분산으로 다음 날 위험을 예측합니다. 이전 365일 학습에 현재 특징의 미래 라벨을 넣지 않았습니다. 목표위험 20%·명목 1배 상한, 현물 0.00001BTC/최소5USDT, 편도 수수료10bp+충격1.5bp, 신호 후1시간 실제 시가, 5%p 리밸런싱 밴드, 종료비용 포함. 추가1/24시간 지연·비용2배·위험10%를 전부 남겼습니다.</p><p>거래는 현물 롱/현금뿐이므로 펀딩은 0이며 누락이 아닙니다. 무기한선물 5분봉은 위험 프록시로만 사용합니다. 현물 한 시간 결측에서 기존 보유가격 평가가 남은 이력, 호가/부분체결/세금/시점별 규정 미복원도 보존합니다.</p><details><summary>연도별 수익</summary>'''+table(['규칙','기간','2022','2023','2024','2025','2026'],years,'annual-results')+'</details><details><summary>체결비용과 실제 노출</summary>'+table(['규칙','기간','가격손익 USDT','비용 USDT','펀딩 USDT','평균 명목노출%','연변동성%'],cost,'cost-results')+'</details><details><summary>기존 현물 대비 일수익 차이의 불확실성</summary><p>14일 블록2,000회95%구간, %/일. 7/28일·HAR 대비·예측손실 차이는 JSON. 누적 탐색 선택편향을 제거하지 못합니다.</p>'+table(['규칙','기간','95% 구간'],ci,'uncertainty-results')+'</details></section><section><h2>실패·민감도 전부 보존</h2><details id="matrix"><summary>30개 조건별 계좌</summary>'
 body+=table(['규칙','기간','조건','수익%','DD%','연변동성%','보유구간','비용 USDT'],[[r['strategy'],r['period'],r['scenario'],f"{r['return_pct']:+.2f}",f"{r['max_drawdown_pct']:.2f}",f"{r['realized_vol_pct']:.2f}",r['round_trips'],f"{r['fees']+r['impact']:.2f}"] for r in rows],'all-accounts')+'</details></section>'
 body+=f'''<section id="proof"><h2>독립 검산</h2><p>공식 BTC 701,280개 5분봉 → 2,435일 실현분산을 별도 검산했습니다. 학습 준비용 21개월만 새로 수집하고 기존 복구 이력을 보존했습니다. 원시 로그수익 계산차이 최대3.56×10⁻¹⁶.</p><p>별도 정규방정식으로 {v['independent_forecast_models']:,}개 예측 모형, raw 현물 6신호 {v['raw_daily_decisions']:,}개 판단, 폐형식 수량 {v['independent_target_quantities']:,}개·무거래 {v['no_trade_decisions']:,}개 및 Decimal 계좌 {v['events']:,}개 이벤트·{v['daily_equities']:,}개 일말 자산을 대조했습니다. 최대 수치오차2×10⁻¹¹USDT, 네 경계검사 통과, 신규49파일 소켓 차단 바이트 일치.</p></section><section><h2>원문이 말하는 범위</h2><p>Q9·Q10 공개 전문은 비대칭 분산/꼬리의 위험예측을 연구합니다. 최적 모형은 표본·예측기간에 따라 다릅니다. 추가 인용 원문(arXiv1912.05228)도 점프 분해의 주된 이득을 장기 예측에서 찾으며 1일 예측의 보편적 우위를 주장하지 않습니다. 이 규칙은 해당 논문의 수익 재현이 아닌 자체 검증입니다.</p><p>연구 목표는 아직 미완료입니다. 정적 보고서가 작업 지속이나 실거래 상태를 뜻하지 않습니다.</p></section><section id="downloads"><h2>검증 자료</h2><div class="downloads"><a download href="downloads/btc-risk-evidence.zip">30계좌·신호·예측·검산 ZIP ↓</a><a download href="downloads/btc-risk-evidence.json">전체 요약·신뢰구간 JSON ↓</a><a download href="downloads/btc-risk-summary.csv">30조건 요약 CSV ↓</a></div><p><a href="EXPERIMENT_BTC_RISK_20261002.md">성과 전 명세</a> · <a href="BTC_WEB_RESEARCH_20261002.md">검색·원문 감사 기록</a></p></section><footer>BUILD1002r1 · BTC-only · 실거래 없음</footer></main></body></html>'''
 (DOC/'btc-risk-research.html').write_text(body)
 p=DOC/'btc-web-research.html';old=p.read_text()
 if 'id="risk-followup"' not in old:p.write_text(old.replace('<h1>','<p id="risk-followup" class="boundary">후속 30계좌: <a href="btc-risk-research.html">상승·하락 변동성 위험배분 검증 ↗</a></p><h1>',1))
 files=['btc-risk-research.html','btc-web-research.html','downloads/btc-risk-evidence.zip','downloads/btc-risk-evidence.json','downloads/btc-risk-summary.csv','EXPERIMENT_BTC_RISK_20261002.md','BTC_WEB_RESEARCH_20261002.md','assets/btc-continuation.css','assets/icon.svg'];manifest={n:{'sha256':sha((DOC/n).read_bytes()),'bytes':(DOC/n).stat().st_size} for n in files};out=ROOT/'runs/btc-risk-report-20261002';out.mkdir(exist_ok=True);(out/'public-manifest.json').write_bytes(canonical(manifest));print(json.dumps({'accounts':len(rows),'public_files':len(files)}))
if __name__=='__main__':run()
